import {
  CoercionDecl,
  EnumDef,
  FieldDecl,
  FileDecl,
  MethodStubDecl,
  PropertyCategory,
  TypeDecl,
  WireFieldMapping,
} from "../../ir/declarations.js";
import { ExprVisitor } from "../../ir/visitor.js";
import { swiftFunctionName, swiftPropertyName, swiftStringLiteral, swiftTypeName } from "./identifiers.js";

const SWIFT_TYPE_MAP: Record<string, string> = {
  string: "String",
  boolean: "Bool",
  int32: "Int32",
  int64: "Int64",
  integer: "Int",
  float32: "Float",
  float64: "Double",
  float: "Double",
  number: "Double",
  numeric: "Double",
  any: "Any",
  unknown: "Any",
  object: "[String: Any]",
  dictionary: "[String: Any]",
  array: "[Any]",
};

export function emitSwiftFile(file: FileDecl, visitor: ExprVisitor, polymorphicTypeNames: Set<string>): string {
  const lines: string[] = [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    "",
    "import Foundation",
    "",
  ];

  for (const enumDef of file.enums) {
    emitEnum(enumDef, lines);
  }

  for (const type of file.types) {
    emitType(type, lines, visitor, polymorphicTypeNames);
  }

  return trimBlankLines(lines).join("\n") + "\n";
}

function emitType(type: TypeDecl, lines: string[], visitor: ExprVisitor, polymorphicTypeNames: Set<string>): void {
  if (type.polymorphicDispatch) {
    emitPolymorphicEnum(type, lines);
    return;
  }
  if (type.isProtocol) {
    emitProtocol(type, lines);
    return;
  }
  emitStruct(type, lines, visitor, polymorphicTypeNames);
}

function emitEnum(enumDef: EnumDef, lines: string[]): void {
  const typeName = swiftTypeName(enumDef.name);
  if (enumDef.isOpen) {
    lines.push(`public struct ${typeName}: RawRepresentable, Equatable, Hashable, Codable {`);
    lines.push("  public let rawValue: String");
    lines.push("  public init(rawValue: String) { self.rawValue = rawValue }");
    for (const value of enumDef.values) {
      lines.push(`  public static let ${swiftPropertyName(value)} = ${typeName}(rawValue: ${swiftStringLiteral(value)})`);
    }
    emitEnumParseMethod(enumDef, lines, typeName);
    lines.push("}");
    lines.push("");
    return;
  }

  lines.push(`public enum ${typeName}: String, Codable, CaseIterable {`);
  for (const value of enumDef.values) {
    lines.push(`  case ${swiftPropertyName(value)} = ${swiftStringLiteral(value)}`);
  }
  emitEnumParseMethod(enumDef, lines, typeName);
  lines.push("}");
  lines.push("");
}

function emitEnumParseMethod(enumDef: EnumDef, lines: string[], typeName: string): void {
  lines.push(`  public static func parse(_ value: String) throws -> ${typeName} {`);
  lines.push("    switch value {");
  for (const value of enumDef.values) {
    lines.push(`    case ${swiftStringLiteral(value)}: return ${enumDef.isOpen ? `.${swiftPropertyName(value)}` : `.${swiftPropertyName(value)}`}`);
  }
  for (const [canonical, aliases] of Object.entries(enumDef.parseAliases)) {
    for (const alias of aliases) {
      lines.push(`    case ${swiftStringLiteral(alias)}: return .${swiftPropertyName(canonical)}`);
    }
  }
  if (enumDef.isOpen) {
    lines.push(`    default: return ${typeName}(rawValue: value)`);
  } else {
    lines.push(`    default: throw TypraRuntimeError.invalidEnum(type: ${swiftStringLiteral(typeName)}, value: value)`);
  }
  lines.push("    }");
  lines.push("  }");
}

function emitPolymorphicEnum(type: TypeDecl, lines: string[]): void {
  const typeName = swiftTypeName(type.typeName.name);
  const dispatch = type.polymorphicDispatch!;
  lines.push(`public enum ${typeName}: TypraModel {`);
  for (const variant of dispatch.variants) {
    const childName = swiftTypeName(variant.typeName.name);
    lines.push(`  case ${swiftPropertyName(variant.typeName.name)}(${childName})`);
  }
  if (!dispatch.isAbstract) {
    lines.push("  case unknown([String: Any])");
  }
  lines.push("");
  lines.push(`  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws -> ${typeName} {`);
  lines.push(`    let object = try TypraRuntime.object(data, typeName: ${swiftStringLiteral(typeName)})`);
  lines.push(`    let discriminator = try TypraRuntime.string(object[${swiftStringLiteral(dispatch.discriminatorField)}] ?? "", field: ${swiftStringLiteral(dispatch.discriminatorField)})`);
  lines.push("    switch discriminator {");
  for (const variant of dispatch.variants) {
    lines.push(`    case ${swiftStringLiteral(variant.value)}: return .${swiftPropertyName(variant.typeName.name)}(try ${swiftTypeName(variant.typeName.name)}.load(data, context: context))`);
  }
  if (dispatch.defaultVariant && !dispatch.defaultVariant.isSelfReference) {
    lines.push(`    default: return .${swiftPropertyName(dispatch.defaultVariant.typeName.name)}(try ${swiftTypeName(dispatch.defaultVariant.typeName.name)}.load(data, context: context))`);
  } else if (!dispatch.isAbstract) {
    lines.push("    default: return .unknown(object)");
  } else {
    lines.push(`    default: throw TypraRuntimeError.unknownDiscriminator(type: ${swiftStringLiteral(typeName)}, field: ${swiftStringLiteral(dispatch.discriminatorField)}, value: discriminator)`);
  }
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {");
  lines.push("    switch self {");
  for (const variant of dispatch.variants) {
    lines.push(`    case .${swiftPropertyName(variant.typeName.name)}(let value): return try value.save(context)`);
  }
  if (!dispatch.isAbstract) {
    lines.push("    case .unknown(let value): return value");
  }
  lines.push("    }");
  lines.push("  }");
  emitJsonYamlMethods(typeName, lines);
  lines.push("}");
  lines.push("");
}

function emitProtocol(type: TypeDecl, lines: string[]): void {
  const typeName = swiftTypeName(type.typeName.name);
  lines.push(`public protocol ${typeName} {`);
  for (const method of type.methods) {
    const params = Object.entries(method.params)
      .map(([name, typeName]) => `${swiftPropertyName(name)}: ${swiftProtocolType(typeName)}`)
      .join(", ");
    const asyncToken = method.sync ? "" : " async";
    const returnType = swiftProtocolType(method.returns);
    lines.push(`  func ${swiftFunctionName(method.name)}(${params})${asyncToken} throws${returnType === "Void" ? "" : ` -> ${returnType}`}`);
  }
  lines.push("}");
  lines.push("");
}

function emitStruct(type: TypeDecl, lines: string[], visitor: ExprVisitor, polymorphicTypeNames: Set<string>): void {
  const typeName = swiftTypeName(type.typeName.name);
  if (type.description) {
    lines.push(`/// ${type.description.replace(/\r?\n/g, " ")}`);
  }
  const conformances = ["TypraModel"];
  lines.push(`public struct ${typeName}: ${conformances.join(", ")} {`);
  for (const field of type.fields) {
    lines.push(`  public var ${swiftPropertyName(field.name)}: ${swiftFieldType(field, polymorphicTypeNames)}${field.isOptional ? " = nil" : ` = ${swiftDefaultValue(field, polymorphicTypeNames)}`}`);
  }
  lines.push("");
  lines.push(`  public init(${type.fields.map(field => `${swiftPropertyName(field.name)}: ${swiftFieldType(field, polymorphicTypeNames)} = ${field.isOptional ? "nil" : swiftDefaultValue(field, polymorphicTypeNames)}`).join(", ")}) {`);
  for (const field of type.fields) {
    lines.push(`    self.${swiftPropertyName(field.name)} = ${swiftPropertyName(field.name)}`);
  }
  lines.push("  }");
  lines.push("");
  emitLoad(type, lines, polymorphicTypeNames);
  lines.push("");
  emitSave(type, lines, polymorphicTypeNames);
  if (type.wire) {
    lines.push("");
    emitToWire(type, lines, polymorphicTypeNames);
  }
  emitJsonYamlMethods(typeName, lines);
  for (const factory of type.factories) {
    lines.push("");
    const params = Object.entries(factory.params).map(([name, paramType]) => `${swiftPropertyName(name)}: ${swiftScalarType(paramType)}`).join(", ");
    lines.push(`  public static func ${swiftFunctionName(factory.name)}(${params}) -> ${typeName} {`);
    lines.push(`    return ${visitor.visitExpr(factory.body)}`);
    lines.push("  }");
  }
  for (const method of type.methods) {
    emitMethodStub(method, lines);
  }
  lines.push("}");
  lines.push("");
}

function emitLoad(type: TypeDecl, lines: string[], polymorphicTypeNames: Set<string>): void {
  const typeName = swiftTypeName(type.typeName.name);
  lines.push(`  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws -> ${typeName} {`);
  for (const coercion of type.load.coercions) {
    emitCoercion(type, coercion, lines, polymorphicTypeNames);
  }
  lines.push(`    let object = try TypraRuntime.object(data, typeName: ${swiftStringLiteral(typeName)})`);
  lines.push(`    var instance = ${typeName}()`);
  for (const assignment of type.load.assignments) {
    const field = type.fields.find(f => f.name === assignment.fieldName);
    lines.push(`    if let value = object[${swiftStringLiteral(assignment.sourceName)}] {`);
    lines.push(`      instance.${swiftPropertyName(assignment.fieldName)} = ${swiftLoadExpression(assignment.category, assignment.enumName, assignment.fieldName, "value", polymorphicTypeNames)}`);
    lines.push("    }");
    if (field?.defaultValue !== null && field?.defaultValue !== undefined && !field.isOptional) {
      lines.push("    else {");
      lines.push(`      instance.${swiftPropertyName(field.name)} = ${swiftLiteralDefault(field)}`);
      lines.push("    }");
    }
  }
  lines.push("    return instance");
  lines.push("  }");
}

function emitCoercion(type: TypeDecl, coercion: CoercionDecl, lines: string[], polymorphicTypeNames: Set<string>): void {
  const check = swiftCoercionCheck(coercion.scalarType);
  if (!check) return;
  lines.push(`    if let scalar = ${check} {`);
  lines.push(`      var instance = ${swiftTypeName(type.typeName.name)}()`);
  for (const assignment of coercion.assignments) {
    const field = type.fields.find(f => f.name === assignment.fieldName);
    const fieldName = assignment.fieldName;
    const expr = assignment.isInput
      ? swiftLoadExpression(field?.category ?? { kind: "scalar", scalarType: coercion.scalarType }, field?.enumName ?? null, fieldName, "scalar", polymorphicTypeNames)
      : swiftLiteralForField(field, assignment.literalValue ?? "");
    lines.push(`      instance.${swiftPropertyName(fieldName)} = ${expr}`);
  }
  lines.push("      return instance");
  lines.push("    }");
}

function emitSave(type: TypeDecl, lines: string[], polymorphicTypeNames: Set<string>): void {
  lines.push("  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {");
  lines.push("    var result: [String: Any] = [:]");
  for (const assignment of type.save.assignments) {
    const prop = `self.${swiftPropertyName(assignment.fieldName)}`;
    const serialized = swiftSaveExpression(assignment.category, assignment.enumName, prop, polymorphicTypeNames);
    if (assignment.isOptional) {
      lines.push(`    if let value = ${prop} {`);
      lines.push(`      result[${swiftStringLiteral(assignment.targetName)}] = ${swiftSaveExpression(assignment.category, assignment.enumName, "value", polymorphicTypeNames)}`);
      lines.push("    }");
    } else {
      lines.push(`    result[${swiftStringLiteral(assignment.targetName)}] = ${serialized}`);
    }
  }
  lines.push("    return result");
  lines.push("  }");
}

function emitToWire(type: TypeDecl, lines: string[], polymorphicTypeNames: Set<string>): void {
  lines.push("  public func toWire(_ provider: String, context: SaveContext = SaveContext()) throws -> [String: Any] {");
  lines.push("    var result: [String: Any] = [:]");
  for (const mapping of type.wire!.mappings) {
    emitWireField(mapping, lines, polymorphicTypeNames);
  }
  lines.push("    return result");
  lines.push("  }");
}

function emitWireField(mapping: WireFieldMapping, lines: string[], polymorphicTypeNames: Set<string>): void {
  const source = `self.${swiftPropertyName(mapping.fieldName)}`;
  const target = `wireName${swiftTypeName(mapping.fieldName)}`;
  lines.push(`    let ${target}: String`);
  lines.push("    switch provider {");
  for (const [provider, wireName] of Object.entries(mapping.wireNames)) {
    lines.push(`    case ${swiftStringLiteral(provider)}: ${target} = ${swiftStringLiteral(wireName)}`);
  }
  lines.push(`    default: ${target} = ${swiftStringLiteral(mapping.fieldName)}`);
  lines.push("    }");
  if (mapping.isOptional) {
    lines.push(`    if let value = ${source} { result[${target}] = ${swiftSaveExpression(mapping.category, null, "value", polymorphicTypeNames)} }`);
  } else {
    lines.push(`    result[${target}] = ${swiftSaveExpression(mapping.category, null, source, polymorphicTypeNames)}`);
  }
}

function emitJsonYamlMethods(typeName: string, lines: string[]): void {
  lines.push("");
  lines.push(`  public static func fromJSON(_ json: String, context: LoadContext = LoadContext()) throws -> ${typeName} {`);
  lines.push(`    return try load(TypraRuntime.jsonObject(from: json, typeName: ${swiftStringLiteral(typeName)}), context: context)`);
  lines.push("  }");
  lines.push("");
  lines.push("  public func toJSON(_ context: SaveContext = SaveContext()) throws -> String {");
  lines.push("    return try TypraRuntime.jsonString(from: save(context))");
  lines.push("  }");
  lines.push("");
  lines.push(`  public static func fromYAML(_ yaml: String, context: LoadContext = LoadContext()) throws -> ${typeName} {`);
  lines.push(`    return try load(TypraRuntime.yamlObject(from: yaml, typeName: ${swiftStringLiteral(typeName)}), context: context)`);
  lines.push("  }");
  lines.push("");
  lines.push("  public func toYAML(_ context: SaveContext = SaveContext()) throws -> String {");
  lines.push("    return try TypraRuntime.yamlString(from: save(context))");
  lines.push("  }");
}

function emitMethodStub(method: MethodStubDecl, lines: string[]): void {
  const params = Object.entries(method.params).map(([name, typeName]) => `${swiftPropertyName(name)}: ${swiftProtocolType(typeName)}`).join(", ");
  const asyncToken = method.sync ? "" : " async";
  const returnType = swiftProtocolType(method.returns);
  lines.push("");
  lines.push(`  public func ${swiftFunctionName(method.name)}(${params})${asyncToken} throws${returnType === "Void" ? "" : ` -> ${returnType}`} {`);
  lines.push(`    throw TypraRuntimeError.unsupported(${swiftStringLiteral(`${method.name} must be implemented by hand-authored code.`)})`);
  lines.push("  }");
}

function swiftFieldType(field: FieldDecl, polymorphicTypeNames: Set<string>): string {
  const base = swiftCategoryType(field.category, field.enumName, polymorphicTypeNames);
  return field.isOptional ? `${base}?` : base;
}

function swiftCategoryType(category: PropertyCategory, enumName: string | null, polymorphicTypeNames: Set<string>): string {
  switch (category.kind) {
    case "scalar":
      return enumName ? swiftTypeName(enumName) : swiftScalarType(category.scalarType);
    case "complex":
      return swiftTypeName(category.typeName);
    case "collection_scalar":
      return `[${swiftScalarType(category.scalarType)}]`;
    case "collection_complex":
      return `[${swiftTypeName(category.typeName)}]`;
    case "dict":
      return "[String: Any]";
  }
}

function swiftScalarType(typeName: string): string {
  return SWIFT_TYPE_MAP[typeName] ?? swiftTypeName(typeName);
}

function swiftDefaultValue(field: FieldDecl, polymorphicTypeNames: Set<string>): string {
  if (field.defaultValue !== null && field.defaultValue !== undefined) {
    return swiftLiteralDefault(field);
  }
  if (field.enumName) return `(try! ${swiftTypeName(field.enumName)}.parse(${swiftStringLiteral(field.allowedValues[0] ?? "")}))`;
  switch (field.category.kind) {
    case "scalar":
      return scalarDefault(field.category.scalarType);
    case "complex":
      return polymorphicTypeNames.has(field.category.typeName) ? ".unknown([:])" : `${swiftTypeName(field.category.typeName)}()`;
    case "collection_scalar":
    case "collection_complex":
      return "[]";
    case "dict":
      return "[:]";
  }
}

function swiftLiteralDefault(field: FieldDecl): string {
  return swiftLiteralForField(field, field.defaultValue);
}

function swiftLiteralForField(field: FieldDecl | undefined, value: string | number | boolean | null): string {
  if (field?.enumName && typeof value === "string") {
    return `(try! ${swiftTypeName(field.enumName)}.parse(${swiftStringLiteral(value)}))`;
  }
  if (typeof value === "string") return swiftStringLiteral(value);
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return "nil";
}

function scalarDefault(typeName: string): string {
  switch (typeName) {
    case "string": return "\"\"";
    case "boolean": return "false";
    case "int32": return "0";
    case "int64": return "0";
    case "integer": return "0";
    case "float32": return "0";
    case "float64":
    case "float":
    case "number":
    case "numeric": return "0";
    case "object":
    case "dictionary": return "[:]";
    case "array": return "[]";
    default: return "NSNull()";
  }
}

function swiftLoadExpression(category: PropertyCategory, enumName: string | null, fieldName: string, valueExpr: string, polymorphicTypeNames: Set<string>): string {
  switch (category.kind) {
    case "scalar":
      if (enumName) return `try ${swiftTypeName(enumName)}.parse(try TypraRuntime.string(${valueExpr}, field: ${swiftStringLiteral(fieldName)}))`;
      return scalarLoadExpression(category.scalarType, valueExpr, fieldName);
    case "complex":
      return `try ${swiftTypeName(category.typeName)}.load(${valueExpr}, context: context)`;
    case "collection_scalar":
      return `try TypraRuntime.array(${valueExpr}, field: ${swiftStringLiteral(fieldName)}).map { ${scalarLoadExpression(category.scalarType, "$0", fieldName)} }`;
    case "collection_complex":
      return `try TypraRuntime.array(${valueExpr}, field: ${swiftStringLiteral(fieldName)}).map { try ${swiftTypeName(category.typeName)}.load($0, context: context) }`;
    case "dict":
      return `try TypraRuntime.dictionary(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
  }
}

function scalarLoadExpression(scalarType: string, valueExpr: string, fieldName: string): string {
  switch (scalarType) {
    case "string": return `try TypraRuntime.string(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "boolean": return `try TypraRuntime.bool(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "int32": return `try TypraRuntime.int32(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "int64": return `try TypraRuntime.int64(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "integer": return `try TypraRuntime.int(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "float32": return `try TypraRuntime.float(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "float64":
    case "float":
    case "number":
    case "numeric": return `try TypraRuntime.double(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "object":
    case "dictionary": return `try TypraRuntime.dictionary(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "array": return `try TypraRuntime.array(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    default: return valueExpr;
  }
}

function swiftSaveExpression(category: PropertyCategory, enumName: string | null, valueExpr: string, polymorphicTypeNames: Set<string>): string {
  switch (category.kind) {
    case "scalar":
      return enumName ? `${valueExpr}.rawValue` : valueExpr;
    case "complex":
      return `try ${valueExpr}.save(context)`;
    case "collection_scalar":
      return valueExpr;
    case "collection_complex":
      return `try ${valueExpr}.map { try $0.save(context) }`;
    case "dict":
      return valueExpr;
  }
}

function swiftCoercionCheck(scalarType: string): string | undefined {
  switch (scalarType) {
    case "string": return "data as? String";
    case "boolean": return "data as? Bool";
    case "int32":
    case "int64":
    case "integer": return "data as? Int";
    case "float32":
    case "float64":
    case "float":
    case "number":
    case "numeric": return "data as? Double";
    default: return undefined;
  }
}

function swiftProtocolType(typeName: string): string {
  const lower = typeName.toLowerCase();
  if (lower === "void") return "Void";
  return swiftScalarType(lower === "unknown" ? "any" : typeName);
}

function trimBlankLines(lines: string[]): string[] {
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  return lines;
}
