import {
  CollectionHelperDecl,
  CoercionDecl,
  EnumDef,
  FieldDecl,
  FileDecl,
  MethodStubDecl,
  PropertyCategory,
  TypeDecl,
  WireFieldMapping,
  isClosedPolymorphicDispatch,
} from "../../ir/declarations.js";
import { shouldGuardMissingRequiredField, shouldOmitAbsentOnSave } from "../../ir/field-emission-policy.js";
import { ExprVisitor } from "../../ir/visitor.js";
import { flattenInheritance } from "../../ir/inheritance.js";
import { swiftFunctionName, swiftPropertyName, swiftStringLiteral, swiftTypeName } from "./identifiers.js";
import { SWIFT_TYPE_MAP, swiftType } from "./types.js";

interface SwiftPolymorphicDefaultCase {
  typeName: string;
  carriesRaw: boolean;
}

type SwiftNativeSerialization = "none" | "codable";

export function emitSwiftFile(
  file: FileDecl,
  visitor: ExprVisitor,
  polymorphicTypeNames: Set<string>,
  declarationUniverse: TypeDecl[] = file.types,
  nativeSerialization: SwiftNativeSerialization = "none",
): string {
  const augmentedUniverse = addNamedCollectionFields(declarationUniverse);
  const polymorphicDefaultCases = new Map<string, SwiftPolymorphicDefaultCase | null>(
    augmentedUniverse
      .filter(type => type.polymorphicDispatch !== null)
      .map(type => {
        const dispatch = type.polymorphicDispatch!;
        const fallback = dispatch.defaultVariant;
        const fallbackIsDeclaredVariant = fallback
          ? dispatch.variants.some(variant => variant.typeName.name === fallback.typeName.name)
          : false;
        const closedDefault = isClosedPolymorphicDispatch(dispatch) && dispatch.variants[0]
          ? { typeName: dispatch.variants[0].typeName.name, carriesRaw: false }
          : null;
        return [
          type.typeName.name,
          fallback && !fallback.isSelfReference
            ? { typeName: fallback.typeName.name, carriesRaw: !fallbackIsDeclaredVariant }
            : closedDefault,
        ] as const;
      }),
  );
  const emittedKeys = new Set(file.types.map(typeKey));
  const fileTypes = augmentedUniverse.filter(type => emittedKeys.has(typeKey(type)));
  const types = flattenInheritance(fileTypes, augmentedUniverse);
  const lines: string[] = [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    "",
    "import Foundation",
    "",
  ];

  for (const enumDef of file.enums) {
    emitEnum(enumDef, lines);
  }

  for (const type of types) {
    emitType(type, lines, visitor, polymorphicTypeNames, types, polymorphicDefaultCases, nativeSerialization);
  }

  return trimBlankLines(lines).join("\n") + "\n";
}

function emitType(
  type: TypeDecl,
  lines: string[],
  visitor: ExprVisitor,
  polymorphicTypeNames: Set<string>,
  allTypes: TypeDecl[],
  polymorphicDefaultCases: ReadonlyMap<string, SwiftPolymorphicDefaultCase | null>,
  nativeSerialization: SwiftNativeSerialization,
): void {
  if (type.polymorphicDispatch) {
    emitPolymorphicEnum(type, lines, allTypes, nativeSerialization);
    return;
  }
  if (type.isProtocol) {
    emitProtocol(type, lines);
    return;
  }
  emitStruct(type, lines, visitor, polymorphicTypeNames, polymorphicDefaultCases, nativeSerialization);
}

function emitEnum(enumDef: EnumDef, lines: string[]): void {
  const typeName = swiftTypeName(enumDef.name);
  if (enumDef.isOpen) {
    lines.push(`public struct ${typeName}: RawRepresentable, Equatable, Hashable, Codable {`);
    lines.push("  public let rawValue: String");
    lines.push("  public init(rawValue: String) { self.rawValue = rawValue }");
    for (const value of enumDef.values) {
      lines.push(`  public static let ${swiftPropertyName(value)} = ${typeName}(rawValue: ${swiftStringLiteral(value)})`);
    }
    emitEnumParseMethod(enumDef, lines, typeName);
    lines.push("}");
    lines.push("");
    return;
  }

  lines.push(`public enum ${typeName}: String, Codable, CaseIterable {`);
  for (const value of enumDef.values) {
    lines.push(`  case ${swiftPropertyName(value)} = ${swiftStringLiteral(value)}`);
  }
  emitEnumParseMethod(enumDef, lines, typeName);
  lines.push("}");
  lines.push("");
}

function emitEnumParseMethod(enumDef: EnumDef, lines: string[], typeName: string): void {
  lines.push(`  public static func parse(_ value: String) throws -> ${typeName} {`);
  lines.push("    switch value {");
  for (const value of enumDef.values) {
    lines.push(`    case ${swiftStringLiteral(value)}: return ${enumDef.isOpen ? `.${swiftPropertyName(value)}` : `.${swiftPropertyName(value)}`}`);
  }
  for (const [canonical, aliases] of Object.entries(enumDef.parseAliases)) {
    for (const alias of aliases) {
      lines.push(`    case ${swiftStringLiteral(alias)}: return .${swiftPropertyName(canonical)}`);
    }
  }
  if (enumDef.isOpen) {
    lines.push(`    default: return ${typeName}(rawValue: value)`);
  } else {
    lines.push(`    default: throw TypraRuntimeError.invalidEnum(type: ${swiftStringLiteral(typeName)}, value: value)`);
  }
  lines.push("    }");
  lines.push("  }");
}

function emitPolymorphicEnum(
  type: TypeDecl,
  lines: string[],
  allTypes: TypeDecl[],
  nativeSerialization: SwiftNativeSerialization,
): void {
  const typeName = swiftTypeName(type.typeName.name);
  const dispatch = type.polymorphicDispatch!;
  const indirect = isRecursivePolymorphicEnum(type, allTypes) ? "indirect " : "";
  const conformances = ["TypraModel"];
  if (nativeSerialization === "codable") conformances.push("Codable");
  lines.push(`public ${indirect}enum ${typeName}: ${conformances.join(", ")} {`);
  const fallback = dispatch.defaultVariant && !dispatch.defaultVariant.isSelfReference
    ? dispatch.defaultVariant
    : null;
  const isClosed = isClosedPolymorphicDispatch(dispatch);
  const usesUnknownFallback = fallback === null && !isClosed;
  for (const variant of dispatch.variants) {
    const childName = swiftTypeName(variant.typeName.name);
    lines.push(`  case ${swiftPropertyName(variant.typeName.name)}(${childName})`);
  }
  if (fallback && !dispatch.variants.some(variant => variant.typeName.name === fallback.typeName.name)) {
    lines.push(`  case ${swiftPropertyName(fallback.typeName.name)}(${swiftTypeName(fallback.typeName.name)}, [String: Any])`);
  }
  if (usesUnknownFallback) {
    lines.push("  case unknown([String: Any])");
  }
  lines.push("");
  lines.push(`  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws -> ${typeName} {`);
  lines.push(`    ${type.load.coercions.length > 0 ? "var" : "let"} normalizedData: Any = data`);
  for (const coercion of type.load.coercions) {
    emitPolymorphicCoercion(coercion, type, lines);
  }
  lines.push(`    let object = try TypraRuntime.object(normalizedData, typeName: ${swiftStringLiteral(typeName)})`);
  lines.push(`    let discriminator = try TypraRuntime.string(object[${swiftStringLiteral(dispatch.discriminatorField)}] ?? NSNull(), field: ${swiftStringLiteral(dispatch.discriminatorField)})`);
  lines.push("    if discriminator.isEmpty {");
  lines.push(`      throw TypraRuntimeError.invalidField(field: context.at(${swiftStringLiteral(dispatch.discriminatorField)}).path, expected: "non-blank string")`);
  lines.push("    }");
  lines.push("    switch discriminator {");
  for (const variant of dispatch.variants) {
    lines.push(`    case ${swiftStringLiteral(variant.value)}: return .${swiftPropertyName(variant.typeName.name)}(try ${swiftTypeName(variant.typeName.name)}.load(normalizedData, context: context))`);
  }
  if (fallback) {
    lines.push(`    default: return .${swiftPropertyName(fallback.typeName.name)}(try ${swiftTypeName(fallback.typeName.name)}.load(normalizedData, context: context), object)`);
  } else if (isClosed) {
    lines.push(`    default: throw TypraRuntimeError.unknownDiscriminator(type: ${swiftStringLiteral(typeName)}, field: ${swiftStringLiteral(dispatch.discriminatorField)}, value: discriminator)`);
  } else {
    lines.push("    default: return .unknown(object)");
  }
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {");
  lines.push("    switch self {");
  for (const variant of dispatch.variants) {
    lines.push(`    case .${swiftPropertyName(variant.typeName.name)}(let value): return try value.save(context)`);
  }
  if (fallback && !dispatch.variants.some(variant => variant.typeName.name === fallback.typeName.name)) {
    lines.push(`    case .${swiftPropertyName(fallback.typeName.name)}(let value, let raw):`);
    lines.push("      var result = raw");
    lines.push("      for (key, item) in try value.save(context) {");
    lines.push("        result[key] = item");
    lines.push("      }");
    lines.push("      return result");
  }
  if (usesUnknownFallback) {
    lines.push("    case .unknown(let value): return value");
  }
  lines.push("    }");
  lines.push("  }");
  if (nativeSerialization === "codable") {
    emitCodableDelegation(typeName, lines);
  }
  emitJsonYamlMethods(typeName, lines);
  lines.push("}");
  lines.push("");
}

function isRecursivePolymorphicEnum(type: TypeDecl, allTypes: TypeDecl[]): boolean {
  const targetName = type.typeName.name;
  const byName = new Map(allTypes.map(candidate => [candidate.typeName.name, candidate]));
  const visited = new Set<string>();

  function referencesTarget(typeName: string): boolean {
    if (typeName === targetName) return true;
    if (visited.has(typeName)) return false;
    visited.add(typeName);
    const candidate = byName.get(typeName);
    if (!candidate) return false;
    return candidate.fields.some(field => {
      if (field.category.kind !== "complex" && field.category.kind !== "collection_complex") return false;
      return referencesTarget(field.category.typeName);
    });
  }

  const relatedTypes = [
    ...type.polymorphicDispatch!.variants.map(variant => variant.typeName.name),
    ...(type.polymorphicDispatch!.defaultVariant &&
      !type.polymorphicDispatch!.defaultVariant.isSelfReference
      ? [type.polymorphicDispatch!.defaultVariant.typeName.name]
      : []),
  ];
  return relatedTypes.some(referencesTarget);
}

function emitProtocol(type: TypeDecl, lines: string[]): void {
  const typeName = swiftTypeName(type.typeName.name);
  lines.push(`public protocol ${typeName}: Sendable {`);
  for (const method of type.methods) {
    const params = Object.entries(method.params)
      .map(([name, typeName]) => `${swiftPropertyName(name)}: ${swiftType(typeName)}`)
      .join(", ");
    const asyncToken = method.sync ? "" : " async";
    const returnType = swiftType(method.returns);
    lines.push(`  func ${swiftFunctionName(method.name)}(${params})${asyncToken} throws${returnType === "Void" ? "" : ` -> ${returnType}`}`);
  }
  lines.push("}");
  lines.push("");
}

function emitPolymorphicCoercion(
  coercion: CoercionDecl,
  type: TypeDecl,
  lines: string[],
): void {
  const coercionCheck = swiftCoercionCheck(coercion.scalarType);
  if (!coercionCheck) return;
  const check = coercionCheck.replace(/\bdata\b/g, "normalizedData");

  lines.push(`    if let scalar = ${check} {`);
  const entries = coercion.assignments.map(assignment => {
    const value = assignment.isInput
      ? "scalar"
      : swiftWireLiteral(
        type.fields.find(field => field.name === assignment.fieldName),
        assignment.literalValue ?? "",
      );
    return `${swiftStringLiteral(assignment.fieldName)}: ${value}`;
  });
  lines.push(`      normalizedData = [${entries.join(", ")}]`);
  lines.push("    }");
}

function swiftWireLiteral(field: FieldDecl | undefined, value: string): string {
  if (field?.category.kind === "scalar") {
    switch (field.category.scalarType) {
      case "boolean":
        return value === "true" ? "true" : "false";
      case "int32":
      case "int64":
      case "integer":
      case "float32":
      case "float64":
      case "float":
      case "number":
      case "numeric":
        return value;
    }
  }
  return swiftStringLiteral(value);
}

function emitStruct(
  type: TypeDecl,
  lines: string[],
  visitor: ExprVisitor,
  polymorphicTypeNames: Set<string>,
  polymorphicDefaultCases: ReadonlyMap<string, SwiftPolymorphicDefaultCase | null>,
  nativeSerialization: SwiftNativeSerialization,
): void {
  const typeName = swiftTypeName(type.typeName.name);
  if (type.description) {
    lines.push(`/// ${type.description.replace(/\r?\n/g, " ")}`);
  }
  const conformances = ["TypraModel"];
  if (type.isError) conformances.push("Swift.Error");
  if (nativeSerialization === "codable") conformances.push("Codable");
  lines.push(`public struct ${typeName}: ${conformances.join(", ")} {`);
  lines.push(`  public static let shorthandProperty: String? = ${type.coercionProperty ? swiftStringLiteral(type.coercionProperty) : "nil"}`);
  for (const field of type.fields) {
    const defaultValue = swiftFieldDefaultValue(field, polymorphicTypeNames, polymorphicDefaultCases);
    lines.push(`  public var ${swiftPropertyName(field.name)}: ${swiftFieldType(field, polymorphicTypeNames)} = ${defaultValue}`);
  }
  lines.push("");
  lines.push(`  public init(${type.fields.map(field => {
    const defaultValue = swiftFieldDefaultValue(field, polymorphicTypeNames, polymorphicDefaultCases);
    return `${swiftPropertyName(field.name)}: ${swiftFieldType(field, polymorphicTypeNames)} = ${defaultValue}`;
  }).join(", ")}) {`);
  for (const field of type.fields) {
    lines.push(`    self.${swiftPropertyName(field.name)} = ${swiftPropertyName(field.name)}`);
  }
  lines.push("  }");
  lines.push("");
  emitLoad(type, lines, polymorphicTypeNames);
  for (const helper of type.collectionHelpers) {
    if (supportsNamedCollectionHelper(helper, polymorphicTypeNames)) {
      lines.push("");
      emitNamedCollectionLoadHelper(helper, lines, polymorphicTypeNames);
      lines.push("");
      emitNamedCollectionSaveHelper(helper, lines, polymorphicTypeNames);
    }
  }
  lines.push("");
  emitSave(type, lines, polymorphicTypeNames);
  if (nativeSerialization === "codable") {
    emitCodableDelegation(typeName, lines);
  }
  if (type.wire) {
    lines.push("");
    emitToWire(type, lines, polymorphicTypeNames);
  }
  emitJsonYamlMethods(typeName, lines);
  for (const factory of type.factories) {
    lines.push("");
    const params = Object.entries(factory.params).map(([name, paramType]) => `${swiftPropertyName(name)}: ${swiftType(paramType)}`).join(", ");
    lines.push(`  public static func ${swiftFunctionName(factory.name)}(${params}) -> ${typeName} {`);
    lines.push(`    return ${visitor.visitExpr(factory.body)}`);
    lines.push("  }");
  }
  for (const method of type.methods) {
    emitMethodStub(method, lines);
  }
  lines.push("}");
  lines.push("");
}

function emitCodableDelegation(typeName: string, lines: string[]): void {
  lines.push("");
  lines.push("  public init(from decoder: Decoder) throws {");
  lines.push("    self = try Self.load(try TypraCodableValue(from: decoder).anyValue)");
  lines.push("  }");
  lines.push("");
  lines.push("  public func encode(to encoder: Encoder) throws {");
  lines.push("    try TypraCodableValue(try save()).encode(to: encoder)");
  lines.push("  }");
}

function emitLoad(type: TypeDecl, lines: string[], polymorphicTypeNames: Set<string>): void {
  const typeName = swiftTypeName(type.typeName.name);
  lines.push(`  public static func load(_ data: Any, context: LoadContext = LoadContext()) throws -> ${typeName} {`);
  for (const coercion of type.load.coercions) {
    emitCoercion(type, coercion, lines, polymorphicTypeNames);
  }
  lines.push(`    let object = try TypraRuntime.object(data, typeName: ${swiftStringLiteral(typeName)})`);
  lines.push(`    var instance = ${typeName}()`);
  for (const assignment of type.load.assignments) {
    const field = type.fields.find(f => f.name === assignment.fieldName);
    const collectionHelper = type.collectionHelpers.find(helper =>
      helper.propertyName === assignment.fieldName && supportsNamedCollectionHelper(helper, polymorphicTypeNames)
    );
    if (shouldGuardMissingRequiredField(field, { includeInheritedScalarAndDict: true, hasBase: type.base !== null })) {
      lines.push(`    if object[${swiftStringLiteral(assignment.sourceName)}] == nil || object[${swiftStringLiteral(assignment.sourceName)}] is NSNull {`);
      lines.push(`      throw TypraRuntimeError.unsupported(context.at(${swiftStringLiteral(assignment.sourceName)}).path + ": missing required field")`);
      lines.push("    }");
    }
    lines.push(`    if let value = object[${swiftStringLiteral(assignment.sourceName)}] {`);
    lines.push(`      instance.${swiftPropertyName(assignment.fieldName)} = ${swiftLoadExpression(assignment.category, assignment.enumName, assignment.fieldName, "value", polymorphicTypeNames, collectionHelper)}`);
    lines.push("    }");
    if (field?.defaultValue !== null && field?.defaultValue !== undefined && !field.isOptional) {
      lines.push("    else {");
      lines.push(`      instance.${swiftPropertyName(field.name)} = ${swiftLiteralDefault(field)}`);
      lines.push("    }");
    }
  }
  lines.push("    return instance");
  lines.push("  }");
}

function emitNamedCollectionLoadHelper(
  helper: CollectionHelperDecl,
  lines: string[],
  _polymorphicTypeNames: Set<string>,
): void {
  const methodName = `load${swiftTypeName(helper.propertyName)}`;
  const elementType = swiftTypeName(helper.elementTypeName.name);
  lines.push(`  private static func ${methodName}(_ data: Any, context: LoadContext) throws -> [${elementType}] {`);
  lines.push("    if let values = data as? [Any] {");
  lines.push(
    `      return try values.enumerated().map { try ${elementType}.load($1, context: context.atIndex($0)) }`,
  );
  lines.push("    }");
  lines.push(`    let values = try TypraRuntime.dictionary(data, field: ${swiftStringLiteral(helper.propertyName)})`);
  lines.push("    return try values.keys.sorted().map { name in");
  lines.push("      let value = values[name]!");
  lines.push("      if value is [Any] {");
  lines.push(`        throw TypraRuntimeError.invalidField(field: context.at(name).path, expected: "non-array named collection entry; received category array")`);
  lines.push("      }");
  lines.push("      var itemData: [String: Any]");
  lines.push("      if let object = value as? [String: Any] {");
  lines.push("        itemData = object");
  lines.push("      } else {");
  lines.push(`        itemData = try ${elementType}.load(value, context: context).save()`);
  lines.push("      }");
  lines.push('      itemData["name"] = name');
  lines.push(`      return try ${elementType}.load(itemData, context: context.at(name))`);
  lines.push("    }");
  lines.push("  }");
}

function emitNamedCollectionSaveHelper(
  helper: CollectionHelperDecl,
  lines: string[],
  polymorphicTypeNames: Set<string>,
): void {
  const methodName = `save${swiftTypeName(helper.propertyName)}`;
  const elementType = swiftTypeName(helper.elementTypeName.name);
  lines.push(`  private static func ${methodName}(_ items: [${elementType}], context: SaveContext) throws -> Any {`);
  lines.push("    var serialized = try items.map { try $0.save(context) }");
  lines.push('    if context.collectionFormat == "array" {');
  lines.push("      return serialized");
  lines.push("    }");
  lines.push("    var names = Set<String>()");
  lines.push("    for itemData in serialized {");
  lines.push('      guard let name = itemData["name"] as? String, !name.isEmpty, names.insert(name).inserted else {');
  lines.push("        return serialized");
  lines.push("      }");
  lines.push("    }");
  lines.push("    var result: [String: Any] = [:]");
  lines.push("    for (item, originalData) in zip(items, serialized) {");
  lines.push("      var itemData = originalData");
  lines.push('      let name = itemData.removeValue(forKey: "name") as! String');
  if (!polymorphicTypeNames.has(helper.elementTypeName.name)) {
    const shorthandProperty = helper.innerFields.length === 1 ? helper.innerFields[0] : undefined;
    if (shorthandProperty) {
      lines.push(`      if context.useShorthand, itemData.count == 1, let value = itemData[${swiftStringLiteral(shorthandProperty)}] {`);
      lines.push("        result[name] = value");
      lines.push("      } else {");
      lines.push("        result[name] = itemData");
      lines.push("      }");
    } else {
      lines.push("      result[name] = itemData");
    }
  } else {
    lines.push("      result[name] = itemData");
  }
  lines.push("    }");
  lines.push("    return result");
  lines.push("  }");
}

function typeKey(type: TypeDecl): string {
  return `${type.typeName.namespace}.${type.typeName.name}`;
}

function supportsNamedCollectionHelper(
  helper: CollectionHelperDecl,
  _polymorphicTypeNames: Set<string>,
): boolean {
  return helper.hasNameProperty;
}

function addNamedCollectionFields(types: TypeDecl[]): TypeDecl[] {
  const polymorphicTypeNames = new Set(
    types.filter(type => type.polymorphicDispatch !== null).map(type => type.typeName.name),
  );
  const namedElementKeys = new Set(
    types.flatMap(type => type.collectionHelpers)
      .filter(helper => supportsNamedCollectionHelper(helper, polymorphicTypeNames))
      .map(helper => `${helper.elementTypeName.namespace}.${helper.elementTypeName.name}`),
  );
  const stringCategory = { kind: "scalar" as const, scalarType: "string" };

  return types.map(type => {
    if (!namedElementKeys.has(typeKey(type)) || type.fields.some(field => field.name === "name")) {
      return type;
    }
    const nameField: FieldDecl = {
      name: "name",
      typeName: { namespace: "", name: "string" },
      category: stringCategory,
      isOptional: true,
      defaultValue: null,
      allowedValues: [],
      parseAliases: {},
      enumName: null,
      isOpenEnum: false,
      description: "Name supplied by an explicit named collection.",
      knownAs: {},
    };
    return {
      ...type,
      fields: [nameField, ...type.fields],
      load: {
        ...type.load,
        assignments: [{
          sourceName: "name",
          fieldName: "name",
          category: stringCategory,
          isOptional: true,
          parentTypeName: type.typeName.name,
          enumName: null,
          allowedValues: [],
          parseAliases: {},
          defaultValue: null,
          isOpenEnum: false,
        }, ...type.load.assignments],
      },
      save: {
        ...type.save,
        assignments: [{
          targetName: "name",
          fieldName: "name",
          category: stringCategory,
          isOptional: true,
          parentTypeName: type.typeName.name,
          enumName: null,
          isOpenEnum: false,
        }, ...type.save.assignments],
      },
    };
  });
}

function emitCoercion(type: TypeDecl, coercion: CoercionDecl, lines: string[], polymorphicTypeNames: Set<string>): void {
  const check = swiftCoercionCheck(coercion.scalarType);
  if (!check) return;
  lines.push(`    if let scalar = ${check} {`);
  lines.push(`      var instance = ${swiftTypeName(type.typeName.name)}()`);
  for (const assignment of coercion.assignments) {
    const field = type.fields.find(f => f.name === assignment.fieldName);
    const fieldName = assignment.fieldName;
    const expr = assignment.isInput
      ? swiftLoadExpression(field?.category ?? { kind: "scalar", scalarType: coercion.scalarType }, field?.enumName ?? null, fieldName, "scalar", polymorphicTypeNames)
      : swiftLiteralForField(field, assignment.literalValue ?? "");
    lines.push(`      instance.${swiftPropertyName(fieldName)} = ${expr}`);
  }
  lines.push("      return instance");
  lines.push("    }");
}

function emitSave(type: TypeDecl, lines: string[], polymorphicTypeNames: Set<string>): void {
  lines.push("  public func save(_ context: SaveContext = SaveContext()) throws -> [String: Any] {");
  lines.push("    var result: [String: Any] = [:]");
  for (const assignment of type.save.assignments) {
    const prop = `self.${swiftPropertyName(assignment.fieldName)}`;
    const collectionHelper = type.collectionHelpers.find(helper =>
      helper.propertyName === assignment.fieldName && supportsNamedCollectionHelper(helper, polymorphicTypeNames)
    );
    const serialized = swiftSaveExpression(
      assignment.category,
      assignment.enumName,
      prop,
      polymorphicTypeNames,
      collectionHelper,
    );
    if (shouldOmitAbsentOnSave(assignment)) {
      lines.push(`    if let value = ${prop} {`);
      lines.push(`      result[${swiftStringLiteral(assignment.targetName)}] = ${swiftSaveExpression(assignment.category, assignment.enumName, "value", polymorphicTypeNames, collectionHelper)}`);
      lines.push("    }");
    } else {
      lines.push(`    result[${swiftStringLiteral(assignment.targetName)}] = ${serialized}`);
    }
  }
  lines.push("    return result");
  lines.push("  }");
}

function emitToWire(type: TypeDecl, lines: string[], polymorphicTypeNames: Set<string>): void {
  lines.push("  public func toWire(_ provider: String, context: SaveContext = SaveContext()) throws -> [String: Any] {");
  lines.push("    var result: [String: Any] = [:]");
  for (const mapping of type.wire!.mappings) {
    const collectionHelper = type.collectionHelpers.find(helper =>
      helper.propertyName === mapping.fieldName && supportsNamedCollectionHelper(helper, polymorphicTypeNames)
    );
    emitWireField(mapping, lines, polymorphicTypeNames, collectionHelper);
  }
  lines.push("    return result");
  lines.push("  }");
}

/**
 * A wire field is emitted only when the requested provider actually maps it. Falling back to the
 * schema name for an unmapped provider leaks fields into payloads that never declared them — the
 * fixture contract maps `temperature` for openai only, so an anthropic payload must not carry it.
 * This mirrors the rule every other backend applies (Go: `if wireName, ok := mapping[provider]`).
 */
function emitWireField(
  mapping: WireFieldMapping,
  lines: string[],
  polymorphicTypeNames: Set<string>,
  collectionHelper?: CollectionHelperDecl,
): void {
  const source = `self.${swiftPropertyName(mapping.fieldName)}`;
  const target = `wireName${swiftTypeName(mapping.fieldName)}`;
  lines.push(`    let ${target}: String?`);
  lines.push("    switch provider {");
  for (const [provider, wireName] of Object.entries(mapping.wireNames)) {
    lines.push(`    case ${swiftStringLiteral(provider)}: ${target} = ${swiftStringLiteral(wireName)}`);
  }
  lines.push(`    default: ${target} = nil`);
  lines.push("    }");
  if (mapping.isOptional) {
    lines.push(`    if let wireKey = ${target}, let value = ${source} { result[wireKey] = ${swiftSaveExpression(mapping.category, null, "value", polymorphicTypeNames, collectionHelper)} }`);
  } else {
    lines.push(`    if let wireKey = ${target} { result[wireKey] = ${swiftSaveExpression(mapping.category, null, source, polymorphicTypeNames, collectionHelper)} }`);
  }
}

function emitJsonYamlMethods(typeName: string, lines: string[]): void {
  lines.push("");
  lines.push(`  public static func fromJSON(_ json: String, context: LoadContext = LoadContext()) throws -> ${typeName} {`);
  lines.push(`    return try load(TypraRuntime.jsonObject(from: json, typeName: ${swiftStringLiteral(typeName)}), context: context)`);
  lines.push("  }");
  lines.push("");
  lines.push("  public func toJSON(_ context: SaveContext = SaveContext()) throws -> String {");
  lines.push("    return try TypraRuntime.jsonString(from: save(context))");
  lines.push("  }");
  lines.push("");
  lines.push(`  public static func fromYAML(_ yaml: String, context: LoadContext = LoadContext()) throws -> ${typeName} {`);
  lines.push(`    return try load(TypraRuntime.yamlObject(from: yaml, typeName: ${swiftStringLiteral(typeName)}), context: context)`);
  lines.push("  }");
  lines.push("");
  lines.push("  public func toYAML(_ context: SaveContext = SaveContext()) throws -> String {");
  lines.push("    return try TypraRuntime.yamlString(from: save(context))");
  lines.push("  }");
}

function emitMethodStub(method: MethodStubDecl, lines: string[]): void {
  const params = Object.entries(method.params).map(([name, typeName]) => `${swiftPropertyName(name)}: ${swiftType(typeName)}`).join(", ");
  const asyncToken = method.sync ? "" : " async";
  const returnType = swiftType(method.returns);
  lines.push("");
  lines.push(`  public func ${swiftFunctionName(method.name)}(${params})${asyncToken} throws${returnType === "Void" ? "" : ` -> ${returnType}`} {`);
  lines.push(`    throw TypraRuntimeError.unsupported(${swiftStringLiteral(`${method.name} must be implemented by hand-authored code.`)})`);
  lines.push("  }");
}

function swiftFieldType(field: FieldDecl, polymorphicTypeNames: Set<string>): string {
  const base = swiftCategoryType(field.category, field.enumName, polymorphicTypeNames);
  return field.isOptional ? `${base}?` : base;
}

function swiftCategoryType(category: PropertyCategory, enumName: string | null, polymorphicTypeNames: Set<string>): string {
  switch (category.kind) {
    case "scalar":
      return enumName ? swiftTypeName(enumName) : swiftType(category.scalarType);
    case "complex":
      return swiftTypeName(category.typeName);
    case "collection_scalar":
      return `[${swiftType(category.scalarType)}]`;
    case "collection_complex":
      return `[${swiftTypeName(category.typeName)}]`;
    case "dict":
      return `[String: ${swiftRecordValueType(category.valueType)}]`;
  }
}

function swiftRecordValueType(valueType: string | undefined): string {
  if (!valueType || valueType === "unknown") return "Any";
  const mapped = swiftType(valueType);
  return mapped === "Any" && valueType !== "any" && valueType !== "unknown" ? swiftTypeName(valueType) : mapped;
}

function swiftFieldDefaultValue(
  field: FieldDecl,
  polymorphicTypeNames: Set<string>,
  polymorphicDefaultCases: ReadonlyMap<string, SwiftPolymorphicDefaultCase | null>,
): string {
  const materializesCollectionDefault =
    field.hasExplicitDefault &&
    (field.category.kind === "collection_scalar" || field.category.kind === "collection_complex");
  return field.isOptional && !materializesCollectionDefault
    ? "nil"
    : swiftDefaultValue(field, polymorphicTypeNames, polymorphicDefaultCases);
}

function swiftDefaultValue(
  field: FieldDecl,
  polymorphicTypeNames: Set<string>,
  polymorphicDefaultCases: ReadonlyMap<string, SwiftPolymorphicDefaultCase | null>,
): string {
  if (
    field.hasExplicitDefault &&
    (field.category.kind === "collection_scalar" || field.category.kind === "collection_complex")
  ) {
    return "[]";
  }
  if (field.defaultValue !== null && field.defaultValue !== undefined) {
    return swiftLiteralDefault(field);
  }
  if (field.enumName) return `(try! ${swiftTypeName(field.enumName)}.parse(${swiftStringLiteral(field.allowedValues[0] ?? "")}))`;
  switch (field.category.kind) {
    case "scalar":
      return scalarDefault(field.category.scalarType);
    case "complex":
      if (polymorphicTypeNames.has(field.category.typeName)) {
        const fallback = polymorphicDefaultCases.get(field.category.typeName);
        return fallback
          ? `.${swiftPropertyName(fallback.typeName)}(${swiftTypeName(fallback.typeName)}()${fallback.carriesRaw ? ", [:]" : ""})`
          : ".unknown([:])";
      }
      return `${swiftTypeName(field.category.typeName)}()`;
    case "collection_scalar":
    case "collection_complex":
      return "[]";
    case "dict":
      return "[:]";
  }
}

function swiftLiteralDefault(field: FieldDecl): string {
  return swiftLiteralForField(field, field.defaultValue);
}

function swiftLiteralForField(field: FieldDecl | undefined, value: string | number | boolean | null): string {
  if (field?.enumName && typeof value === "string") {
    return `(try! ${swiftTypeName(field.enumName)}.parse(${swiftStringLiteral(value)}))`;
  }
  if (typeof value === "string") return swiftStringLiteral(value);
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return "nil";
}

function scalarDefault(typeName: string): string {
  switch (typeName) {
    case "string": return "\"\"";
    case "boolean": return "false";
    case "int32": return "0";
    case "int64": return "0";
    case "integer": return "0";
    case "float32": return "0";
    case "float64":
    case "float":
    case "number":
    case "numeric": return "0";
    case "object":
    case "dictionary": return "[:]";
    case "array": return "[]";
    default: return "NSNull()";
  }
}

function swiftLoadExpression(
  category: PropertyCategory,
  enumName: string | null,
  fieldName: string,
  valueExpr: string,
  polymorphicTypeNames: Set<string>,
  collectionHelper?: CollectionHelperDecl,
): string {
  switch (category.kind) {
    case "scalar":
      if (enumName) return `try ${swiftTypeName(enumName)}.parse(try TypraRuntime.string(${valueExpr}, field: ${swiftStringLiteral(fieldName)}))`;
      return scalarLoadExpression(category.scalarType, valueExpr, fieldName);
    case "complex":
      return `try ${swiftTypeName(category.typeName)}.load(${valueExpr}, context: context.at(${swiftStringLiteral(fieldName)}))`;
    case "collection_scalar":
      return `try TypraRuntime.array(${valueExpr}, field: ${swiftStringLiteral(fieldName)}).map { ${scalarLoadExpression(category.scalarType, "$0", fieldName)} }`;
    case "collection_complex":
      if (collectionHelper?.hasNameProperty) {
        return `try load${swiftTypeName(collectionHelper.propertyName)}(${valueExpr}, context: context.at(${swiftStringLiteral(fieldName)}))`;
      }
      return `try TypraRuntime.array(${valueExpr}, field: ${swiftStringLiteral(fieldName)}).enumerated().map { try ${swiftTypeName(category.typeName)}.load($1, context: context.at(${swiftStringLiteral(fieldName)}).atIndex($0)) }`;
    case "dict":
      if (!category.valueType || category.valueType === "unknown") {
        return `try TypraRuntime.dictionary(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
      }
      return `Dictionary(uniqueKeysWithValues: try TypraRuntime.dictionary(${valueExpr}, field: ${swiftStringLiteral(fieldName)}).map { (key, item) in (key, ${swiftRecordValueLoadExpression(category.valueType, "item", fieldName)}) })`;
  }
}

function swiftRecordValueLoadExpression(valueType: string, valueExpr: string, fieldName: string): string {
  if (isSwiftScalarRecordValue(valueType)) {
    return scalarLoadExpression(valueType, valueExpr, fieldName);
  }
  return `try ${swiftTypeName(valueType)}.load(${valueExpr}, context: context.at(${swiftStringLiteral(fieldName)}).at(key))`;
}

function isSwiftScalarRecordValue(valueType: string): boolean {
  return valueType.toLowerCase() in SWIFT_TYPE_MAP;
}

function scalarLoadExpression(scalarType: string, valueExpr: string, fieldName: string): string {
  switch (scalarType) {
    case "string": return `try TypraRuntime.string(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "boolean": return `try TypraRuntime.bool(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "int32": return `try TypraRuntime.int32(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "int64": return `try TypraRuntime.int64(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "integer": return `try TypraRuntime.int(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "float32": return `try TypraRuntime.float(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "float64":
    case "float":
    case "number":
    case "numeric": return `try TypraRuntime.double(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "object":
    case "dictionary": return `try TypraRuntime.dictionary(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    case "array": return `try TypraRuntime.array(${valueExpr}, field: ${swiftStringLiteral(fieldName)})`;
    default: return valueExpr;
  }
}

function swiftSaveExpression(
  category: PropertyCategory,
  enumName: string | null,
  valueExpr: string,
  polymorphicTypeNames: Set<string>,
  collectionHelper?: CollectionHelperDecl,
): string {
  switch (category.kind) {
    case "scalar":
      return enumName ? `${valueExpr}.rawValue` : valueExpr;
    case "complex":
      return `try ${valueExpr}.save(context)`;
    case "collection_scalar":
      return valueExpr;
    case "collection_complex":
      if (collectionHelper?.hasNameProperty) {
        return `try Self.save${swiftTypeName(collectionHelper.propertyName)}(${valueExpr}, context: context)`;
      }
      return `try ${valueExpr}.map { try $0.save(context) }`;
    case "dict":
      if (category.valueType && category.valueType !== "unknown" && !isSwiftScalarRecordValue(category.valueType)) {
        return `Dictionary(uniqueKeysWithValues: try ${valueExpr}.map { (key, item) in (key, try item.save(context)) })`;
      }
      return valueExpr;
  }
}

function swiftCoercionCheck(scalarType: string): string | undefined {
  switch (scalarType) {
    case "string": return "data as? String";
    case "boolean": return "data as? Bool";
    case "int32":
    case "int64":
    case "integer": return "data as? Int";
    case "float32":
    case "float64":
    case "float":
    case "number":
    case "numeric": return "data as? Double";
    default: return undefined;
  }
}

function trimBlankLines(lines: string[]): string[] {
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  return lines;
}
