import { BaseTestContext, PropertyNode, PropertyValidation, TestExample, TypeNode } from "../../ir/ast.js";
import { swiftPropertyName, swiftStringLiteral, swiftTypeName } from "./identifiers.js";

type SwiftNativeSerialization = "none" | "codable";

export function emitSwiftTests(ctx: BaseTestContext & { moduleName: string; nativeSerialization?: SwiftNativeSerialization }): string {
  const typeName = swiftTypeName(ctx.node.typeName.name);
  const lines = [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    "",
    "import Foundation",
    "import XCTest",
    `@testable import ${ctx.moduleName}`,
    "",
    `final class ${typeName}Tests: XCTestCase {`,
  ];

  ctx.examples.forEach((example, index) => {
    emitExampleTest(lines, ctx.node, typeName, example, index, ctx.nativeSerialization ?? "none");
  });

  ctx.coercions.forEach((coercion, index) => {
    lines.push(`  func testScalarCoercion${index + 1}() throws {`);
    lines.push(`    let instance = try ${typeName}.load(${coercion.value})`);
    const expansion = ctx.node.coercions[index]?.expansion;
    const child = expansion && ctx.node.discriminator
      ? matchingPolymorphicChild(ctx.node, expansion)
      : undefined;
    if (child) {
      const rawPattern = isWildcardFallbackChild(ctx.node, child) ? ", _" : "";
      lines.push(`    if case .${swiftPropertyName(child.typeName.name)}(let concrete${rawPattern}) = instance {`);
      for (const validation of coercion.validations) {
        if (validation.key === ctx.node.discriminator) continue;
        const expected = validationExpected(validation);
        const prop = findProperty(child, validation.key) ?? findProperty(ctx.node, validation.key);
        emitPropertyAssertion(
          lines,
          `concrete.${swiftPropertyName(validation.key)}`,
          expected,
          prop,
          "      ",
          validationCast(validation),
        );
      }
      lines.push("    } else {");
      lines.push(`      XCTFail("Expected ${swiftTypeName(child.typeName.name)}")`);
      lines.push("    }");
    } else if (isUnknownPolymorphicRoot(ctx.node)) {
      emitUnknownCoercionValidation(
        lines,
        coercion.validations,
        expansion,
        ctx.node.coercions[index]?.scalar,
      );
    } else {
      for (const validation of coercion.validations) {
        const expected = validationExpected(validation);
        const prop = findProperty(ctx.node, validation.key);
        emitPropertyAssertion(
          lines,
          `instance.${swiftPropertyName(validation.key)}`,
          expected,
          prop,
          "    ",
        );
      }
    }
    lines.push("  }");
    lines.push("");
  });

  if ((ctx.nativeSerialization ?? "none") === "codable") {
    emitCodableAssertions(lines);
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export function emitSwiftConformanceTest(moduleName: string): string {
  return [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    "",
    "import XCTest",
    `@testable import ${moduleName}`,
    "",
    "final class ConformanceTests: XCTestCase {",
    "  func testIntegerValidationRejectsUnsafeValues() throws {",
    "    XCTAssertEqual(try TypraRuntime.int64(NSNumber(value: Int64.max), field: \"value\"), Int64.max)",
    "    XCTAssertThrowsError(try TypraRuntime.int64(NSDecimalNumber(mantissa: 9223372036854775808, exponent: 0, isNegative: false), field: \"value\"))",
    "    XCTAssertThrowsError(try TypraRuntime.int64(NSDecimalNumber(mantissa: 9223372036854775809, exponent: 0, isNegative: true), field: \"value\"))",
    "    XCTAssertThrowsError(try TypraRuntime.int64(1.5, field: \"value\"))",
    "    XCTAssertThrowsError(try TypraRuntime.int32(2147483648, field: \"value\"))",
    "  }",
    "",
    "  func testJsonBooleansAreNotNumericValues() throws {",
    "    let parsed = try TypraRuntime.jsonObject(from: \"{\\\"intZero\\\":0,\\\"intOne\\\":1,\\\"boolTrue\\\":true,\\\"boolFalse\\\":false}\", typeName: \"NumericProbe\") as! [String: Any]",
    "    XCTAssertEqual(try TypraRuntime.int64(parsed[\"intZero\"]!, field: \"intZero\"), 0)",
    "    XCTAssertEqual(try TypraRuntime.int64(parsed[\"intOne\"]!, field: \"intOne\"), 1)",
    "    XCTAssertEqual(try TypraRuntime.double(parsed[\"intZero\"]!, field: \"intZero\"), 0)",
    "    XCTAssertEqual(try TypraRuntime.double(parsed[\"intOne\"]!, field: \"intOne\"), 1)",
    "    XCTAssertThrowsError(try TypraRuntime.int64(parsed[\"boolTrue\"]!, field: \"boolTrue\"))",
    "    XCTAssertThrowsError(try TypraRuntime.int64(parsed[\"boolFalse\"]!, field: \"boolFalse\"))",
    "    XCTAssertThrowsError(try TypraRuntime.double(parsed[\"boolTrue\"]!, field: \"boolTrue\"))",
    "    XCTAssertThrowsError(try TypraRuntime.double(parsed[\"boolFalse\"]!, field: \"boolFalse\"))",
    "  }",
    "}",
    "",
  ].join("\n");
}

function emitExampleTest(
  lines: string[],
  node: TypeNode,
  typeName: string,
  example: TestExample,
  index: number,
  nativeSerialization: SwiftNativeSerialization,
): void {
  lines.push(`  func testJSONRoundTrip${index + 1}() throws {`);
  lines.push(`    let json = ${swiftMultilineString(example.json.join("\n"))}`);
  lines.push(`    let instance = try ${typeName}.fromJSON(json)`);
  emitValidations(lines, "instance", example, node);
  lines.push("    let reloaded = try " + typeName + ".fromJSON(try instance.toJSON())");
  const jsonReloadValidationStart = lines.length;
  emitValidations(lines, "reloaded", example, node);
  if (lines.length === jsonReloadValidationStart) {
    lines.push("    _ = reloaded");
  }
  if (nativeSerialization === "codable") {
    lines.push(`    try assertCodableMatches(${typeName}.self, sourceJson: json, message: "example ${index + 1}")`);
  }
  lines.push("  }");
  lines.push("");
  lines.push(`  func testYAMLRoundTrip${index + 1}() throws {`);
  lines.push(`    let yaml = ${swiftMultilineString(example.yaml.join("\n"))}`);
  lines.push(`    let instance = try ${typeName}.fromYAML(yaml)`);
  emitValidations(lines, "instance", example, node);
  lines.push("    let reloaded = try " + typeName + ".fromYAML(try instance.toYAML())");
  const yamlReloadValidationStart = lines.length;
  emitValidations(lines, "reloaded", example, node);
  if (lines.length === yamlReloadValidationStart) {
    lines.push("    _ = reloaded");
  }
  lines.push("  }");
  lines.push("");
}

function emitCodableAssertions(lines: string[]): void {
  lines.push("  private func assertCodableMatches<T: TypraModel & Codable>(_ type: T.Type, sourceJson: String, message: String) throws {");
  lines.push("    let sourceData = Data(sourceJson.utf8)");
  lines.push("    let typraLoaded = try T.load(try TypraRuntime.jsonObject(from: sourceJson, typeName: String(describing: T.self)), context: LoadContext())");
  lines.push("    let codableLoaded = try JSONDecoder().decode(T.self, from: sourceData)");
  lines.push("    let encoder = JSONEncoder()");
  lines.push("    encoder.outputFormatting = [.sortedKeys]");
  lines.push("    let codableObject = try JSONSerialization.jsonObject(with: encoder.encode(codableLoaded), options: [])");
  lines.push("    XCTAssertEqual(try TypraRuntime.jsonString(from: codableObject), try TypraRuntime.jsonString(from: try typraLoaded.save(SaveContext())), message + \" Codable encode\")");
  lines.push("    XCTAssertEqual(try TypraRuntime.jsonString(from: try codableLoaded.save(SaveContext())), try TypraRuntime.jsonString(from: try typraLoaded.save(SaveContext())), message + \" Codable decode\")");
  lines.push("  }");
  lines.push("");
}

function emitValidations(lines: string[], varName: string, example: TestExample, node: TypeNode): void {
  if (emitPolymorphicValidation(lines, varName, example.sample, node)) {
    return;
  }
  for (const validation of example.validations) {
    const expected = validation.delimiter ? `${validation.delimiter}${validation.value}${validation.delimiter}` : String(validation.value);
    const prop = findProperty(node, validation.key);
    if (!prop) continue;
    const accessor = `${varName}.${swiftPropertyName(prop.name)}`;
    emitPropertyAssertion(lines, accessor, expected, prop, "    ");
  }
  emitStructuredValidations(lines, varName, example.sample, node);
}

function emitStructuredValidations(lines: string[], varName: string, sample: Record<string, any>, node: TypeNode): void {
  for (const prop of node.properties) {
    if (!(prop.name in sample)) continue;
    const value = sample[prop.name];
    const accessor = `${varName}.${swiftPropertyName(prop.name)}`;
    if (prop.isCollection) {
      const count = Array.isArray(value)
        ? value.length
        : value && typeof value === "object"
          ? Object.keys(value).length
          : undefined;
      if (count !== undefined) {
        lines.push(`    XCTAssertEqual(${requiredAccessor(accessor, prop.isOptional)}.count, ${count})`);
      }
      continue;
    }
    if (prop.isDict && value && typeof value === "object" && !Array.isArray(value)) {
      lines.push(`    XCTAssertNotNil(${accessor})`);
      continue;
    }
    if (!prop.isScalar && prop.type && value && typeof value === "object" && !Array.isArray(value)) {
      emitNestedValidation(lines, requiredAccessor(accessor, prop.isOptional), value, prop);
    }
  }
}

function emitNestedValidation(lines: string[], accessor: string, value: Record<string, any>, prop: PropertyNode): void {
  if ((prop.type?.childTypes.length ?? 0) > 0) {
    const child = matchingPolymorphicChild(prop.type!, value);
    if (child) {
      emitChildPatternValidation(lines, accessor, value, prop.type!, child, "    ");
      return;
    }
    emitUnknownPatternValidation(lines, accessor, value, prop.type!, "    ");
    return;
  }
  for (const [key, expected] of Object.entries(value)) {
    const nestedProp = prop.type ? findProperty(prop.type, key) : undefined;
    if (!nestedProp) continue;
    const literal = swiftExpectedLiteral(expected);
    if (literal !== null) {
      emitPropertyAssertion(
        lines,
        `${accessor}.${swiftPropertyName(nestedProp.name)}`,
        literal,
        nestedProp,
        "    ",
      );
    }
  }
}

function emitPolymorphicValidation(
  lines: string[],
  accessor: string,
  sample: Record<string, any>,
  node: TypeNode,
): boolean {
  if (!node.discriminator || node.childTypes.length === 0) {
    return false;
  }
  const child = matchingPolymorphicChild(node, sample);
  if (child) {
    emitChildPatternValidation(lines, accessor, sample, node, child, "    ");
    return true;
  }
  emitUnknownPatternValidation(lines, accessor, sample, node, "    ");
  return true;
}

/**
 * Assert against the `.unknown` arm of a polymorphic enum.
 *
 * A discriminated base is emitted as an enum, never a struct, so a sample whose discriminator no
 * subtype claims has no members to reach through — it lands in `.unknown([String: Any])` and must
 * be matched as such. Abstractness does not enter into it: the model emitter gates the `.unknown`
 * case on the absence of a wildcard subtype, not on whether the base is abstract.
 *
 * Callers must have already established that no subtype claims the discriminator; a wildcard
 * subtype always claims it, so reaching here means the enum carries an `.unknown` case. The one
 * shape this does not cover is a closed-rejecting dispatch, which omits `.unknown` entirely — a
 * sample like that cannot load in the first place, and TypeNode does not carry the closedness flag
 * the model emitter uses, so it is left to fail loudly rather than be guessed at here.
 */
function emitUnknownPatternValidation(
  lines: string[],
  accessor: string,
  sample: Record<string, any>,
  node: TypeNode,
  indent: string,
): void {
  lines.push(`${indent}if case .unknown(let concrete) = ${accessor} {`);
  for (const [key, expected] of Object.entries(sample)) {
    const literal = swiftExpectedLiteral(expected);
    if (literal === null) continue;
    const cast = swiftDictionaryCast(expected);
    lines.push(`${indent}  XCTAssertEqual(concrete[${swiftStringLiteral(key)}] as? ${cast}, ${literal})`);
  }
  lines.push(`${indent}} else {`);
  lines.push(`${indent}  XCTFail("Expected ${swiftTypeName(node.typeName.name)}.unknown")`);
  lines.push(`${indent}}`);
}

function emitChildPatternValidation(
  lines: string[],
  accessor: string,
  sample: Record<string, any>,
  node: TypeNode,
  child: TypeNode,
  indent: string,
): void {
  const rawPattern = isWildcardFallbackChild(node, child) ? ", _" : "";
  lines.push(`${indent}if case .${swiftPropertyName(child.typeName.name)}(let concrete${rawPattern}) = ${accessor} {`);
  for (const [key, expected] of Object.entries(sample)) {
    if (key === node.discriminator) continue;
    const literal = swiftExpectedLiteral(expected);
    if (literal === null) continue;
    const prop = findProperty(child, key) ?? findProperty(node, key);
    if (!prop) continue;
    emitPropertyAssertion(
      lines,
      `concrete.${swiftPropertyName(prop.name)}`,
      literal,
      prop,
      `${indent}  `,
    );
  }
  lines.push(`${indent}} else {`);
  lines.push(`${indent}  XCTFail("Expected ${swiftTypeName(child.typeName.name)}")`);
  lines.push(`${indent}}`);
}

function matchingPolymorphicChild(node: TypeNode, sample: Record<string, any>): TypeNode | undefined {
  const discriminatorValue = node.discriminator ? sample[node.discriminator] : undefined;
  return node.childTypes.find(child => polymorphicChildValue(node, child) === discriminatorValue)
    ?? defaultPolymorphicChild(node);
}

function defaultPolymorphicChild(node: TypeNode): TypeNode | undefined {
  return node.childTypes.find(child => polymorphicChildValue(node, child) === "*");
}

function polymorphicChildValue(node: TypeNode, child: TypeNode): unknown {
  return child.properties.find(prop => prop.name === node.discriminator)?.defaultValue ?? "*";
}

function isWildcardFallbackChild(node: TypeNode, child: TypeNode): boolean {
  return polymorphicChildValue(node, child) === "*";
}

function emitPropertyAssertion(
  lines: string[],
  accessor: string,
  expected: string,
  prop: PropertyNode | undefined,
  indent: string,
  unknownCast = "String",
): void {
  if (prop?.enumName) {
    const valueAccessor = requiredAccessor(accessor, prop.isOptional);
    if (expected.startsWith("\"")) {
      lines.push(`${indent}XCTAssertEqual(${valueAccessor}.rawValue, ${expected})`);
    } else {
      const normalizedExpected = expected.replace(
        /^[A-Za-z_][A-Za-z0-9_]*/,
        swiftTypeName(prop.enumName),
      );
      lines.push(`${indent}XCTAssertEqual(${valueAccessor}, ${normalizedExpected})`);
    }
    return;
  }

  if (prop?.typeName.name === "unknown" || prop?.typeName.name === "any") {
    const castAccessor = `${accessor} as? ${unknownCast}`;
    lines.push(`${
      indent
    }XCTAssertEqual(${prop.isOptional ? `try XCTUnwrap(${castAccessor})` : castAccessor}, ${expected})`);
    return;
  }

  if (prop?.enumName) {
    const enumExpected = expected.startsWith("\"")
      ? `(try! ${swiftTypeName(prop.enumName)}.parse(${expected}))`
      : expected;
    lines.push(
      `${indent}XCTAssertEqual(${requiredAccessor(accessor, prop.isOptional)}, ${enumExpected})`,
    );
    return;
  }

  if (prop && !prop.isScalar && prop.type) {
    const nestedKey = coercionProperty(prop.type) ?? prop.type.discriminator;
    if (nestedKey) {
      const valueAccessor = requiredAccessor(accessor, prop.isOptional);
      if (prop.type.childTypes.length > 0) {
        lines.push(`${indent}XCTAssertEqual(try ${valueAccessor}.save()[${swiftStringLiteral(nestedKey)}] as? String, ${expected})`);
      } else {
        const nestedProp = prop.type.properties.find(candidate => candidate.name === nestedKey);
        const nestedAccessor = `${valueAccessor}.${swiftPropertyName(nestedKey)}`;
        lines.push(`${indent}XCTAssertEqual(${requiredAccessor(nestedAccessor, nestedProp?.isOptional ?? false)}, ${expected})`);
      }

      return;
    }
  }

  lines.push(`${indent}XCTAssertEqual(${requiredAccessor(accessor, prop?.isOptional ?? false)}, ${expected})`);
}

function isUnknownPolymorphicRoot(node: TypeNode): boolean {
  return Boolean(
    node.discriminator
    && node.childTypes.length > 0
    && !node.isAbstract
    && !defaultPolymorphicChild(node),
  );
}

function validationExpected(validation: PropertyValidation): string {
  return validation.delimiter
    ? `${validation.delimiter}${validation.value}${validation.delimiter}`
    : String(validation.value);
}

function coercionProperty(node: TypeNode): string | undefined {
  for (const coercion of node.coercions) {
    const inputAssignment = Object.entries(coercion.expansion)
      .find(([, value]) => value === "{value}");
    if (inputAssignment) return inputAssignment[0];
  }
  return undefined;
}

function requiredAccessor(accessor: string, isOptional: boolean): string {
  return isOptional ? `(try XCTUnwrap(${accessor}))` : accessor;
}

function findProperty(node: TypeNode, key: string): PropertyNode | undefined {
  return node.properties.find(candidate =>
    swiftPropertyName(candidate.name) === swiftPropertyName(key)
    || candidate.knownAs.some(mapping =>
      swiftPropertyName(mapping.name) === swiftPropertyName(key)));
}

function emitUnknownCoercionValidation(
  lines: string[],
  validations: TestExample["validations"],
  expansion: Record<string, unknown> | undefined,
  scalarType: string | undefined,
): void {
  lines.push("    if case .unknown(let concrete) = instance {");
  for (const validation of validations) {
    const expected = validation.delimiter
      ? `${validation.delimiter}${validation.value}${validation.delimiter}`
      : String(validation.value);
    const rawValue = expansion?.[validation.key];
    const cast = expansion
      ? (rawValue === "{value}"
          ? swiftCoercionCast(scalarType)
          : swiftDictionaryCast(rawValue))
      : validationCast(validation);
    lines.push(
      `      XCTAssertEqual(concrete[${swiftStringLiteral(validation.key)}] as? ${cast}, ${expected})`,
    );
  }
  lines.push("    } else {");
  lines.push('      XCTFail("Expected unknown polymorphic fallback")');
  lines.push("    }");
}

function validationCast(validation: PropertyValidation): string {
  if (validation.delimiter) return "String";
  const value = String(validation.value);
  if (value === "true" || value === "false") return "Bool";
  if (/^-?\d+$/.test(value)) return "Int";
  if (/^-?(?:\d+\.\d*|\d*\.\d+)(?:[eE][+-]?\d+)?$/.test(value)) return "Double";
  return "String";
}

function swiftCoercionCast(scalarType: string | undefined): string {
  switch (scalarType) {
    case "boolean":
      return "Bool";
    case "float":
    case "float32":
    case "float64":
    case "number":
      return "Double";
    case "int32":
    case "int64":
    case "integer":
      return "Int";
    default:
      return "String";
  }
}

function swiftExpectedLiteral(value: unknown): string | null {
  if (typeof value === "string") return swiftStringLiteral(value);
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  return null;
}

function swiftDictionaryCast(value: unknown): string {
  if (typeof value === "boolean") return "Bool";
  if (typeof value === "number") return "NSNumber";
  return "String";
}

function swiftMultilineString(value: string): string {
  return `"""\n${value.replace(/"""/g, "\\\"\\\"\\\"")}\n"""`;
}
