import { BaseTestContext, PropertyNode, TestExample, TypeNode } from "../../ir/ast.js";
import { swiftPropertyName, swiftStringLiteral, swiftTypeName } from "./identifiers.js";

export function emitSwiftTests(ctx: BaseTestContext & { moduleName: string }): string {
  const typeName = swiftTypeName(ctx.node.typeName.name);
  const lines = [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    "",
    "import XCTest",
    `@testable import ${ctx.moduleName}`,
    "",
    `final class ${typeName}Tests: XCTestCase {`,
  ];

  ctx.examples.forEach((example, index) => {
    emitExampleTest(lines, ctx.node, typeName, example, index);
  });

  ctx.coercions.forEach((coercion, index) => {
    lines.push(`  func testScalarCoercion${index + 1}() throws {`);
    lines.push(`    let instance = try ${typeName}.load(${coercion.value})`);
    for (const validation of coercion.validations) {
      const expected = validation.delimiter ? `${validation.delimiter}${validation.value}${validation.delimiter}` : String(validation.value);
      lines.push(`    XCTAssertEqual(instance.${swiftPropertyName(validation.key)}, ${expected})`);
    }
    lines.push("  }");
    lines.push("");
  });

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export function emitSwiftConformanceTest(moduleName: string): string {
  return [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    "",
    "import XCTest",
    `@testable import ${moduleName}`,
    "",
    "final class ConformanceTests: XCTestCase {",
    "  func testCanonicalFixtureConformance() throws {",
    "    let root = try FixtureRoot.load([",
    "      \"name\": \"fixture-root\",",
    "      \"description\": \"A generated fixture with broad emitter coverage.\",",
    "      \"tags\": [\"typespec\", \"emitter\", \"validation\"],",
    "      \"metadata\": [\"source\": \"fixture\", \"version\": 1],",
    "      \"owner\": [\"id\": \"owner-1\", \"displayName\": \"Fixture Owner\"],",
    "      \"content\": [\"kind\": \"text\", \"text\": \"hello from a polymorphic sample\"],",
    "      \"contentItems\": [[\"kind\": \"text\", \"text\": \"hello from a polymorphic collection\"]],",
    "      \"status\": \"complete\",",
    "      \"mode\": \"bulk\",",
    "    ])",
    "    let rootSaved = try root.save()",
    "    XCTAssertEqual(rootSaved[\"status\"] as? String, \"ready\")",
    "    XCTAssertEqual(rootSaved[\"mode\"] as? String, \"batch\")",
    "",
    "    let imageContent = try FixtureContent.load([\"kind\": \"image\", \"url\": \"https://example.com/fixture.png\"])",
    "    XCTAssertEqual(try imageContent.save()[\"kind\"] as? String, \"image\")",
    "",
    "    let wire = try WireOptions.load([\"maxOutputTokens\": 256, \"temperature\": 0.7])",
    "    let openai = try wire.toWire(\"openai\")",
    "    XCTAssertEqual(openai[\"max_completion_tokens\"] as? Int32, 256)",
    "    XCTAssertEqual(openai[\"temperature\"] as? Float, 0.7)",
    "    let anthropic = try wire.toWire(\"anthropic\")",
    "    XCTAssertEqual(anthropic[\"max_tokens\"] as? Int32, 256)",
    "",
    "    let reference = try FixtureReference.load(\"ref-coerced\")",
    "    XCTAssertEqual(try reference.save()[\"label\"] as? String, \"coerced reference\")",
    "  }",
    "",
    "  func testIntegerValidationRejectsUnsafeValues() throws {",
    "    XCTAssertEqual(try TypraRuntime.int64(NSNumber(value: Int64.max), field: \"value\"), Int64.max)",
    "    XCTAssertThrowsError(try TypraRuntime.int64(NSDecimalNumber(mantissa: 9223372036854775808, exponent: 0, isNegative: false), field: \"value\"))",
    "    XCTAssertThrowsError(try TypraRuntime.int64(NSDecimalNumber(mantissa: 9223372036854775809, exponent: 0, isNegative: true), field: \"value\"))",
    "    XCTAssertThrowsError(try TypraRuntime.int64(1.5, field: \"value\"))",
    "    XCTAssertThrowsError(try TypraRuntime.int32(2147483648, field: \"value\"))",
    "  }",
    "}",
    "",
  ].join("\n");
}

function emitExampleTest(lines: string[], node: TypeNode, typeName: string, example: TestExample, index: number): void {
  lines.push(`  func testJSONRoundTrip${index + 1}() throws {`);
  lines.push(`    let json = ${swiftMultilineString(example.json.join("\n"))}`);
  lines.push(`    let instance = try ${typeName}.fromJSON(json)`);
  emitValidations(lines, "instance", example, node);
  lines.push("    let reloaded = try " + typeName + ".fromJSON(try instance.toJSON())");
  const jsonReloadValidationStart = lines.length;
  emitValidations(lines, "reloaded", example, node);
  if (lines.length === jsonReloadValidationStart) {
    lines.push("    _ = reloaded");
  }
  lines.push("  }");
  lines.push("");
  lines.push(`  func testYAMLRoundTrip${index + 1}() throws {`);
  lines.push(`    let yaml = ${swiftMultilineString(example.yaml.join("\n"))}`);
  lines.push(`    let instance = try ${typeName}.fromYAML(yaml)`);
  emitValidations(lines, "instance", example, node);
  lines.push("    let reloaded = try " + typeName + ".fromYAML(try instance.toYAML())");
  const yamlReloadValidationStart = lines.length;
  emitValidations(lines, "reloaded", example, node);
  if (lines.length === yamlReloadValidationStart) {
    lines.push("    _ = reloaded");
  }
  lines.push("  }");
  lines.push("");
}

function emitValidations(lines: string[], varName: string, example: TestExample, node: TypeNode): void {
  for (const validation of example.validations) {
    const expected = validation.delimiter ? `${validation.delimiter}${validation.value}${validation.delimiter}` : String(validation.value);
    const accessor = `${varName}.${swiftPropertyName(validation.key)}`;
    const prop = node.properties.find(candidate => swiftPropertyName(candidate.name) === swiftPropertyName(validation.key));
    if (prop?.typeName.name === "unknown" || prop?.typeName.name === "any") {
      lines.push(`    XCTAssertEqual(${accessor} as? String, ${expected})`);
    } else {
      lines.push(`    XCTAssertEqual(${accessor}, ${expected})`);
    }
  }
  emitStructuredValidations(lines, varName, example.sample, node);
}

function emitStructuredValidations(lines: string[], varName: string, sample: Record<string, any>, node: TypeNode): void {
  for (const prop of node.properties) {
    if (!(prop.name in sample)) continue;
    const value = sample[prop.name];
    const accessor = `${varName}.${swiftPropertyName(prop.name)}`;
    if (prop.isCollection && Array.isArray(value)) {
      lines.push(`    XCTAssertEqual(${accessor}.count, ${value.length})`);
      continue;
    }
    if (prop.isDict && value && typeof value === "object" && !Array.isArray(value)) {
      lines.push(`    XCTAssertNotNil(${accessor})`);
      continue;
    }
    if (!prop.isScalar && prop.type && value && typeof value === "object" && !Array.isArray(value)) {
      emitNestedValidation(lines, accessor, value, prop);
    }
  }
}

function emitNestedValidation(lines: string[], accessor: string, value: Record<string, any>, prop: PropertyNode): void {
  if ((prop.type?.childTypes.length ?? 0) > 0) {
    for (const child of prop.type?.childTypes ?? []) {
      const discriminator = prop.type?.discriminator;
      const discriminatorValue = discriminator ? value[discriminator] : undefined;
      const matchingDefault = child.properties.find(childProp => childProp.name === discriminator)?.defaultValue;
      if (matchingDefault === discriminatorValue) {
        lines.push(`    if case .${swiftPropertyName(child.typeName.name)}(let concrete) = ${accessor} {`);
        for (const [key, expected] of Object.entries(value)) {
          if (typeof expected === "string" && key !== discriminator) {
            lines.push(`      XCTAssertEqual(concrete.${swiftPropertyName(key)}, ${swiftStringLiteral(expected)})`);
          }
        }
        lines.push("    } else {");
        lines.push(`      XCTFail("Expected ${swiftTypeName(child.typeName.name)}")`);
        lines.push("    }");
        return;
      }
    }
  }
  for (const [key, expected] of Object.entries(value)) {
    if (typeof expected === "string") {
      lines.push(`    XCTAssertEqual(${accessor}.${swiftPropertyName(key)}, ${swiftStringLiteral(expected)})`);
    }
  }
}

function swiftMultilineString(value: string): string {
  return `"""\n${value.replace(/"""/g, "\\\"\\\"\\\"")}\n"""`;
}
