import { BaseTestContext, PropertyNode, TestExample, TypeNode } from "../../ir/ast.js";
import { swiftPropertyName, swiftStringLiteral, swiftTypeName } from "./identifiers.js";

export function emitSwiftTests(ctx: BaseTestContext & { moduleName: string }): string {
  const typeName = swiftTypeName(ctx.node.typeName.name);
  const lines = [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    "",
    "import XCTest",
    `@testable import ${ctx.moduleName}`,
    "",
    `final class ${typeName}Tests: XCTestCase {`,
  ];

  ctx.examples.forEach((example, index) => {
    emitExampleTest(lines, ctx.node, typeName, example, index);
  });

  ctx.coercions.forEach((coercion, index) => {
    lines.push(`  func testScalarCoercion${index + 1}() throws {`);
    lines.push(`    let instance = try ${typeName}.load(${coercion.value})`);
    for (const validation of coercion.validations) {
      const expected = validation.delimiter ? `${validation.delimiter}${validation.value}${validation.delimiter}` : String(validation.value);
      const prop = findProperty(ctx.node, validation.key);
      emitPropertyAssertion(
        lines,
        `instance.${swiftPropertyName(validation.key)}`,
        expected,
        prop,
        "    ",
      );
    }
    lines.push("  }");
    lines.push("");
  });

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export function emitSwiftConformanceTest(moduleName: string): string {
  return [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    "",
    "import XCTest",
    `@testable import ${moduleName}`,
    "",
    "final class ConformanceTests: XCTestCase {",
    "  func testIntegerValidationRejectsUnsafeValues() throws {",
    "    XCTAssertEqual(try TypraRuntime.int64(NSNumber(value: Int64.max), field: \"value\"), Int64.max)",
    "    XCTAssertThrowsError(try TypraRuntime.int64(NSDecimalNumber(mantissa: 9223372036854775808, exponent: 0, isNegative: false), field: \"value\"))",
    "    XCTAssertThrowsError(try TypraRuntime.int64(NSDecimalNumber(mantissa: 9223372036854775809, exponent: 0, isNegative: true), field: \"value\"))",
    "    XCTAssertThrowsError(try TypraRuntime.int64(1.5, field: \"value\"))",
    "    XCTAssertThrowsError(try TypraRuntime.int32(2147483648, field: \"value\"))",
    "  }",
    "}",
    "",
  ].join("\n");
}

function emitExampleTest(lines: string[], node: TypeNode, typeName: string, example: TestExample, index: number): void {
  lines.push(`  func testJSONRoundTrip${index + 1}() throws {`);
  lines.push(`    let json = ${swiftMultilineString(example.json.join("\n"))}`);
  lines.push(`    let instance = try ${typeName}.fromJSON(json)`);
  emitValidations(lines, "instance", example, node);
  lines.push("    let reloaded = try " + typeName + ".fromJSON(try instance.toJSON())");
  const jsonReloadValidationStart = lines.length;
  emitValidations(lines, "reloaded", example, node);
  if (lines.length === jsonReloadValidationStart) {
    lines.push("    _ = reloaded");
  }
  lines.push("  }");
  lines.push("");
  lines.push(`  func testYAMLRoundTrip${index + 1}() throws {`);
  lines.push(`    let yaml = ${swiftMultilineString(example.yaml.join("\n"))}`);
  lines.push(`    let instance = try ${typeName}.fromYAML(yaml)`);
  emitValidations(lines, "instance", example, node);
  lines.push("    let reloaded = try " + typeName + ".fromYAML(try instance.toYAML())");
  const yamlReloadValidationStart = lines.length;
  emitValidations(lines, "reloaded", example, node);
  if (lines.length === yamlReloadValidationStart) {
    lines.push("    _ = reloaded");
  }
  lines.push("  }");
  lines.push("");
}

function emitValidations(lines: string[], varName: string, example: TestExample, node: TypeNode): void {
  if (emitPolymorphicValidation(lines, varName, example.sample, node)) {
    return;
  }
  for (const validation of example.validations) {
    const expected = validation.delimiter ? `${validation.delimiter}${validation.value}${validation.delimiter}` : String(validation.value);
    const accessor = `${varName}.${swiftPropertyName(validation.key)}`;
    emitPropertyAssertion(lines, accessor, expected, findProperty(node, validation.key), "    ");
  }
  emitStructuredValidations(lines, varName, example.sample, node);
}

function emitStructuredValidations(lines: string[], varName: string, sample: Record<string, any>, node: TypeNode): void {
  for (const prop of node.properties) {
    if (!(prop.name in sample)) continue;
    const value = sample[prop.name];
    const accessor = `${varName}.${swiftPropertyName(prop.name)}`;
    if (prop.isCollection && Array.isArray(value)) {
      lines.push(`    XCTAssertEqual(${requiredAccessor(accessor, prop.isOptional)}.count, ${value.length})`);
      continue;
    }
    if (prop.isDict && value && typeof value === "object" && !Array.isArray(value)) {
      lines.push(`    XCTAssertNotNil(${accessor})`);
      continue;
    }
    if (!prop.isScalar && prop.type && value && typeof value === "object" && !Array.isArray(value)) {
      emitNestedValidation(lines, requiredAccessor(accessor, prop.isOptional), value, prop);
    }
  }
}

function emitNestedValidation(lines: string[], accessor: string, value: Record<string, any>, prop: PropertyNode): void {
  if ((prop.type?.childTypes.length ?? 0) > 0) {
    const child = matchingPolymorphicChild(prop.type!, value);
    if (child) {
      emitChildPatternValidation(lines, accessor, value, prop.type!, child, "    ");
      return;
    }
  }
  for (const [key, expected] of Object.entries(value)) {
    const literal = swiftExpectedLiteral(expected);
    if (literal !== null) {
      emitPropertyAssertion(
        lines,
        `${accessor}.${swiftPropertyName(key)}`,
        literal,
        prop.type?.properties.find(candidate => candidate.name === key),
        "    ",
      );
    }
  }
}

function emitPolymorphicValidation(
  lines: string[],
  accessor: string,
  sample: Record<string, any>,
  node: TypeNode,
): boolean {
  if (!node.discriminator || node.childTypes.length === 0) {
    return false;
  }
  const child = matchingPolymorphicChild(node, sample);
  if (child) {
    emitChildPatternValidation(lines, accessor, sample, node, child, "    ");
    return true;
  }
  if (!node.isAbstract && !defaultPolymorphicChild(node)) {
    lines.push(`    if case .unknown(let concrete) = ${accessor} {`);
    for (const [key, expected] of Object.entries(sample)) {
      const literal = swiftExpectedLiteral(expected);
      if (literal === null) continue;
      const cast = swiftDictionaryCast(expected);
      lines.push(`      XCTAssertEqual(concrete[${swiftStringLiteral(key)}] as? ${cast}, ${literal})`);
    }
    lines.push("    } else {");
    lines.push(`      XCTFail("Expected ${swiftTypeName(node.typeName.name)}.unknown")`);
    lines.push("    }");
    return true;
  }
  return false;
}

function emitChildPatternValidation(
  lines: string[],
  accessor: string,
  sample: Record<string, any>,
  node: TypeNode,
  child: TypeNode,
  indent: string,
): void {
  lines.push(`${indent}if case .${swiftPropertyName(child.typeName.name)}(let concrete) = ${accessor} {`);
  for (const [key, expected] of Object.entries(sample)) {
    if (key === node.discriminator) continue;
    const literal = swiftExpectedLiteral(expected);
    if (literal === null) continue;
    const prop = child.properties.find(candidate => candidate.name === key)
      ?? node.properties.find(candidate => candidate.name === key);
    emitPropertyAssertion(
      lines,
      `concrete.${swiftPropertyName(key)}`,
      literal,
      prop,
      `${indent}  `,
    );
  }
  lines.push(`${indent}} else {`);
  lines.push(`${indent}  XCTFail("Expected ${swiftTypeName(child.typeName.name)}")`);
  lines.push(`${indent}}`);
}

function matchingPolymorphicChild(node: TypeNode, sample: Record<string, any>): TypeNode | undefined {
  const discriminatorValue = node.discriminator ? sample[node.discriminator] : undefined;
  return node.childTypes.find(child => polymorphicChildValue(node, child) === discriminatorValue)
    ?? defaultPolymorphicChild(node);
}

function defaultPolymorphicChild(node: TypeNode): TypeNode | undefined {
  return node.childTypes.find(child => polymorphicChildValue(node, child) === "*");
}

function polymorphicChildValue(node: TypeNode, child: TypeNode): unknown {
  return child.properties.find(prop => prop.name === node.discriminator)?.defaultValue ?? "*";
}

function emitPropertyAssertion(
  lines: string[],
  accessor: string,
  expected: string,
  prop: PropertyNode | undefined,
  indent: string,
): void {
  if (prop?.typeName.name === "unknown" || prop?.typeName.name === "any") {
    const castAccessor = `${accessor} as? String`;
    lines.push(`${
      indent
    }XCTAssertEqual(${prop.isOptional ? `try XCTUnwrap(${castAccessor})` : castAccessor}, ${expected})`);
    return;
  }

  if (prop && !prop.isScalar && prop.type) {
    const nestedKey = coercionProperty(prop.type) ?? prop.type.discriminator;
    if (nestedKey) {
      const valueAccessor = requiredAccessor(accessor, prop.isOptional);
      if (prop.type.childTypes.length > 0) {
        lines.push(`${indent}XCTAssertEqual(try ${valueAccessor}.save()[${swiftStringLiteral(nestedKey)}] as? String, ${expected})`);
      } else {
        const nestedProp = prop.type.properties.find(candidate => candidate.name === nestedKey);
        const nestedAccessor = `${valueAccessor}.${swiftPropertyName(nestedKey)}`;
        lines.push(`${indent}XCTAssertEqual(${requiredAccessor(nestedAccessor, nestedProp?.isOptional ?? false)}, ${expected})`);
      }

      return;
    }
  }

  lines.push(`${indent}XCTAssertEqual(${requiredAccessor(accessor, prop?.isOptional ?? false)}, ${expected})`);
}

function coercionProperty(node: TypeNode): string | undefined {
  for (const coercion of node.coercions) {
    const inputAssignment = Object.entries(coercion.expansion)
      .find(([, value]) => value === "{value}");
    if (inputAssignment) return inputAssignment[0];
  }
  return undefined;
}

function requiredAccessor(accessor: string, isOptional: boolean): string {
  return isOptional ? `(try XCTUnwrap(${accessor}))` : accessor;
}

function findProperty(node: TypeNode, key: string): PropertyNode | undefined {
  return node.properties.find(candidate =>
    swiftPropertyName(candidate.name) === swiftPropertyName(key));
}

function swiftExpectedLiteral(value: unknown): string | null {
  if (typeof value === "string") return swiftStringLiteral(value);
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  return null;
}

function swiftDictionaryCast(value: unknown): string {
  if (typeof value === "boolean") return "Bool";
  if (typeof value === "number") return "NSNumber";
  return "String";
}

function swiftMultilineString(value: string): string {
  return `"""\n${value.replace(/"""/g, "\\\"\\\"\\\"")}\n"""`;
}
