/**
 * TypeScript code emitter — Declaration IR → TypeScript source code.
 *
 * Replaces `file.ts.njk` (~414 lines of Nunjucks templates)
 * with a typed TypeScript function that walks the FileDecl tree.
 *
 * The emitter produces correctly-formatted TypeScript code using modern
 * class patterns with `Partial<T>` constructors. Output is post-processed
 * by prettier + eslint, so exact whitespace is not critical.
 *
 * Structural blocks emitted (in order):
 *   1. Header comment (auto-generated warning)
 *   2. Imports (LoadContext/SaveContext, referenced types)
 *   3. For each type in the file:
 *      a. [abstract] class definition with extends
 *      b. shorthandProperty static ClassVar
 *      c. Field declarations with type annotations + defaults
 *      d. Constructor with Partial<T>
 *      e. //#region Load Methods
 *         - load() static method
 *         - loadKind() for polymorphic dispatch (private static)
 *         - Collection helpers (loadX / saveX)
 *      f. //#endregion
 *      g. //#region Save Methods
 *         - save() instance method
 *         - toYaml() / toJson()
 *         - fromJson() / fromYaml() static methods
 *      h. //#endregion
 *      i. Factory static methods
 *      j. Method stubs (as comments)
 */

import {
  FileDecl,
  TypeDecl,
  FieldDecl,
  LoadAssignment,
  SaveAssignment,
  CollectionHelperDecl,
  PolymorphicDispatchDecl,
  FactoryDecl,
  CoercionDecl,
  PropertyCategory,
  WireDecl,
  isClosedPolymorphicDispatch,
} from "../../ir/declarations.js";
import {
  orderedEntryShorthandCases,
  entryShorthandTarget,
  scalarRuntimeKind,
} from "../../ir/scalar-kinds.js";
import { ExprVisitor } from "../../ir/visitor.js";
import { toKebabCase } from "../../ir/utilities.js";

export interface TypeScriptEmitterOptions {
  nativeSerialization?: "none" | "zod" | "standard-schema";
}

/**
 * Type mapping from TypeSpec scalar types to TypeScript types.
 */
const TYPE_MAP: Record<string, string> = {
  string: "string",
  boolean: "boolean",
  int32: "number",
  int64: "number",
  float32: "number",
  float64: "number",
  number: "number",
  integer: "number",
  numeric: "number",
  float: "number",
  plainDate: "Date",
  plainTime: "Date",
  utcDateTime: "Date",
  bytes: "Uint8Array",
  url: "string",
  unknown: "unknown",
  any: "unknown",
  dictionary: "Record<string, unknown>",
};

/**
 * Map a TypeSpec scalar to its typeof check string for coercion guards.
 */
function typeofCheck(scalarType: string): string | null {
  switch (scalarType) {
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "int32":
    case "int64":
    case "float32":
    case "float64":
    case "number":
    case "integer":
    case "numeric":
    case "float":
      return "number";
    default:
      return null;
  }
}

function paramType(typeStr: string): string {
  return TYPE_MAP[typeStr] || typeStr;
}

function returnType(typeStr: string): string {
  if (typeStr.endsWith("?")) {
    const inner = typeStr.slice(0, -1);
    return `${returnType(inner)} | null`;
  }
  if (typeStr === "Record<unknown>") return "Record<string, unknown>";
  if (typeStr === "void") return "void";
  return TYPE_MAP[typeStr] || typeStr;
}

// ============================================================================
// Main entry point
// ============================================================================

/**
 * Emit a complete TypeScript file from a FileDecl.
 *
 * @param decl - The file declaration to emit
 * @param visitor - Expression visitor for rendering expressions
 * @param namespace - Optional namespace override
 * @param group - Semantic group folder this file lives in (e.g. "connection"). Empty string = root.
 */
export function emitTypeScriptFile(
  decl: FileDecl,
  visitor: ExprVisitor,
  namespace?: string,
  group: string = "",
  options: TypeScriptEmitterOptions = {},
): string {
  const lines: string[] = [];
  const emitZod = options.nativeSerialization === "zod";

  // 1. Header
  lines.push("// Copyright (c) Microsoft. All rights reserved.");
  lines.push("// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.");
  lines.push("");

  // 2. Imports
  // Protocol-only files don't need LoadContext/SaveContext
  const hasNonProtocol = decl.types.some(t => !t.isProtocol);
  if (hasNonProtocol) {
    // Context file is always at the model root — go up one level when inside a group subfolder
    const contextPath = group ? "../context" : "./context";
    lines.push(`import { LoadContext, SaveContext } from "${contextPath}";`);
  }
  if (emitZod && hasNonProtocol) {
    lines.push('import { z } from "zod";');
  }

  for (const imp of decl.imports) {
    const kebab = toKebabCase(imp.module);
    if (imp.group === group) {
      // Same group (or both root): relative sibling
      lines.push(`import { ${imp.names.join(", ")} } from "./${kebab}";`);
    } else if (imp.group) {
      // Different non-empty group: go up to model root, then into the group subfolder
      lines.push(`import { ${imp.names.join(", ")} } from "../${imp.group}/${kebab}";`);
    } else {
      // Root-level module: go up one level from group subfolder
      lines.push(`import { ${imp.names.join(", ")} } from "../${kebab}";`);
    }
  }
  lines.push("");

  // 2.5. Enum type aliases
  for (const enumDef of decl.enums) {
    const values = enumDef.values.map(v => `"${v}"`).join(" | ");
    if (enumDef.isOpen) {
      // Open enum — known values + any string
      lines.push(`export type ${enumDef.name} = ${values} | (string & {});`);
    } else {
      lines.push(`export type ${enumDef.name} = ${values};`);
    }
  }
  if (decl.enums.length > 0) {
    lines.push("");
  }
  for (const enumDef of decl.enums) {
    emitEnumParser(enumDef, lines);
  }
  if (decl.enums.some(hasParseAliases)) {
    lines.push("");
  }

  // 3. Emit each type
  for (const type of decl.types) {
    emitType(type, lines, visitor, emitZod, decl.types);
    lines.push("");
  }

  return lines.join("\n") + "\n";
}

function hasParseAliases(enumDef: { parseAliases: Record<string, string[]> }): boolean {
  return Object.values(enumDef.parseAliases).some(aliases => aliases.length > 0);
}

function enumParserName(enumName: string): string {
  return `parse${enumName}`;
}

function emitEnumParser(enumDef: { name: string; values: string[]; parseAliases: Record<string, string[]>; isOpen: boolean }, lines: string[]): void {
  if (!hasParseAliases(enumDef)) return;
  lines.push(`function ${enumParserName(enumDef.name)}(value: unknown): ${enumDef.name} {`);
  lines.push("  const text = String(value);");
  lines.push("  switch (text) {");
  for (const value of enumDef.values) {
    lines.push(`    case ${JSON.stringify(value)}:`);
    lines.push(`      return ${JSON.stringify(value)};`);
  }
  for (const [canonical, aliases] of Object.entries(enumDef.parseAliases)) {
    for (const alias of aliases) {
      lines.push(`    case ${JSON.stringify(alias)}:`);
    }
    lines.push(`      return ${JSON.stringify(canonical)};`);
  }
  lines.push("    default:");
  if (enumDef.isOpen) {
    lines.push(`      return text as ${enumDef.name};`);
  } else {
    lines.push(`      throw new Error(\`Invalid ${enumDef.name} value: \${text}\`);`);
  }
  lines.push("  }");
  lines.push("}");
}

// ============================================================================
// Type emission
// ============================================================================

function emitType(type: TypeDecl, lines: string[], visitor: ExprVisitor, emitZod: boolean, allTypes: TypeDecl[]): void {
  const name = type.typeName.name;

  // Protocol types → emit as interface with method signatures
  if (type.isProtocol) {
    emitProtocolInterface(type, lines);
    return;
  }

  // Class definition
  const abstractPrefix = type.isAbstract ? "abstract " : "";
  const extendsClause = type.base ? ` extends ${type.base.name}` : "";
  lines.push(`export ${abstractPrefix}class ${name}${extendsClause} {`);

  // shorthandProperty static
  const shorthand = type.coercionProperty ? `"${type.coercionProperty}"` : "undefined";
  lines.push(`  static readonly shorthandProperty: string | undefined = ${shorthand};`);
  if (emitZod) {
    emitZodSchemas(type, lines, allTypes);
  }
  lines.push("");

  // Field declarations
  for (const field of type.fields) {
    const annotation = tsTypeAnnotation(field);
    const defaultVal = tsDefaultValue(field);
    if (field.isOptional) {
      lines.push(`  ${field.name}?: ${annotation}${defaultVal};`);
    } else if (defaultVal === "" && field.category.kind === "complex") {
      // Required complex types without defaults need definite assignment assertion
      lines.push(`  ${field.name}!: ${annotation};`);
    } else {
      lines.push(`  ${field.name}: ${annotation}${defaultVal};`);
    }
  }
  if (absorbsUnknownValues(type.polymorphicDispatch)) {
    // `protected` rather than `private`: an abstract base's unknown-value carrier is a
    // separate subclass and has to populate this.
    lines.push("  protected raw: Record<string, unknown> = {};");
  }
  lines.push("");

  if (absorbsUnknownValues(type.polymorphicDispatch)) {
    emitRawCloneMethod(lines);
  }

  // Constructor
  emitConstructor(type, lines);

  // //#region Load Methods
  lines.push("  //#region Load Methods");
  lines.push("");

  // load() static method
  emitLoadMethod(type, lines);

  // Polymorphic dispatch
  if (type.polymorphicDispatch) {
    emitPolymorphicDispatch(
      name,
      type.polymorphicDispatch,
      lines,
      needsUnknownCarrier(type) ? unknownCarrierName(name) : undefined,
    );
  }

  function emitRawCloneMethod(lines: string[]): void {
    lines.push("  protected static cloneRawValue(value: unknown): unknown {");
    lines.push("    if (Array.isArray(value)) {");
    lines.push("      return value.map(item => this.cloneRawValue(item));");
    lines.push("    }");
    lines.push('    if (value !== null && typeof value === "object") {');
    lines.push("      const result: Record<string, unknown> = {};");
    lines.push("      for (const [key, item] of Object.entries(value as Record<string, unknown>)) {");
    lines.push("        result[key] = this.cloneRawValue(item);");
    lines.push("      }");
    lines.push("      return result;");
    lines.push("    }");
    lines.push("    return value;");
    lines.push("  }");
    lines.push("");
  }

  // Collection helpers
  for (const helper of type.collectionHelpers) {
    emitCollectionLoadHelper(name, helper, lines);
    emitCollectionSaveHelper(name, helper, lines);
  }

  lines.push("  //#endregion");
  lines.push("");

  // //#region Save Methods
  lines.push("  //#region Save Methods");
  lines.push("");

  // save() instance method
  emitSaveMethod(type, lines);

  // toWire() method (only if wire mappings exist)
  if (type.wire !== null) {
    emitToWireMethod(type, lines);
  }

  // toYaml / toJson
  emitToYaml(name, lines);
  emitToJson(name, lines);

  // fromJson / fromYaml
  emitFromJson(name, type, lines);
  emitFromYaml(name, type, lines);

  lines.push("  //#endregion");

  // Factory methods
  if (type.factories.length > 0) {
    lines.push("");
    for (const factory of type.factories) {
      emitFactory(name, factory, visitor, lines);
    }
  }

  // Method stubs — emitted as a sibling interface below the class

  lines.push("}");

  if (needsUnknownCarrier(type)) {
    emitUnknownCarrier(type, lines);
  }

  // Emit MessageHelpers-style interface after the class
  if (type.methods.length > 0) {
    emitMethodHelpersInterface(type, lines);
  }

  if (emitZod) {
    lines.push("");
    lines.push(`export type ${name}Wire = z.infer<typeof ${name}.wireSchema>;`);
  }
}

/**
 * Emit the concrete carrier for an abstract base whose discriminator is open.
 *
 * Rust models polymorphism as an enum and adds an `Unknown { kind_name, raw }` variant;
 * Swift adds `case unknown([String: Any])`. The class-based backends have no variant to add,
 * so the equivalent is a concrete subclass. The base stays `abstract`, which honours the
 * schema's `@abstract`, and unknown discriminator values land here instead of throwing.
 *
 * The carrier needs no `kind` field of its own: the base's `load()` applies the declared
 * field assignments to whatever instance `loadKind` returned, so the exact unrecognized
 * discriminator is already preserved on `kind` by the time this instance is handed back.
 * It also needs no `save()`: the base's `save()` seeds its result from `raw`, so the
 * inherited implementation already re-emits the unknown payload.
 */
function emitUnknownCarrier(type: TypeDecl, lines: string[]): void {
  const parentName = type.typeName.name;
  const carrier = unknownCarrierName(parentName);

  lines.push("");
  lines.push(`/**`);
  lines.push(` * Carries a ${parentName} whose discriminator value matches no known subtype.`);
  lines.push(` *`);
  lines.push(` * The unrecognized value stays on \`${type.polymorphicDispatch!.discriminatorField}\` and every`);
  lines.push(` * key the schema does not declare is preserved verbatim, so an unknown ${parentName}`);
  lines.push(` * survives a load/save round-trip unchanged.`);
  lines.push(` */`);
  lines.push(`export class ${carrier} extends ${parentName} {`);
  lines.push(`  static load(data: Record<string, unknown>, context?: LoadContext): ${carrier} {`);
  lines.push(`    const instance = new ${carrier}();`);
  lines.push(`    instance.raw = ${parentName}.cloneRawValue(data) as Record<string, unknown>;`);
  for (const a of type.load.assignments) {
    lines.push(`    delete instance.raw["${a.sourceName}"];`);
  }
  lines.push("    return instance;");
  lines.push("  }");
  lines.push("}");
}

/**
 * Emit a TypeScript interface named `<TypeName>Helpers` declaring the
 * `@method` contract for a concrete type. The generated class does NOT
 * implement this interface on its own — runtime code must provide an
 * implementation. The type checker verifies conformance via structural typing.
 */
function emitMethodHelpersInterface(type: TypeDecl, lines: string[]): void {
  const name = type.typeName.name;
  lines.push("");
  lines.push(`/**`);
  lines.push(` * Helper contract for \`${name}\`.`);
  lines.push(` *`);
  lines.push(` * Runtime implementations must provide these methods on every ${name}`);
  lines.push(` * instance (either on the generated class or on a wrapper type). The`);
  lines.push(` * TypeScript compiler enforces conformance wherever a value is typed as`);
  lines.push(` * \`${name}Helpers\`.`);
  lines.push(` */`);
  lines.push(`export interface ${name}Helpers {`);
  for (const m of type.methods) {
    if (m.description) {
      lines.push(`  /** ${m.description} */`);
    }
    const params = Object.entries(m.params)
      .map(([pName, pType]) => `${pName}: ${returnType(pType)}`)
    if (m.runtimeCancellable) {
      params.push("signal?: AbortSignal");
    }
    const ret = returnType(m.returns);
    // Zero-param non-verb methods are emitted as getter-style readonly
    // properties (matches C#/Python emitters). Callers access them without
    // parens, e.g. ``msg.text``.
    const isGetter = Object.keys(m.params).length === 0 && !m.runtimeCancellable && !isMethodStyle(m.name);
    if (isGetter) {
      lines.push(`  readonly ${m.name}: ${ret};`);
    } else {
      lines.push(`  ${m.name}(${params.join(", ")}): ${ret};`);
    }
  }
  lines.push("}");
}

function emitZodSchemas(type: TypeDecl, lines: string[], allTypes: TypeDecl[]): void {
  const name = type.typeName.name;
  lines.push(`  static readonly wireObjectSchema: z.ZodObject<any> = ${zodObjectExpression(type, allTypes)};`);
  lines.push(`  static readonly wireObjectSchemaWithoutName: z.ZodObject<any> = ${zodObjectExpression(type, allTypes, "name")};`);
  lines.push(`  static readonly wireSchema: z.ZodType<Record<string, unknown>> = z.lazy(() => ${zodWireSchemaExpression(type)});`);
  lines.push(`  static readonly schema = z.any().transform((data, ctx) => {`);
  lines.push(`    try {`);
  lines.push(`      return ${name}.load(data as Record<string, unknown>).save();`);
  lines.push(`    } catch (error) {`);
  lines.push(`      ctx.addIssue({ code: z.ZodIssueCode.custom, message: String(error) });`);
  lines.push(`      return z.NEVER;`);
  lines.push(`    }`);
  lines.push(`  }).pipe(${name}.wireSchema);`);
}

function zodWireSchemaExpression(type: TypeDecl): string {
  const dispatch = type.polymorphicDispatch;
  if (!dispatch || dispatch.variants.length === 0) {
    return `${type.typeName.name}.wireObjectSchema`;
  }

  const variantSchemas = dispatch.variants
    .map(variant => `${variant.typeName.name}.wireObjectSchema as any`)
    .join(", ");
  const knownSchema = dispatch.variants.length === 1
    ? variantSchemas
    : `z.discriminatedUnion("${dispatch.discriminatorField}", [${variantSchemas}])`;

  if (isClosedPolymorphicDispatch(dispatch)) {
    return knownSchema;
  }

  const fallback = dispatch.defaultVariant && !dispatch.defaultVariant.isSelfReference
    ? `${dispatch.defaultVariant.typeName.name}.wireObjectSchema`
    : `${type.typeName.name}.wireObjectSchema.passthrough()`;
  return `z.union([${knownSchema}, ${fallback}])`;
}

function zodObjectExpression(type: TypeDecl, allTypes: TypeDecl[], omitField?: string): string {
  const entries = type.save.assignments
    .filter(a => a.fieldName !== omitField)
    .map(a => `    "${a.targetName}": ${zodFieldSchema(type, a, allTypes)}${a.isOptional ? ".optional()" : ""},`);
  const objectBody = entries.length > 0
    ? `{\n${entries.join("\n")}\n  }`
    : "{}";
  const object = type.base
    ? `${type.base.name}.${omitField === "name" ? "wireObjectSchemaWithoutName" : "wireObjectSchema"}.extend(${objectBody})`
    : `z.object(${objectBody})`;
  return absorbsUnknownValues(type.polymorphicDispatch) ? `${object}.passthrough()` : object;
}

function zodFieldSchema(type: TypeDecl, assignment: SaveAssignment, allTypes: TypeDecl[]): string {
  const field = type.fields.find(candidate => candidate.name === assignment.fieldName);
  const baseType = type.base ? allTypes.find(candidate => candidate.typeName.name === type.base!.name) : undefined;
  const discriminatorField = type.polymorphicDispatch?.discriminatorField ?? baseType?.polymorphicDispatch?.discriminatorField;
  if (
    field &&
    type.base !== null &&
    field.name === discriminatorField &&
    field.defaultValue !== null &&
    field.defaultValue !== undefined
  ) {
    if (field.defaultValue === "*") {
      return "z.string()";
    }
    return `z.literal(${JSON.stringify(field.defaultValue)})`;
  }

  if (field?.enumName && field.allowedValues.length > 0) {
    return field.isOpenEnum ? "z.string()" : zodEnumExpression(field.allowedValues);
  }

  const cat = assignment.category;
  switch (cat.kind) {
    case "scalar":
      return zodScalarSchema(cat.scalarType);
    case "dict":
      return cat.valueType && cat.valueType !== "unknown"
        ? `z.record(${zodRecordValueSchema(cat.valueType)})`
        : "z.record(z.unknown())";
    case "collection_scalar":
      return `z.array(${zodScalarSchema(cat.scalarType)})`;
    case "complex":
      return `z.lazy(() => ${cat.typeName}.wireSchema)`;
    case "collection_complex": {
      const helper = type.collectionHelpers.find(candidate => candidate.propertyName === assignment.fieldName);
      const arraySchema = `z.array(z.lazy(() => ${cat.typeName}.wireSchema))`;
      if (helper?.hasNameProperty) {
        return `z.union([${arraySchema}, z.record(z.lazy(() => ${cat.typeName}.wireObjectSchemaWithoutName))])`;
      }
      return arraySchema;
    }
  }
}

function zodScalarSchema(scalarType: string): string {
  switch (TYPE_MAP[scalarType] ?? scalarType) {
    case "string":
      return "z.string()";
    case "number":
      return "z.number()";
    case "boolean":
      return "z.boolean()";
    case "Uint8Array":
      return "z.instanceof(Uint8Array)";
    case "Date":
      return "z.instanceof(Date)";
    case "unknown":
    case "any":
      return "z.unknown()";
    default:
      return "z.unknown()";
  }
}

function zodRecordValueSchema(valueType: string): string {
  const scalarSchema = zodScalarSchema(valueType);
  return scalarSchema === "z.unknown()" && !TYPE_MAP[valueType]
    ? `z.lazy(() => ${valueType}.wireSchema)`
    : scalarSchema;
}

function zodEnumExpression(values: string[]): string {
  if (values.length === 0) {
    return "z.never()";
  }
  if (values.length === 1) {
    return `z.literal(${JSON.stringify(values[0])})`;
  }
  return `z.enum([${values.map(value => JSON.stringify(value)).join(", ")}])`;
}

/**
 * Verbs that indicate an action — zero-param @methods whose name starts with
 * one of these are emitted as regular TypeScript methods. Everything else
 * becomes a ``readonly`` getter-style property. Mirrors the C#/Python emitter
 * heuristic so that ``message.text`` stays a property and
 * ``message.toTextContent()`` stays a method in every runtime.
 */
const TS_METHOD_VERB_PREFIXES = [
  "to", "get", "set", "fetch", "compute", "make", "build", "create",
  "load", "save", "convert", "parse", "format", "render", "serialize",
  "deserialize", "find", "calculate", "invoke", "execute", "run",
];

function isMethodStyle(name: string): boolean {
  const lower = name.toLowerCase();
  for (const prefix of TS_METHOD_VERB_PREFIXES) {
    if (lower === prefix) return true;
    if (lower.startsWith(prefix) && name.length > prefix.length) {
      const next = name[prefix.length];
      if (next === next.toUpperCase() && next !== next.toLowerCase()) {
        return true;
      }
    }
  }
  return false;
}

// ============================================================================
// Protocol interface emission
// ============================================================================

/**
 * Emit a TypeScript interface for a protocol type.
 * Protocols have methods but no data fields, load/save, or serialization.
 */
function emitProtocolInterface(type: TypeDecl, lines: string[]): void {
  const name = type.typeName.name;

  if (type.description) {
    lines.push(`/** ${type.description} */`);
  }
  lines.push(`export interface ${name} {`);

  for (const method of type.methods) {
    if (method.description) {
      lines.push(`  /** ${method.description} */`);
    }
    const params = Object.entries(method.params)
      .map(([pName, pType]) => `${pName}: ${returnType(pType)}`)
    if (method.runtimeCancellable) {
      params.push("signal?: AbortSignal");
    }
    const ret = returnType(method.returns);
    const optMark = method.optional ? "?" : "";

    if (method.sync) {
      lines.push(`  ${method.name}${optMark}(${params.join(", ")}): ${ret};`);
    } else {
      lines.push(`  ${method.name}${optMark}(${params.join(", ")}): Promise<${ret}>;`);
    }
  }

  lines.push("}");
}

function tsTypeAnnotation(f: FieldDecl): string {
  // Named enum field — use the enum type alias
  if (f.enumName && f.allowedValues.length > 0) {
    return f.isOptional ? `${f.enumName} | undefined` : f.enumName;
  }
  const cat = f.category;
  switch (cat.kind) {
    case "dict":
      return f.isOptional
        ? `Record<string, ${tsRecordValueType(cat.valueType)}> | undefined`
        : `Record<string, ${tsRecordValueType(cat.valueType)}>`;
    case "collection_scalar":
      return `${TYPE_MAP[cat.scalarType] || "unknown"}[]`;
    case "collection_complex":
      return `${cat.typeName}[]`;
    case "scalar": {
      const tsType = TYPE_MAP[cat.scalarType] || "unknown";
      return f.isOptional ? `${tsType} | undefined` : tsType;
    }
    case "complex":
      return f.isOptional ? `${cat.typeName} | undefined` : cat.typeName;
  }
}

function tsRecordValueType(valueType: string | undefined): string {
  if (!valueType || valueType === "unknown") return "unknown";
  return TYPE_MAP[valueType] || valueType;
}

// ============================================================================
// Default values
// ============================================================================

function tsDefaultValue(f: FieldDecl): string {
  const cat = f.category;

  if (cat.kind === "collection_scalar" || cat.kind === "collection_complex") {
    if (f.isOptional && !f.hasExplicitDefault) {
      return "";
    }
    return " = []";
  }

  if (f.isOptional) {
    return "";
  }

  // Enum fields — use the field's default value or the first allowed value
  if (f.enumName && f.allowedValues.length > 0) {
    const dv = typeof f.defaultValue === "string" && f.allowedValues.includes(f.defaultValue)
      ? f.defaultValue
      : f.allowedValues[0];
    return ` = "${dv}"`;
  }

  if (cat.kind === "dict") {
    return " = {}";
  }

  if (cat.kind === "scalar") {
    return tsScalarDefault(cat.scalarType, f.defaultValue);
  }

  // complex required types — no inline default, handled by constructor
  return "";
}

function tsScalarDefault(scalarType: string, defaultValue: string | number | boolean | null): string {
  if (defaultValue !== undefined && defaultValue !== null) {
    if (typeof defaultValue === "string") {
      return ` = "${defaultValue}"`;
    }
    return ` = ${defaultValue}`;
  }

  switch (scalarType) {
    case "string":
      return ' = ""';
    case "boolean":
      return " = false";
    case "number":
    case "int32":
    case "int64":
    case "float32":
    case "float64":
    case "integer":
    case "numeric":
    case "float":
      return " = 0";
    default:
      return "";
  }
}

// ============================================================================
// Constructor
// ============================================================================

function emitConstructor(type: TypeDecl, lines: string[]): void {
  const name = type.typeName.name;
  const hasBase = type.base !== null;

  lines.push(`  constructor(init?: Partial<${name}>) {`);
  if (hasBase) {
    lines.push("    super(init);");
  }

  for (const field of type.fields) {
    const cat = field.category;
    if (
      field.isOptional &&
      field.hasExplicitDefault &&
      (cat.kind === "collection_scalar" || cat.kind === "collection_complex")
    ) {
      lines.push(`    this.${field.name} = init?.${field.name} ?? [];`);
    } else if (field.isOptional) {
      lines.push(`    if (init?.${field.name} !== undefined) {`);
      lines.push(`      this.${field.name} = init.${field.name};`);
      lines.push("    }");
    } else if (cat.kind === "collection_scalar" || cat.kind === "collection_complex") {
      lines.push(`    this.${field.name} = init?.${field.name} ?? [];`);
    } else if (cat.kind === "dict") {
      lines.push(`    this.${field.name} = init?.${field.name} ?? {};`);
    } else if (field.enumName && field.allowedValues.length > 0 && !field.isOptional) {
      const dv = typeof field.defaultValue === "string" && field.allowedValues.includes(field.defaultValue)
        ? field.defaultValue
        : field.allowedValues[0];
      lines.push(`    this.${field.name} = init?.${field.name} ?? "${dv}";`);
    } else if (cat.kind === "scalar") {
      const def = tsConstructorDefault(cat.scalarType, field.defaultValue);
      lines.push(`    this.${field.name} = init?.${field.name} ?? ${def};`);
    } else {
      // complex required — use init value or construct a new default
      lines.push(`    if (init?.${field.name} !== undefined) {`);
      lines.push(`      this.${field.name} = init.${field.name};`);
      lines.push("    }");
    }
  }

  lines.push("  }");
  lines.push("");
}

function tsConstructorDefault(scalarType: string, defaultValue: string | number | boolean | null): string {
  if (defaultValue !== undefined && defaultValue !== null) {
    if (typeof defaultValue === "string") {
      return `"${defaultValue}"`;
    }
    return String(defaultValue);
  }

  switch (scalarType) {
    case "string":
      return '""';
    case "boolean":
      return "false";
    case "number":
    case "int32":
    case "int64":
    case "float32":
    case "float64":
    case "integer":
    case "numeric":
    case "float":
      return "0";
    default:
      return '""';
  }
}

// ============================================================================
// load() method
// ============================================================================

function emitLoadMethod(type: TypeDecl, lines: string[]): void {
  const name = type.typeName.name;

  lines.push(`  static load(data: Record<string, unknown>, context?: LoadContext): ${name} {`);
  lines.push("    context ??= new LoadContext();");

  // Context pre-processing
  lines.push("    if (context) {");
  lines.push("      data = context.processInput(data) as Record<string, unknown>;");
  lines.push("    }");

  // Coercion checks — group by JS typeof to handle int/float distinction
  if (type.load.coercions.length > 0) {
    lines.push("");
    lines.push("    // Handle alternate representations");
    emitCoercionBranches(name, type.load.coercions, type, lines);
  }

  lines.push("");

  for (const a of type.load.assignments) {
    const field = type.fields.find(candidate => candidate.name === a.fieldName);
    if (field?.category.kind !== "complex" || field.isOptional || field.hasExplicitDefault) continue;
    lines.push(`    if (data["${a.sourceName}"] === undefined || data["${a.sourceName}"] === null) {`);
    lines.push(`      throw new Error(\`\${context.at("${a.sourceName}").path}: missing required field\`);`);
    lines.push("    }");
  }

  // Create instance (polymorphic dispatch or direct)
  if (type.load.hasPolymorphicDispatch && type.polymorphicDispatch) {
    lines.push(`    // Load polymorphic ${name} instance`);
    lines.push(`    const instance = ${name}.loadKind(data, context);`);
  } else {
    lines.push(`    const instance = new ${name}();`);
  }

  lines.push("");

  // Per-property assignments
  for (const a of type.load.assignments) {
    lines.push(`    if (data["${a.sourceName}"] !== undefined && data["${a.sourceName}"] !== null) {`);
    lines.push(`      ${emitLoadAssignment(a)}`);
    lines.push("    }");
  }
  if (type.polymorphicDispatch?.defaultVariant?.isSelfReference) {
    lines.push("");
    lines.push(`    if (instance.constructor === ${name}) {`);
    lines.push(`      instance.raw = ${name}.cloneRawValue(data) as Record<string, unknown>;`);
    lines.push("    }");
  }

  // Context post-processing
  lines.push("");
  lines.push("    if (context) {");
  lines.push(`      return context.processOutput(instance) as ${name};`);
  lines.push("    }");
  lines.push("    return instance;");
  lines.push("  }");
  lines.push("");
}

function emitLoadAssignment(a: LoadAssignment): string {
  // Named enum — cast string to enum type alias
  if (a.enumName && a.allowedValues.length > 0) {
    if (Object.keys(a.parseAliases).length > 0) {
      return `instance.${a.fieldName} = ${enumParserName(a.enumName)}(data["${a.sourceName}"]);`;
    }
    return `instance.${a.fieldName} = String(data["${a.sourceName}"]) as ${a.enumName};`;
  }
  const cat = a.category;
  switch (cat.kind) {
    case "scalar": {
      const tsType = TYPE_MAP[cat.scalarType];
      switch (tsType) {
        case "string":
          return `instance.${a.fieldName} = String(data["${a.sourceName}"]);`;
        case "number":
          return `instance.${a.fieldName} = Number(data["${a.sourceName}"]);`;
        case "boolean":
          return `instance.${a.fieldName} = Boolean(data["${a.sourceName}"]);`;
        default:
          return `instance.${a.fieldName} = data["${a.sourceName}"] as ${tsType};`;
      }
    }
    case "complex":
      return `instance.${a.fieldName} = ${cat.typeName}.load(data["${a.sourceName}"] as Record<string, unknown>, context.at("${a.sourceName}"));`;
    case "collection_scalar": {
      const tsType = TYPE_MAP[cat.scalarType];
      switch (tsType) {
        case "string":
          return `instance.${a.fieldName} = (data["${a.sourceName}"] as unknown[]).map(v => String(v));`;
        case "number":
          return `instance.${a.fieldName} = (data["${a.sourceName}"] as unknown[]).map(v => Number(v));`;
        case "boolean":
          return `instance.${a.fieldName} = (data["${a.sourceName}"] as unknown[]).map(v => Boolean(v));`;
        default:
          return `instance.${a.fieldName} = data["${a.sourceName}"] as ${tsType}[];`;
      }
    }
    case "collection_complex":
      return `instance.${a.fieldName} = ${a.parentTypeName}.load${capitalize(a.fieldName)}(data["${a.sourceName}"] as unknown[], context.at("${a.sourceName}"));`;
    case "dict":
      return dictLoadAssignment(a.fieldName, a.sourceName, cat.valueType);
  }
}

function dictLoadAssignment(fieldName: string, sourceName: string, valueType: string | undefined): string {
  if (!valueType || valueType === "unknown") {
    return `instance.${fieldName} = data["${sourceName}"] as Record<string, unknown>;`;
  }
  const valueExpr = dictValueLoadExpr("value", valueType, `context.at("${sourceName}").at(key)`);
  return `instance.${fieldName} = Object.fromEntries(Object.entries(data["${sourceName}"] as Record<string, unknown>).map(([key, value]) => [key, ${valueExpr}]));`;
}

function dictValueLoadExpr(valueExpr: string, valueType: string, contextExpr: string): string {
  const tsType = TYPE_MAP[valueType];
  switch (tsType) {
    case "string":
      return `String(${valueExpr})`;
    case "number":
      return `Number(${valueExpr})`;
    case "boolean":
      return `Boolean(${valueExpr})`;
    case "unknown":
      return valueExpr;
    default:
      return `${valueType}.load(${valueExpr} as Record<string, unknown>, ${contextExpr})`;
  }
}

/**
 * Emit coercion branches, grouping coercions that share the same JS typeof.
 *
 * In TypeScript, int32 and float64 both map to `typeof data === "number"`.
 * When multiple coercions share a typeof, we emit a single outer `if` with
 * `Number.isInteger()` sub-branches to disambiguate.
 */
function emitCoercionBranches(
  typeName: string,
  coercions: CoercionDecl[],
  type: TypeDecl,
  lines: string[],
): void {
  // Group coercions by JS typeof check
  const groups = new Map<string, CoercionDecl[]>();
  for (const c of coercions) {
    const jsType = typeofCheck(c.scalarType);
    if (!jsType) continue;
    if (!groups.has(jsType)) groups.set(jsType, []);
    groups.get(jsType)!.push(c);
  }

  for (const [jsType, group] of groups) {
    if (group.length === 1) {
      // Single coercion for this typeof — emit simple branch
      emitCoercionBranch(typeName, group[0], type, lines);
    } else {
      // Multiple coercions sharing the same typeof (e.g., int32 + float64 → "number")
      lines.push(`    if (typeof data === "${jsType}") {`);

      // Find integer and float coercions
      const intCoercion = group.find(c => isIntegerScalar(c.scalarType));
      const floatCoercion = group.find(c => !isIntegerScalar(c.scalarType));

      if (intCoercion && floatCoercion) {
        // Use Number.isInteger to disambiguate
        lines.push("      if (Number.isInteger(data)) {");
        emitCoercionBody(typeName, intCoercion, type, lines, "        ");
        lines.push("      } else {");
        emitCoercionBody(typeName, floatCoercion, type, lines, "        ");
        lines.push("      }");
      } else {
        // Fallback: just emit them sequentially (shouldn't happen)
        for (const c of group) {
          emitCoercionBody(typeName, c, type, lines, "      ");
        }
      }

      lines.push("    }");
    }
  }
}

function isIntegerScalar(scalarType: string): boolean {
  return scalarType === "int32" || scalarType === "int64" || scalarType === "integer";
}

/**
 * Emit a single coercion branch — typeof check with early return.
 */
function emitCoercionBranch(
  typeName: string,
  c: CoercionDecl,
  type: TypeDecl,
  lines: string[],
): void {
  const jsType = typeofCheck(c.scalarType);
  if (!jsType) return;

  lines.push(`    if (typeof data === "${jsType}") {`);
  emitCoercionBody(typeName, c, type, lines, "      ");
  lines.push("    }");
}

/**
 * Emit the body of a coercion branch (instance creation + property assignment).
 */
function emitCoercionBody(
  typeName: string,
  c: CoercionDecl,
  type: TypeDecl,
  lines: string[],
  indent: string,
): void {
  if (c.needsDispatch && type.polymorphicDispatch) {
    // Dynamic discriminator — must go through dispatch
    const dictFields = c.assignments.map(a => {
      const val = a.isInput ? "data" : `"${a.literalValue}"`;
      return `"${a.fieldName}": ${val}`;
    });
    lines.push(`${indent}return ${typeName}.loadKind({ ${dictFields.join(", ")} } as Record<string, unknown>, context);`);
  } else {
    // Direct property setting
    lines.push(`${indent}const instance = new ${typeName}();`);
    for (const a of c.assignments) {
      if (a.isInput) {
        // Check if the target field is an enum — cast to enum type instead of scalar
        const targetField = type.fields.find(f => f.name === a.fieldName);
        const castType = targetField?.enumName && targetField.allowedValues.length > 0
          ? targetField.enumName
          : (TYPE_MAP[c.scalarType] || "unknown");
        lines.push(`${indent}instance.${a.fieldName} = data as ${castType};`);
      } else {
        lines.push(`${indent}instance.${a.fieldName} = "${a.literalValue}";`);
      }
    }
    lines.push(`${indent}if (context) {`);
    lines.push(`${indent}  return context.processOutput(instance) as ${typeName};`);
    lines.push(`${indent}}`);
    lines.push(`${indent}return instance;`);
  }
}

// ============================================================================
// Polymorphic dispatch (loadKind)
// ============================================================================

/**
 * Does this dispatch absorb unrecognized discriminator values into a carrier
 * rather than rejecting them?
 *
 * Two shapes qualify. A non-abstract base declares itself as the wildcard variant, so the IR
 * hands back a self-referencing default and the base doubles as its own carrier. An abstract
 * base never gets that default (see `TypeNode.retrievePolymorphicTypes`), but when its
 * discriminator is open the unknown values still have to land somewhere. TypeScript emits
 * `abstract class` for those, so `new Base()` is a compile error and a dedicated concrete
 * subclass carries them instead. Closed dispatches absorb nothing.
 *
 * This mirrors `absorbsUnknownIntoBase` in the Go emitter; the predicate is deliberately
 * identical so the two backends agree on which schemas are open.
 */
function absorbsUnknownValues(dispatch: PolymorphicDispatchDecl | null | undefined): boolean {
  if (!dispatch) {
    return false;
  }
  if (dispatch.defaultVariant) {
    return dispatch.defaultVariant.isSelfReference;
  }
  return !isClosedPolymorphicDispatch(dispatch);
}

/**
 * An abstract base with an open discriminator needs a concrete carrier, because the base
 * itself cannot be instantiated. Non-abstract bases carry unknown values themselves.
 */
function needsUnknownCarrier(type: TypeDecl): boolean {
  const dispatch = type.polymorphicDispatch;
  if (!dispatch || !type.isAbstract) {
    return false;
  }
  return !dispatch.defaultVariant && !isClosedPolymorphicDispatch(dispatch);
}

function unknownCarrierName(parentName: string): string {
  return `Unknown${parentName}`;
}

function emitPolymorphicDispatch(
  parentName: string,
  dispatch: PolymorphicDispatchDecl,
  lines: string[],
  carrier?: string,
): void {
  const isClosed = isClosedPolymorphicDispatch(dispatch);
  lines.push(`  private static loadKind(data: Record<string, unknown>, context?: LoadContext): ${parentName} {`);
  lines.push(`    const discriminatorValue = data["${dispatch.discriminatorField}"];`);
  // A blank discriminator is not a variant selector — it is the absence of a kind. Routing it
  // here (rather than into the wildcard/default arm) reuses this backend's existing
  // missing-discriminator behaviour instead of fabricating a wildcard instance.
  lines.push('    if (discriminatorValue !== undefined && discriminatorValue !== null && String(discriminatorValue) !== "") {');
  lines.push("      const discriminator = String(discriminatorValue);");
  lines.push("      switch (discriminator) {");

  for (const v of dispatch.variants) {
    lines.push(`        case "${v.value}":`);
    lines.push(`          return ${v.typeName.name}.load(data, context);`);
  }

  // Default handling
  if (dispatch.defaultVariant) {
    lines.push("        default:");
    if (dispatch.defaultVariant.isSelfReference) {
      lines.push(`          return new ${parentName}();`);
    } else {
      lines.push(`          return ${dispatch.defaultVariant.typeName.name}.load(data, context);`);
    }
  } else if (carrier) {
    lines.push("        default:");
    lines.push(`          return ${carrier}.load(data, context);`);
  } else {
    lines.push("        default:");
    lines.push(`          throw new Error(\`Unknown ${parentName} discriminator field '${dispatch.discriminatorField}' value: \${discriminator}\`);`);
  }

  lines.push("      }");
  lines.push("    }");

  // Missing discriminator
  if (carrier) {
    // Matches the Go backend, which absorbs a missing discriminator into the same
    // carrier it uses for an unrecognized one. No vector covers this case; the
    // choice is made for cross-backend consistency, not from a stated requirement.
    lines.push(`    return ${carrier}.load(data, context);`);
  } else if (isClosed || dispatch.isAbstract) {
    lines.push(`    throw new Error("Missing ${parentName} discriminator property: '${dispatch.discriminatorField}'");`);
  } else {
    lines.push(`    return new ${parentName}();`);
  }

  lines.push("  }");
  lines.push("");
}

// ============================================================================
// Collection helpers (loadX / saveX)
// ============================================================================

function emitCollectionLoadHelper(parentName: string, helper: CollectionHelperDecl, lines: string[]): void {
  const methodName = `load${capitalize(helper.propertyName)}`;
  const elemName = helper.elementTypeName.name;
  const shorthandField = entryShorthandTarget(helper, "kind");

  lines.push(`  static ${methodName}(data: Record<string, unknown>[] | unknown[], context?: LoadContext): ${elemName}[] {`);
  lines.push(`    context ??= new LoadContext({ path: "${helper.propertyName}" });`);
  lines.push("    if (!Array.isArray(data)) {");
  lines.push(`      const result: ${elemName}[] = [];`);
  lines.push("      for (const [k, v] of Object.entries(data)) {");
  lines.push("        if (Array.isArray(v)) {");
  lines.push('          throw new TypeError(context.at(k).path + ": invalid named collection entry category array");');
  lines.push("        }");
  lines.push("        if (typeof v === \"object\" && v !== null && !Array.isArray(v)) {");
  lines.push(`          result.push(${elemName}.load({ name: k, ...(v as Record<string, unknown>) }, context.at(k)));`);
  lines.push("        } else {");
  emitTsEntryShorthandArms(helper, shorthandField, elemName, lines);
  lines.push("        }");
  lines.push("      }");
  lines.push("      return result;");
  lines.push("    }");
  lines.push(`    return data.map((item, index) => ${elemName}.load(item as Record<string, unknown>, context.atIndex(index)));`);
  lines.push("  }");
  lines.push("");
}

/**
 * Emit the immediate-scalar branch of a name-keyed collection entry.
 *
 * With `@entryShorthand` declared, each `@coerce` scalar type contributes an arm
 * that applies that coercion's constant assignments (typically the discriminator)
 * and routes the raw scalar to the declared value field. Without it, this falls
 * back to the historical single-field assignment so existing schemas are unchanged.
 */
function emitTsEntryShorthandArms(
  helper: CollectionHelperDecl,
  shorthandField: string,
  elemName: string,
  lines: string[],
): void {
  const shorthand = helper.entryShorthand;
  const load = (expr: string) =>
    lines.push(`          result.push(${elemName}.load(${expr}, context.at(k)));`);

  if (!shorthand || shorthand.cases.length === 0) {
    load(`{ name: k, "${shorthandField}": v }`);
    return;
  }

  lines.push("          let shorthand: Record<string, unknown>;");
  let first = true;
  for (const entryCase of orderedEntryShorthandCases(shorthand.cases)) {
    const check = tsScalarValueCheck(entryCase.scalarType);
    if (!check) continue;
    const fields = entryCase.assignments
      .map(a => `"${a.fieldName}": ${JSON.stringify(a.literalValue)}`)
      .concat(`"${shorthand.valueField}": v`)
      .join(", ");
    lines.push(`          ${first ? "if" : "} else if"} (${check}) {`);
    lines.push(`            shorthand = { ${fields} };`);
    first = false;
  }
  lines.push("          } else {");
  lines.push(`            shorthand = { "${shorthand.valueField}": v };`);
  lines.push("          }");
  load("{ name: k, ...shorthand }");
}

/**
 * Runtime predicate recognising a decoded JSON token of the given TypeSpec scalar.
 *
 * The integral check is narrower than the fractional one, which is sound only
 * because `orderedEntryShorthandCases` guarantees integral arms are emitted first.
 */
function tsScalarValueCheck(scalarType: string): string | null {
  switch (scalarRuntimeKind(scalarType)) {
    case "integral": return 'typeof v === "number" && Number.isInteger(v)';
    case "fractional": return 'typeof v === "number"';
    case "string": return 'typeof v === "string"';
    case "boolean": return 'typeof v === "boolean"';
    default: return null;
  }
}

function emitCollectionSaveHelper(parentName: string, helper: CollectionHelperDecl, lines: string[]): void {
  const loadMethodName = `save${capitalize(helper.propertyName)}`;
  const elemName = helper.elementTypeName.name;

  lines.push(`  static ${loadMethodName}(items: ${elemName}[], context?: SaveContext): Record<string, unknown>[] | Record<string, unknown> {`);
  lines.push("    if (!context) {");
  lines.push("      context = new SaveContext();");
  lines.push("    }");

  if (helper.hasNameProperty) {
    lines.push("");
    lines.push("    const serialized = items.map(item => ({ ...item.save(context) } as Record<string, unknown>));");
    lines.push("    for (const itemData of serialized) {");
    lines.push('      if (itemData["name"] === "") delete itemData["name"];');
    lines.push("    }");
    lines.push("");
    lines.push('    if (context.collectionFormat === "array") {');
    lines.push("      return serialized;");
    lines.push("    }");
    lines.push("");
    lines.push("    const names = new Set<string>();");
    lines.push("    for (const itemData of serialized) {");
    lines.push('      const name = itemData["name"];');
    lines.push('      if (typeof name !== "string" || name.length === 0 || names.has(name)) return serialized;');
    lines.push("      names.add(name);");
    lines.push("    }");
    lines.push("");
    lines.push("    // Object format: use name as key");
    lines.push("    const result: Record<string, unknown> = {};");
    lines.push("    for (let index = 0; index < items.length; index++) {");
    lines.push("      const item = items[index];");
    lines.push("      const itemData = serialized[index];");
    lines.push('      const name = itemData["name"] as string;');
    lines.push('      delete itemData["name"];');
    lines.push("      // Check if we can use shorthand (only primary property set)");
    lines.push(`      const shorthand = (item.constructor as typeof ${elemName}).shorthandProperty;`);
    lines.push("      if (context.useShorthand && shorthand && Object.keys(itemData).length === 1 && shorthand in itemData) {");
    lines.push("        result[name] = itemData[shorthand];");
    lines.push("        continue;");
    lines.push("      }");
    lines.push("      result[name] = itemData;");
    lines.push("    }");
    lines.push("    return result;");
  } else {
    lines.push("");
    lines.push("    // This type doesn't have a 'name' property, so always use array format");
    lines.push("    return items.map(item => item.save(context));");
  }

  lines.push("  }");
  lines.push("");
}

// ============================================================================
// save() method
// ============================================================================

function emitSaveMethod(type: TypeDecl, lines: string[]): void {
  const name = type.typeName.name;

  lines.push("  save(context?: SaveContext): Record<string, unknown> {");
  lines.push("    let obj: this = this;");
  lines.push("    if (context) {");
  lines.push(`      obj = context.processObject(obj) as this;`);
  lines.push("    }");
  lines.push("");

  if (type.save.hasBase) {
    lines.push("    // Start with parent class properties");
    lines.push("    const result = super.save(context);");
  } else if (absorbsUnknownValues(type.polymorphicDispatch)) {
    lines.push(`    const result = ${name}.cloneRawValue(obj.raw) as Record<string, unknown>;`);
  } else {
    lines.push("    const result: Record<string, unknown> = {};");
  }

  lines.push("");

  // Per-property save assignments
  for (const a of type.save.assignments) {
    if (a.isOptional) {
      lines.push(`    if (obj.${a.fieldName} !== undefined && obj.${a.fieldName} !== null) {`);
      lines.push(`      ${emitSaveAssignment(a)}`);
      lines.push("    }");
    } else {
      lines.push(`    if (obj.${a.fieldName} !== undefined && obj.${a.fieldName} !== null) {`);
      lines.push(`      ${emitSaveAssignment(a)}`);
      lines.push("    }");
    }
  }

  // Context post-processing (only for root types without base)
  if (!type.save.hasBase) {
    lines.push("");
    lines.push("    if (context) {");
    lines.push("      return context.processDict(result);");
    lines.push("    }");
  }

  lines.push("    return result;");
  lines.push("  }");
  lines.push("");
}

function emitSaveAssignment(a: SaveAssignment): string {
  const cat = a.category;
  switch (cat.kind) {
    case "scalar":
    case "dict":
    case "collection_scalar":
      if (cat.kind === "dict" && cat.valueType && cat.valueType !== "unknown" && !TYPE_MAP[cat.valueType]) {
        return `result["${a.targetName}"] = Object.fromEntries(Object.entries(obj.${a.fieldName}).map(([key, value]) => [key, value.save(context)]));`;
      }
      return `result["${a.targetName}"] = obj.${a.fieldName};`;
    case "collection_complex":
      return `result["${a.targetName}"] = ${a.parentTypeName}.save${capitalize(a.fieldName)}(obj.${a.fieldName}, context);`;
    case "complex":
      return `result["${a.targetName}"] = obj.${a.fieldName}.save(context);`;
  }
}

// ============================================================================
// toWire() method
// ============================================================================

function emitToWireMethod(type: TypeDecl, lines: string[]): void {
  const wire = type.wire!;

  lines.push("  toWire(provider: string): Record<string, unknown> {");
  lines.push("    const data = this.save();");
  lines.push("    const result: Record<string, unknown> = {};");
  lines.push("    const wireMap: Record<string, Record<string, string>> = {");

  for (const mapping of wire.mappings) {
    const entries = Object.entries(mapping.wireNames)
      .map(([prov, wireName]) => `"${prov}": "${wireName}"`)
      .join(", ");
    lines.push(`      "${mapping.fieldName}": { ${entries} },`);
  }

  lines.push("    };");
  lines.push("    for (const [key, value] of Object.entries(data)) {");
  lines.push("      const mapping = wireMap[key];");
  lines.push("      if (mapping?.[provider]) {");
  lines.push("        result[mapping[provider]] = value;");
  lines.push("      }");
  lines.push("    }");
  lines.push("    return result;");
  lines.push("  }");
  lines.push("");
}

// ============================================================================
// toYaml() / toJson()
// ============================================================================

function emitToYaml(name: string, lines: string[]): void {
  lines.push("  toYaml(context?: SaveContext): string {");
  lines.push("    context = context ?? new SaveContext();");
  lines.push("    return context.toYaml(this.save(context));");
  lines.push("  }");
  lines.push("");
}

function emitToJson(name: string, lines: string[]): void {
  lines.push("  toJson(context?: SaveContext, indent: number = 2): string {");
  lines.push("    context = context ?? new SaveContext();");
  lines.push("    return context.toJson(this.save(context), indent);");
  lines.push("  }");
  lines.push("");
}

// ============================================================================
// fromJson() / fromYaml()
// ============================================================================

function emitFromJson(name: string, type: TypeDecl, lines: string[]): void {
  lines.push(`  static fromJson(json: string, context?: LoadContext): ${name} {`);
  lines.push("    const data = JSON.parse(json);");

  if (type.load.coercions.length > 0) {
    // Pass raw parsed value directly to load() — it handles typeof coercions
    lines.push(`    return ${name}.load(data as Record<string, unknown>, context);`);
  } else {
    lines.push(`    return ${name}.load(data as Record<string, unknown>, context);`);
  }

  lines.push("  }");
  lines.push("");
}

function emitFromYaml(name: string, type: TypeDecl, lines: string[]): void {
  lines.push(`  static fromYaml(yaml: string, context?: LoadContext): ${name} {`);
  lines.push('    const { parse } = require("yaml");');
  lines.push("    const data = parse(yaml);");

  if (type.load.coercions.length > 0) {
    // Pass raw parsed value directly to load() — it handles typeof coercions
    lines.push(`    return ${name}.load(data as Record<string, unknown>, context);`);
  } else {
    lines.push(`    return ${name}.load(data as Record<string, unknown>, context);`);
  }

  lines.push("  }");
  lines.push("");
}

// ============================================================================
// Factory methods
// ============================================================================

function emitFactory(parentName: string, factory: FactoryDecl, visitor: ExprVisitor, lines: string[]): void {
  const params = Object.entries(factory.params)
    .map(([pName, pType]) => `${pName}: ${paramType(pType)}`)
    .join(", ");

  lines.push(`  static ${factory.name}(${params}): ${parentName} {`);
  lines.push(`    return ${visitor.visitExpr(factory.body)};`);
  lines.push("  }");
  lines.push("");
}

// ============================================================================
// Helpers
// ============================================================================

/** Capitalize first letter (camelCase → PascalCase for method names). */
function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
