/**
 * TypeScript test file emitter — BaseTestContext → vitest source code.
 *
 * Replaces the Nunjucks templates:
 *   - `test.ts.njk`   → emitTypeScriptTest()
 *   - `_macros.njk`    → factoryParamTestValue() (test-specific macro)
 *
 * The emitter produces vitest `describe`/`it` blocks for:
 *   - Construction (default + partial)
 *   - JSON serialization (load + round-trip per example)
 *   - YAML serialization (load + round-trip per example)
 *   - Alternate representations (scalar coercions)
 *   - Factory methods
 *   - Load/save (dictionary round-trip)
 */

import { BaseTestContext } from "../../ir/ast.js";

// ============================================================================
// Macro replacements
// ============================================================================

/**
 * Map a factory parameter type string to a TypeScript test value literal.
 * Replaces the `factoryParamTestValue` macro from `_macros.njk`.
 */
function factoryParamTestValue(typeStr: string): string {
  switch (typeStr) {
    case "string":
      return '"test"';
    case "boolean":
      return "true";
    case "integer":
    case "int32":
    case "int64":
      return "42";
    case "float":
    case "float64":
    case "float32":
      return "3.14";
    case "unknown":
    default:
      return '"test"';
  }
}

/**
 * Render name in PascalCase (used by coercion test validation keys).
 */
function renderName(name: string): string {
  const pascal = name.replace(/_([a-z])/g, (_, letter: string) =>
    letter.toUpperCase(),
  );
  return pascal.charAt(0).toUpperCase() + pascal.slice(1);
}

// ============================================================================
// Main entry point
// ============================================================================

/**
 * Emit a vitest test file for a TypeNode.
 */
export function emitTypeScriptTest(
  ctx: BaseTestContext & { importPath: string; namespace: string },
): string {
  const { node, isAbstract, examples, coercions, factories, importPath } = ctx;
  const typeName = node.typeName.name;

  const lines: string[] = [];
  lines.push("// Copyright (c) Microsoft. All rights reserved.");
  lines.push(
    "// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.",
  );
  lines.push("");
  lines.push(`import { ${typeName} } from "${importPath}";`);
  lines.push("");
  lines.push(`describe("${typeName}", () => {`);
  if (!node.isAbstract) {
    lines.push(`  describe("construction", () => {`);
    lines.push(`    it("should create a new instance with defaults", () => {`);
    lines.push(`      const instance = new ${typeName}();`);
    lines.push(`      expect(instance).toBeDefined();`);
    lines.push(`    });`);
    lines.push("");
    lines.push(
      `    it("should create a new instance with partial initialization", () => {`,
    );
    lines.push(`      const instance = new ${typeName}({});`);
    lines.push(`      expect(instance).toBeDefined();`);
    lines.push(`    });`);
    lines.push(`  });`);
  }

  // JSON serialization
  if (examples.length > 0) {
    lines.push("");
    lines.push(`  describe("JSON serialization", () => {`);
    for (let i = 0; i < examples.length; i++) {
      const example = examples[i];
      const exampleNum = i + 1;
      lines.push(
        `    it("should load from JSON - example ${exampleNum}", () => {`,
      );
      lines.push("      const json = `" + example.json.join("\\n") + "`;");
      lines.push(`      const instance = ${typeName}.fromJson(json);`);
      lines.push(`      expect(instance).toBeDefined();`);
      for (const val of example.validations) {
        lines.push(
          `      expect(instance.${val.key}).toEqual(${val.delimiter}${val.value}${val.delimiter});`,
        );
      }
      lines.push(`    });`);
      lines.push("");
      lines.push(
        `    it("should round-trip JSON - example ${exampleNum}", () => {`,
      );
      lines.push("      const json = `" + example.json.join("\\n") + "`;");
      lines.push(`      const instance = ${typeName}.fromJson(json);`);
      lines.push(`      const output = instance.toJson();`);
      lines.push(`      const reloaded = ${typeName}.fromJson(output);`);
      if (example.validations.length === 0) {
        lines.push(`      expect(reloaded).toBeDefined();`);
      }
      for (const val of example.validations) {
        lines.push(
          `      expect(reloaded.${val.key}).toEqual(instance.${val.key});`,
        );
      }
      lines.push(`    });`);
    }
    lines.push(`  });`);

    // YAML serialization
    lines.push("");
    lines.push(`  describe("YAML serialization", () => {`);
    for (let i = 0; i < examples.length; i++) {
      const example = examples[i];
      const exampleNum = i + 1;
      lines.push(
        `    it("should load from YAML - example ${exampleNum}", () => {`,
      );
      lines.push("      const yaml = `" + example.yaml.join("\\n") + "`;");
      lines.push(`      const instance = ${typeName}.fromYaml(yaml);`);
      lines.push(`      expect(instance).toBeDefined();`);
      for (const val of example.validations) {
        lines.push(
          `      expect(instance.${val.key}).toEqual(${val.delimiter}${val.value}${val.delimiter});`,
        );
      }
      lines.push(`    });`);
      lines.push("");
      lines.push(
        `    it("should round-trip YAML - example ${exampleNum}", () => {`,
      );
      lines.push("      const yaml = `" + example.yaml.join("\\n") + "`;");
      lines.push(`      const instance = ${typeName}.fromYaml(yaml);`);
      lines.push(`      const output = instance.toYaml();`);
      lines.push(`      const reloaded = ${typeName}.fromYaml(output);`);
      if (example.validations.length === 0) {
        lines.push(`      expect(reloaded).toBeDefined();`);
      }
      for (const val of example.validations) {
        lines.push(
          `      expect(reloaded.${val.key}).toEqual(instance.${val.key});`,
        );
      }
      lines.push(`    });`);
    }
    lines.push(`  });`);
  }

  // Alternate representations (coercions)
  if (coercions.length > 0) {
    lines.push("");
    lines.push(`  describe("alternate representations", () => {`);
    for (const alt of coercions) {
      lines.push(
        `    it("should handle ${alt.title} alternate representation", () => {`,
      );
      lines.push(`      const value = ${alt.value};`);
      lines.push(`      const json = JSON.stringify(value);`);
      lines.push(`      const instance = ${typeName}.fromJson(json);`);
      lines.push(`      expect(instance).toBeDefined();`);
      for (const val of alt.validations) {
        const coercionKey = renderName(val.key)
          .toLowerCase()
          .replace(/\./g, "");
        lines.push(
          `      expect(instance.${coercionKey}).toEqual(${val.delimiter}${val.value}${val.delimiter});`,
        );
      }
      lines.push(`    });`);
    }
    lines.push(`  });`);
  }

  // Factory methods
  if (factories.length > 0) {
    lines.push("");
    lines.push(`  describe("factory methods", () => {`);
    for (const factory of factories) {
      const paramValues = Object.values(factory.params)
        .map((pType) => factoryParamTestValue(pType))
        .join(", ");
      const paramLiterals = new Map<string, string>();
      for (const [pName, pType] of Object.entries(factory.params)) {
        const rendered = factoryParamTestValue(pType);
        paramLiterals.set(
          pName,
          rendered.length > 1 &&
            rendered.startsWith('"') &&
            rendered.endsWith('"')
            ? rendered.slice(1, -1)
            : rendered,
        );
      }
      const substituteParams = (raw: string): string =>
        raw.replace(
          /\{(\w+)\}/g,
          (match, param) => paramLiterals.get(param) ?? match,
        );

      lines.push(
        `    it("should create instance via ${factory.name}() factory", () => {`,
      );
      lines.push(
        `      const instance = ${typeName}.${factory.name}(${paramValues});`,
      );
      lines.push(`      expect(instance).toBeDefined();`);
      lines.push(`      expect(instance).toBeInstanceOf(${typeName});`);
      for (const [propName, rawValue] of Object.entries(factory.sets)) {
        const value =
          typeof rawValue === "string" ? substituteParams(rawValue) : rawValue;
        if (value === true) {
          lines.push(`      expect(instance.${propName}).toBe(true);`);
        } else if (value === false) {
          lines.push(`      expect(instance.${propName}).toBe(false);`);
        } else if (typeof value === "number") {
          lines.push(`      expect(instance.${propName}).toBe(${value});`);
        } else if (typeof value === "string") {
          lines.push(`      expect(instance.${propName}).toBe("${value}");`);
        }
      }
      lines.push(`    });`);
    }
    lines.push(`  });`);
  }

  // Load and save
  lines.push("");
  if (!(isAbstract && node.isAbstract)) {
    lines.push(`  describe("load and save", () => {`);
    if (!isAbstract && examples.length > 0) {
      lines.push(`    it("should load from dictionary", () => {`);
      // Reuse the payload the sibling JSON/YAML tests load. An empty object
      // fails required-field validation for any type that has one, so a type
      // with no example has no dictionary payload worth asserting on.
      lines.push(
        "      const data = JSON.parse(`" +
          examples[0].json.join("\\n") +
          "`) as Record<string, unknown>;",
      );
      lines.push(`      const instance = ${typeName}.load(data);`);
      lines.push(`      expect(instance).toBeDefined();`);
      lines.push(`    });`);
    }
    lines.push("");
    if (!node.isAbstract) {
      lines.push(`    it("should save to dictionary", () => {`);
      lines.push(`      const instance = new ${typeName}();`);
      lines.push(`      const data = instance.save();`);
      lines.push(`      expect(data).toBeDefined();`);
      lines.push(`      expect(typeof data).toBe("object");`);
      lines.push(`    });`);
    }
    lines.push(`  });`);
  }
  // A file that declares no test cases is not a passing test file — vitest fails it
  // outright. An abstract type with no `@sample` reaches this state: it cannot be
  // constructed, and there is no example payload to load. Assert the one thing that
  // is still meaningful, that the type is exported and reachable, rather than
  // emitting an empty `describe`.
  if (!lines.some((line) => line.trimStart().startsWith("it("))) {
    lines.push(`  it("should be defined", () => {`);
    lines.push(`    expect(${typeName}).toBeDefined();`);
    lines.push(`  });`);
  }
  lines.push("});");
  lines.push("");

  return lines.join("\n");
}
