import type {
  TransportBinding,
  TransportContract,
  TransportOperation,
} from "../../ir/transport.js";
import {
  successOrFallbackBodyResponses,
  transportBindingsByKind,
} from "../../ir/transport.js";
import type { TypeNode } from "../../ir/ast.js";
import type { CallableVector } from "../../ir/vector.js";

export function emitTypeScriptFetchClient(
  contracts: TransportContract[],
  modelTypes: Set<string>,
): string {
  const lines: string[] = [];
  const imports = collectClientModelImports(contracts, modelTypes);

  lines.push("// Copyright (c) Microsoft. All rights reserved.");
  lines.push(
    "// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.",
  );
  lines.push("");
  if (imports.length > 0) {
    lines.push(`import { ${imports.join(", ")} } from "./index";`);
    lines.push("");
  }
  lines.push("export interface TypraFetchRequest {");
  lines.push("  method: string;");
  lines.push("  url: string;");
  lines.push("  headers?: Record<string, string>;");
  lines.push("  cookies?: Record<string, string>;");
  lines.push("  auth?: TypraAuthRequirement;");
  lines.push("  body?: unknown;");
  lines.push("}");
  lines.push("");
  lines.push("export interface TypraAuthRequirement {");
  lines.push("  options: TypraAuthOption[];");
  lines.push("}");
  lines.push("");
  lines.push("export interface TypraAuthOption {");
  lines.push("  schemes: TypraAuthScheme[];");
  lines.push("}");
  lines.push("");
  lines.push("export interface TypraAuthScheme {");
  lines.push("  id: string;");
  lines.push("  type: string;");
  lines.push("  description?: string;");
  lines.push("  scheme?: string;");
  lines.push('  in?: "header" | "query" | "cookie";');
  lines.push("  name?: string;");
  lines.push("  scopes?: string[];");
  lines.push("  flows?: TypraOAuth2Flow[];");
  lines.push("  openIdConnectUrl?: string;");
  lines.push("}");
  lines.push("");
  lines.push("export interface TypraOAuth2Flow {");
  lines.push("  type: string;");
  lines.push("  authorizationUrl?: string;");
  lines.push("  tokenUrl?: string;");
  lines.push("  refreshUrl?: string;");
  lines.push("  scopes: string[];");
  lines.push("}");
  lines.push("");
  lines.push("export interface TypraFetchResponse {");
  lines.push("  status: number;");
  lines.push("  headers?: Record<string, string>;");
  lines.push("  body?: unknown;");
  lines.push("}");
  lines.push("");
  lines.push("export type TypraFetchTransport = (");
  lines.push("  request: TypraFetchRequest,");
  lines.push(") => Promise<TypraFetchResponse>;");
  lines.push("");
  lines.push("export interface TypraClientOptions {");
  lines.push("  baseUrl: string;");
  lines.push("  transport: TypraFetchTransport;");
  lines.push("}");
  lines.push("");
  lines.push("function joinUrl(baseUrl: string, path: string): string {");
  lines.push('  return `${baseUrl.replace(/\\/+$/, "")}/${path.replace(/^\\/+/, "")}`;');
  lines.push("}");
  lines.push("");
  lines.push(
    "function serializeValue(value: unknown): string | undefined {",
  );
  lines.push("  if (value === undefined || value === null) return undefined;");
  lines.push("  if (value instanceof Date) return value.toISOString();");
  lines.push("  return String(value);");
  lines.push("}");
  lines.push("");
  lines.push("function serializeBody(value: unknown): unknown {");
  lines.push("  if (");
  lines.push('    typeof value === "object" &&');
  lines.push("    value !== null &&");
  lines.push('    "save" in value &&');
  lines.push('    typeof value.save === "function"');
  lines.push("  ) {");
  lines.push("    return value.save();");
  lines.push("  }");
  lines.push("  return value;");
  lines.push("}");
  lines.push("");
  lines.push("function escapeRegExp(value: string): string {");
  lines.push('  return value.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&");');
  lines.push("}");
  lines.push("");
  lines.push("function pathParameterPattern(name: string): RegExp {");
  lines.push(
    '  return new RegExp(`\\\\{[+#./;?&]?${escapeRegExp(name)}(?:\\\\*|:\\\\d+)?\\\\}`, "g");',
  );
  lines.push("}");
  lines.push("");
  lines.push("function isSuccessStatus(status: number): boolean {");
  lines.push("  return status >= 200 && status < 300;");
  lines.push("}");
  lines.push("");
  lines.push("function matchesStatusCode(status: number, code: string): boolean {");
  lines.push('  if (code === "*") return true;');
  lines.push('  if (/^\\d+$/.test(code)) return Number(code) === status;');
  lines.push('  const range = /^(\\d+)-(\\d+)$/.exec(code);');
  lines.push("  if (!range) return false;");
  lines.push("  return status >= Number(range[1]) && status <= Number(range[2]);");
  lines.push("}");
  lines.push("");
  lines.push("export class TypraFetchResponseError extends Error {");
  lines.push("  readonly status: number;");
  lines.push("  readonly body: unknown;");
  lines.push("");
  lines.push("  constructor(response: TypraFetchResponse) {");
  lines.push("    super(`Unexpected response status ${response.status}`);");
  lines.push('    this.name = "TypraFetchResponseError";');
  lines.push("    this.status = response.status;");
  lines.push("    this.body = response.body;");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  for (const contract of contracts) {
    emitContractClient(contract, modelTypes, lines);
  }

  return `${lines.join("\n")}\n`;
}

function emitContractClient(
  contract: TransportContract,
  modelTypes: Set<string>,
  lines: string[],
): void {
  lines.push(`export class ${contract.name}Client {`);
  lines.push("  private readonly baseUrl: string;");
  lines.push("  private readonly transport: TypraFetchTransport;");
  lines.push("");
  lines.push("  constructor(options: TypraClientOptions) {");
  lines.push("    this.baseUrl = options.baseUrl;");
  lines.push("    this.transport = options.transport;");
  lines.push("  }");
  lines.push("");
  for (const operation of contract.operations) {
    emitOperationClient(operation, modelTypes, lines);
    lines.push("");
  }
  lines.push("}");
  lines.push("");
}

function emitOperationClient(
  operation: TransportOperation,
  modelTypes: Set<string>,
  lines: string[],
): void {
  const inputType = operationInputType(operation);
  const resultType = operationResultType(operation, modelTypes);
  lines.push(
    `  async ${toCamelCase(operation.operation)}(input: ${inputType}): Promise<${resultType}> {`,
  );
  lines.push(`    let path = ${JSON.stringify(routePathTemplate(operation))};`);
  for (const binding of transportBindingsByKind(operation, "path")) {
    const property = propertyAccess(binding.name);
    lines.push(
      `    path = path.replace(pathParameterPattern(${JSON.stringify(binding.wireName)}), encodeURIComponent(serializeValue(input${property}) ?? ""));`,
    );
  }
  lines.push("    const query = new URLSearchParams();");
  for (const binding of transportBindingsByKind(operation, "query")) {
    const property = propertyAccess(binding.name);
    lines.push(`    {`);
    lines.push(`      const value = serializeValue(input${property});`);
    lines.push(
      `      if (value !== undefined) query.set(${JSON.stringify(binding.wireName)}, value);`,
    );
    lines.push(`    }`);
  }
  lines.push("    const queryText = query.toString();");
  lines.push("    if (queryText) path = `${path}?${queryText}`;");
  lines.push("    const headers: Record<string, string> = {};");
  for (const binding of transportBindingsByKind(operation, "header")) {
    const property = propertyAccess(binding.name);
    lines.push(`    {`);
    lines.push(`      const value = serializeValue(input${property});`);
    lines.push(
      `      if (value !== undefined) headers[${JSON.stringify(binding.wireName)}] = value;`,
    );
    lines.push(`    }`);
  }
  lines.push("    const cookies: Record<string, string> = {};");
  for (const binding of transportBindingsByKind(operation, "cookie")) {
    const property = propertyAccess(binding.name);
    lines.push(`    {`);
    lines.push(`      const value = serializeValue(input${property});`);
    lines.push(
      `      if (value !== undefined) cookies[${JSON.stringify(binding.wireName)}] = value;`,
    );
    lines.push(`    }`);
  }
  const body = operation.bindings.find((binding) => binding.kind === "body");
  if (body) {
    const property = propertyAccess(body.name);
    lines.push('    headers["Content-Type"] ??= "application/json";');
    lines.push(`    const body = serializeBody(input${property});`);
  } else {
    lines.push("    const body = undefined;");
  }
  lines.push("    const response = await this.transport({");
  lines.push(`      method: ${JSON.stringify(operation.verb.toUpperCase())},`);
  lines.push("      url: joinUrl(this.baseUrl, path),");
  lines.push("      headers,");
  lines.push("      cookies,");
  lines.push(
    `      auth: ${operation.auth ? renderTypeScriptLiteral(operation.auth, 6) : "undefined"},`,
  );
  lines.push("      body,");
  lines.push("    });");
  emitResponseReturn(operation, modelTypes, lines);
  lines.push("  }");
}

function operationInputType(operation: TransportOperation): string {
  if (operation.bindings.length === 0) return "Record<string, never>";
  const fields = operation.bindings.map((binding) => {
    const optional = binding.optional ? "?" : "";
    return `${binding.name}${optional}: ${typeScriptType(binding.type)}`;
  });
  return `{ ${fields.join("; ")} }`;
}

function operationResultType(
  operation: TransportOperation,
  modelTypes: Set<string>,
): string {
  const responseTypes = Array.from(
    new Set(
      successOrFallbackBodyResponses(operation).map((response) =>
        typeScriptType(response.body!, modelTypes),
      ),
    ),
  );
  const hasExplicitSuccess = operation.responses.some(
    (response) => response.kind === "success",
  );
  const hasVoidSuccess = operation.responses.some(
    (response) =>
      (response.kind === "success" ||
        (!hasExplicitSuccess && response.kind === "unknown")) &&
      (!response.body || response.body === "void"),
  );
  if (hasVoidSuccess) responseTypes.push("void");
  if (responseTypes.length === 0) return "void";
  return responseTypes.join(" | ");
}

function collectClientModelImports(
  contracts: TransportContract[],
  modelTypes: Set<string>,
): string[] {
  const imports = new Set<string>();
  for (const contract of contracts) {
    for (const operation of contract.operations) {
      for (const binding of operation.bindings) {
        if (modelTypes.has(binding.type)) imports.add(binding.type);
      }
      const responseBodies = successOrFallbackBodyResponses(operation);
      for (const response of operation.responses) {
        if (
          responseBodies.includes(response) &&
          response.body &&
          modelTypes.has(response.body)
        ) {
          imports.add(response.body);
        }
      }
    }
  }
  return Array.from(imports).sort();
}

function typeScriptType(type: string, modelTypes = new Set<string>()): string {
  if (modelTypes.has(type)) return type;
  switch (type) {
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "int32":
    case "int64":
    case "float32":
    case "float64":
    case "integer":
    case "numeric":
    case "number":
      return "number";
    case "void":
      return "void";
    default:
      return type;
  }
}

function emitResponseReturn(
  operation: TransportOperation,
  modelTypes: Set<string>,
  lines: string[],
): void {
  lines.push("    if (!isSuccessStatus(response.status)) {");
  lines.push("      throw new TypraFetchResponseError(response);");
  lines.push("    }");
  const successResponses = operation.responses.filter(
    (response) => response.kind === "success",
  );
  const fallbackResponses =
    successResponses.length === 0
      ? operation.responses.filter((response) => response.kind === "unknown")
      : [];
  for (const response of [...successResponses, ...fallbackResponses]) {
    const statusCheck = response.statusCodes
      .map((statusCode) => `matchesStatusCode(response.status, ${JSON.stringify(statusCode)})`)
      .join(" || ");
    lines.push(`    if (${statusCheck}) {`);
    if (!response.body || response.body === "void") {
      lines.push("      return undefined;");
    } else if (modelTypes.has(response.body)) {
      lines.push(
        `      return ${response.body}.load(response.body as Record<string, unknown>);`,
      );
    } else {
      lines.push(`      return response.body as ${typeScriptType(response.body, modelTypes)};`);
    }
    lines.push("    }");
  }
  lines.push("    throw new TypraFetchResponseError(response);");
}

function propertyAccess(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
    ? `.${name}`
    : `[${JSON.stringify(name)}]`;
}

function routePathTemplate(operation: TransportOperation): string {
  return operation.uriTemplate.replace(/\{\?[^}]+\}/g, "");
}

export function collectTransportModelTypes(nodes: TypeNode[]): Set<string> {
  return new Set(
    nodes.filter((node) => !node.isProtocol).map((node) => node.typeName.name),
  );
}

function toCamelCase(value: string): string {
  return value ? value.charAt(0).toLowerCase() + value.slice(1) : value;
}

export function emitTypeScriptFetchClientConformanceTest(
  contracts: TransportContract[],
  modelTypes: Set<string>,
  clientImportPath: string,
  modelImportPath: string,
): string {
  const lines: string[] = [];
  const vectors = collectTransportClientVectors(contracts);
  const clientNames = Array.from(
    new Set(vectors.map((entry) => `${entry.contract.name}Client`)),
  ).sort();
  const modelImports = collectConformanceTestModelImports(vectors, modelTypes);

  lines.push("// Copyright (c) Microsoft. All rights reserved.");
  lines.push(
    "// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.",
  );
  lines.push("");
  lines.push(
    `import { ${[...clientNames, "TypraFetchRequest", "TypraFetchResponseError"].join(", ")} } from "${clientImportPath}";`,
  );
  if (modelImports.length > 0) {
    lines.push(`import { ${modelImports.join(", ")} } from "${modelImportPath}";`);
  }
  lines.push("");
  lines.push("function saved(value: unknown): unknown {");
  lines.push("  return typeof value === \"object\" && value !== null && \"save\" in value && typeof value.save === \"function\"");
  lines.push("    ? value.save()");
  lines.push("    : value;");
  lines.push("}");
  lines.push("");
  lines.push('describe("transport fetch consumer conformance", () => {');
  for (const entry of vectors) {
    const testName = `${entry.contract.name}.${entry.operation.operation}:${entry.vector.name ?? "unnamed"}`;
    const clientName = `${entry.contract.name}Client`;
    const methodName = toCamelCase(entry.operation.operation);
    const input = vectorObject(entry.vector.input);
    const typedInput = typedInputExpression(
      entry.operation,
      input,
      modelTypes,
    );
    const expectedRequest = expectedRequestShape(entry.operation, input);
    const expectedBody = expectedBodyExpression(entry.operation, input, modelTypes);
    const successStatus =
      firstConcreteStatusCode(
        entry.operation.responses.find((response) => response.kind === "success")?.statusCodes ?? [],
      ) ?? 200;
    lines.push(`  it(${JSON.stringify(testName)}, async () => {`);
    lines.push("    let captured: TypraFetchRequest | undefined;");
    lines.push(
      `    const expectedRequest: TypraFetchRequest = ${renderTypeScriptLiteral(expectedRequest, 4)};`,
    );
    if (expectedBody) {
      lines.push(`    expectedRequest.body = ${expectedBody};`);
    }
    lines.push(`    const client = new ${clientName}({`);
    lines.push('      baseUrl: "https://example.test",');
    lines.push("      transport: async (request) => {");
    lines.push("        captured = request;");
    lines.push("        return {");
    lines.push(`          status: ${successStatus},`);
    lines.push(`          body: ${JSON.stringify(entry.vector.expected ?? null)},`);
    lines.push("        };");
    lines.push("      },");
    lines.push("    });");
    lines.push(`    const result = await client.${methodName}(${typedInput});`);
    lines.push("    expect(captured).toEqual(expectedRequest);");
    lines.push("    const observed = saved(result);");
    lines.push(`    expect(observed).toEqual(${JSON.stringify(entry.vector.expected ?? undefined)});`);
    lines.push("  });");
    const errorResponse = entry.operation.responses.find(
      (response) => response.kind === "error",
    );
    if (errorResponse) {
      const errorStatus = firstConcreteStatusCode(errorResponse.statusCodes) ?? 400;
      const errorBody = { error: "not-success" };
      lines.push("");
      lines.push(`  it(${JSON.stringify(`${testName}:non-success-response`)}, async () => {`);
      lines.push(`    const client = new ${clientName}({`);
      lines.push('      baseUrl: "https://example.test",');
      lines.push("      transport: async () => ({");
      lines.push(`        status: ${errorStatus},`);
      lines.push(`        body: ${JSON.stringify(errorBody)},`);
      lines.push("      }),");
      lines.push("    });");
      lines.push("    let error: unknown;");
      lines.push("    try {");
      lines.push(`      await client.${methodName}(${typedInput});`);
      lines.push("    } catch (caught) {");
      lines.push("      error = caught;");
      lines.push("    }");
      lines.push("    expect(error instanceof TypraFetchResponseError).toEqual(true);");
      lines.push("    expect((error as TypraFetchResponseError).status).toEqual(" + errorStatus + ");");
      lines.push(
        "    expect((error as TypraFetchResponseError).body).toEqual(" +
          JSON.stringify(errorBody) +
          ");",
      );
      lines.push("  });");
    }
  }
  lines.push("});");
  lines.push("");

  return `${lines.join("\n")}\n`;
}

function collectTransportClientVectors(contracts: TransportContract[]): Array<{
  contract: TransportContract;
  operation: TransportOperation;
  vector: CallableVector;
}> {
  return contracts.flatMap((contract) =>
    contract.operations.flatMap((operation) =>
      (operation.callable.vectors ?? [])
        .filter((vector) => vector.stage === "transport")
        .map((vector) => ({ contract, operation, vector })),
    ),
  );
}

function collectConformanceTestModelImports(
  vectors: Array<{
    operation: TransportOperation;
  }>,
  modelTypes: Set<string>,
): string[] {
  const imports = new Set<string>();
  for (const { operation } of vectors) {
    for (const binding of operation.bindings) {
      if (binding.kind === "body" && modelTypes.has(binding.type)) {
        imports.add(binding.type);
      }
    }
  }
  return Array.from(imports).sort();
}

function typedInputExpression(
  operation: TransportOperation,
  input: Record<string, unknown>,
  modelTypes: Set<string>,
): string {
  const fields = operation.bindings.map((binding) => {
    const value = input[binding.name];
    if (binding.kind === "body" && modelTypes.has(binding.type)) {
      return `${binding.name}: ${binding.type}.load(${JSON.stringify(value)})`;
    }
    return `${binding.name}: ${JSON.stringify(value)}`;
  });
  return `{ ${fields.join(", ")} }`;
}

function expectedRequestShape(
  operation: TransportOperation,
  input: Record<string, unknown>,
): {
  method: string;
  url: string;
  headers: Record<string, string>;
  cookies: Record<string, string>;
  auth?: unknown;
  body?: unknown;
} {
  let path = routePathTemplate(operation);
  for (const binding of transportBindingsByKind(operation, "path")) {
    path = path.replace(
      new RegExp(`\\{[+#./;?&]?${escapeRegExpForEmitter(binding.wireName)}(?:\\*|:\\d+)?\\}`, "g"),
      encodeURIComponent(String(input[binding.name] ?? "")),
    );
  }
  const query = new URLSearchParams();
  for (const binding of transportBindingsByKind(operation, "query")) {
    const value = input[binding.name];
    if (value !== undefined && value !== null) {
      query.set(binding.wireName, String(value));
    }
  }
  const queryText = query.toString();
  if (queryText) path = `${path}?${queryText}`;

  const headers: Record<string, string> = {};
  for (const binding of transportBindingsByKind(operation, "header")) {
    const value = input[binding.name];
    if (value !== undefined && value !== null) {
      headers[binding.wireName] = String(value);
    }
  }
  const cookies: Record<string, string> = {};
  for (const binding of transportBindingsByKind(operation, "cookie")) {
    const value = input[binding.name];
    if (value !== undefined && value !== null) {
      cookies[binding.wireName] = String(value);
    }
  }

  const request: {
    method: string;
    url: string;
    headers: Record<string, string>;
    cookies: Record<string, string>;
    auth?: unknown;
    body?: unknown;
  } = {
    method: operation.verb.toUpperCase(),
    url: `https://example.test${path}`,
    headers,
    cookies,
    auth: operation.auth,
    body: undefined,
  };
  const body = operation.bindings.find((binding) => binding.kind === "body");
  if (body) {
    request.headers["Content-Type"] = "application/json";
    request.body = input[body.name];
  }
  return request;
}

function expectedBodyExpression(
  operation: TransportOperation,
  input: Record<string, unknown>,
  modelTypes: Set<string>,
): string | undefined {
  const body = operation.bindings.find((binding) => binding.kind === "body");
  if (!body || !modelTypes.has(body.type)) return undefined;
  return `${body.type}.load(${JSON.stringify(input[body.name])}).save()`;
}

function vectorObject(value: unknown): Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function escapeRegExpForEmitter(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function firstConcreteStatusCode(statusCodes: readonly string[]): number | undefined {
  for (const statusCode of statusCodes) {
    if (/^\d+$/.test(statusCode)) return Number(statusCode);
    const range = /^(\d+)-\d+$/.exec(statusCode);
    if (range) return Number(range[1]);
  }
  return undefined;
}

function renderTypeScriptLiteral(value: unknown, indentSize = 0): string {
  if (value === undefined) return "undefined";
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) {
    return `[${value.map((item) => renderTypeScriptLiteral(item, indentSize)).join(", ")}]`;
  }
  const entries = Object.entries(value as Record<string, unknown>);
  if (entries.length === 0) return "{}";
  const current = " ".repeat(indentSize);
  const next = " ".repeat(indentSize + 2);
  return [
    "{",
    ...entries.map(
      ([key, entryValue]) =>
        `${next}${JSON.stringify(key)}: ${renderTypeScriptLiteral(entryValue, indentSize + 2)},`,
    ),
    `${current}}`,
  ].join("\n");
}
