import type {
  TransportBinding,
  TransportContract,
  TransportOperation,
} from "../../ir/transport.js";
import type { TypeNode } from "../../ir/ast.js";
import type { CallableVector } from "../../ir/vector.js";

export function emitTypeScriptFetchClient(
  contracts: TransportContract[],
  modelTypes: Set<string>,
): string {
  const lines: string[] = [];
  const imports = collectClientModelImports(contracts, modelTypes);

  lines.push("// Copyright (c) Microsoft. All rights reserved.");
  lines.push(
    "// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.",
  );
  lines.push("");
  if (imports.length > 0) {
    lines.push(`import { ${imports.join(", ")} } from "./index";`);
    lines.push("");
  }
  lines.push("export interface TypraFetchRequest {");
  lines.push("  method: string;");
  lines.push("  url: string;");
  lines.push("  headers?: Record<string, string>;");
  lines.push("  body?: unknown;");
  lines.push("}");
  lines.push("");
  lines.push("export interface TypraFetchResponse {");
  lines.push("  status: number;");
  lines.push("  headers?: Record<string, string>;");
  lines.push("  body?: unknown;");
  lines.push("}");
  lines.push("");
  lines.push("export type TypraFetchTransport = (");
  lines.push("  request: TypraFetchRequest,");
  lines.push(") => Promise<TypraFetchResponse>;");
  lines.push("");
  lines.push("export interface TypraClientOptions {");
  lines.push("  baseUrl: string;");
  lines.push("  transport: TypraFetchTransport;");
  lines.push("}");
  lines.push("");
  lines.push("function joinUrl(baseUrl: string, path: string): string {");
  lines.push('  return `${baseUrl.replace(/\\/+$/, "")}/${path.replace(/^\\/+/, "")}`;');
  lines.push("}");
  lines.push("");
  lines.push(
    "function serializeValue(value: unknown): string | undefined {",
  );
  lines.push("  if (value === undefined || value === null) return undefined;");
  lines.push("  if (value instanceof Date) return value.toISOString();");
  lines.push("  return String(value);");
  lines.push("}");
  lines.push("");
  lines.push("function serializeBody(value: unknown): unknown {");
  lines.push("  if (");
  lines.push('    typeof value === "object" &&');
  lines.push("    value !== null &&");
  lines.push('    "save" in value &&');
  lines.push('    typeof value.save === "function"');
  lines.push("  ) {");
  lines.push("    return value.save();");
  lines.push("  }");
  lines.push("  return value;");
  lines.push("}");
  lines.push("");
  lines.push("function escapeRegExp(value: string): string {");
  lines.push('  return value.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&");');
  lines.push("}");
  lines.push("");
  lines.push("function pathParameterPattern(name: string): RegExp {");
  lines.push(
    '  return new RegExp(`\\\\{[+#./;?&]?${escapeRegExp(name)}(?:\\\\*|:\\\\d+)?\\\\}`, "g");',
  );
  lines.push("}");
  lines.push("");
  lines.push("function isSuccessStatus(status: number): boolean {");
  lines.push("  return status >= 200 && status < 300;");
  lines.push("}");
  lines.push("");
  for (const contract of contracts) {
    emitContractClient(contract, modelTypes, lines);
  }

  return `${lines.join("\n")}\n`;
}

function emitContractClient(
  contract: TransportContract,
  modelTypes: Set<string>,
  lines: string[],
): void {
  lines.push(`export class ${contract.name}Client {`);
  lines.push("  private readonly baseUrl: string;");
  lines.push("  private readonly transport: TypraFetchTransport;");
  lines.push("");
  lines.push("  constructor(options: TypraClientOptions) {");
  lines.push("    this.baseUrl = options.baseUrl;");
  lines.push("    this.transport = options.transport;");
  lines.push("  }");
  lines.push("");
  for (const operation of contract.operations) {
    emitOperationClient(operation, modelTypes, lines);
    lines.push("");
  }
  lines.push("}");
  lines.push("");
}

function emitOperationClient(
  operation: TransportOperation,
  modelTypes: Set<string>,
  lines: string[],
): void {
  const inputType = operationInputType(operation);
  const resultType = operationResultType(operation, modelTypes);
  lines.push(
    `  async ${toCamelCase(operation.operation)}(input: ${inputType}): Promise<${resultType}> {`,
  );
  lines.push(`    let path = ${JSON.stringify(routePathTemplate(operation))};`);
  for (const binding of operation.bindings.filter((b) => b.kind === "path")) {
    const property = propertyAccess(binding.name);
    lines.push(
      `    path = path.replace(pathParameterPattern(${JSON.stringify(binding.wireName)}), encodeURIComponent(serializeValue(input${property}) ?? ""));`,
    );
  }
  lines.push("    const query = new URLSearchParams();");
  for (const binding of operation.bindings.filter((b) => b.kind === "query")) {
    const property = propertyAccess(binding.name);
    lines.push(`    {`);
    lines.push(`      const value = serializeValue(input${property});`);
    lines.push(
      `      if (value !== undefined) query.set(${JSON.stringify(binding.wireName)}, value);`,
    );
    lines.push(`    }`);
  }
  lines.push("    const queryText = query.toString();");
  lines.push("    if (queryText) path = `${path}?${queryText}`;");
  lines.push("    const headers: Record<string, string> = {};");
  for (const binding of operation.bindings.filter((b) => b.kind === "header")) {
    const property = propertyAccess(binding.name);
    lines.push(`    {`);
    lines.push(`      const value = serializeValue(input${property});`);
    lines.push(
      `      if (value !== undefined) headers[${JSON.stringify(binding.wireName)}] = value;`,
    );
    lines.push(`    }`);
  }
  const body = operation.bindings.find((binding) => binding.kind === "body");
  if (body) {
    const property = propertyAccess(body.name);
    lines.push('    headers["Content-Type"] ??= "application/json";');
    lines.push(`    const body = serializeBody(input${property});`);
  } else {
    lines.push("    const body = undefined;");
  }
  lines.push("    const response = await this.transport({");
  lines.push(`      method: ${JSON.stringify(operation.verb.toUpperCase())},`);
  lines.push("      url: joinUrl(this.baseUrl, path),");
  lines.push("      headers,");
  lines.push("      body,");
  lines.push("    });");
  emitResponseReturn(operation, modelTypes, lines);
  lines.push("  }");
}

function operationInputType(operation: TransportOperation): string {
  if (operation.bindings.length === 0) return "Record<string, never>";
  const fields = operation.bindings.map((binding) => {
    const optional = binding.optional ? "?" : "";
    return `${binding.name}${optional}: ${typeScriptType(binding.type)}`;
  });
  return `{ ${fields.join("; ")} }`;
}

function operationResultType(
  operation: TransportOperation,
  modelTypes: Set<string>,
): string {
  const response = successBodyResponse(operation);
  if (!response?.body || response.body === "void") return "void";
  return typeScriptType(response.body, modelTypes);
}

function collectClientModelImports(
  contracts: TransportContract[],
  modelTypes: Set<string>,
): string[] {
  const imports = new Set<string>();
  for (const contract of contracts) {
    for (const operation of contract.operations) {
      for (const binding of operation.bindings) {
        if (modelTypes.has(binding.type)) imports.add(binding.type);
      }
      for (const response of operation.responses) {
        if (response.body && modelTypes.has(response.body)) {
          imports.add(response.body);
        }
      }
    }
  }
  return Array.from(imports).sort();
}

function typeScriptType(type: string, modelTypes = new Set<string>()): string {
  if (modelTypes.has(type)) return type;
  switch (type) {
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "int32":
    case "int64":
    case "float32":
    case "float64":
    case "integer":
    case "numeric":
    case "number":
      return "number";
    case "void":
      return "void";
    default:
      return type;
  }
}

function emitResponseReturn(
  operation: TransportOperation,
  modelTypes: Set<string>,
  lines: string[],
): void {
  lines.push("    if (!isSuccessStatus(response.status)) {");
  lines.push(
    "      throw new Error(`Unexpected response status ${response.status}`);",
  );
  lines.push("    }");
  const response = successBodyResponse(operation);
  if (!response?.body || response.body === "void") {
    lines.push("    return undefined;");
    return;
  }
  if (modelTypes.has(response.body)) {
    lines.push(
      `    return ${response.body}.load(response.body as Record<string, unknown>);`,
    );
    return;
  }
  lines.push(`    return response.body as ${typeScriptType(response.body, modelTypes)};`);
}

function successBodyResponse(operation: TransportOperation) {
  return operation.responses.find(
    (candidate) => candidate.body && candidate.statusCodes.some(isSuccessCode),
  );
}

function isSuccessCode(statusCode: string): boolean {
  if (statusCode === "*") return false;
  if (/^\d+$/.test(statusCode)) {
    const status = Number(statusCode);
    return status >= 200 && status < 300;
  }
  const range = /^(\d+)-(\d+)$/.exec(statusCode);
  if (!range) return false;
  const start = Number(range[1]);
  const end = Number(range[2]);
  return start < 300 && end >= 200;
}

function propertyAccess(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
    ? `.${name}`
    : `[${JSON.stringify(name)}]`;
}

function routePathTemplate(operation: TransportOperation): string {
  return operation.uriTemplate.replace(/\{\?[^}]+\}/g, "");
}

export function collectTransportModelTypes(nodes: TypeNode[]): Set<string> {
  return new Set(
    nodes.filter((node) => !node.isProtocol).map((node) => node.typeName.name),
  );
}

function toCamelCase(value: string): string {
  return value ? value.charAt(0).toLowerCase() + value.slice(1) : value;
}

export function emitTypeScriptFetchClientConformanceTest(
  contracts: TransportContract[],
  modelTypes: Set<string>,
  clientImportPath: string,
  modelImportPath: string,
): string {
  const lines: string[] = [];
  const vectors = collectTransportClientVectors(contracts);
  const clientNames = Array.from(
    new Set(vectors.map((entry) => `${entry.contract.name}Client`)),
  ).sort();
  const modelImports = collectConformanceTestModelImports(vectors, modelTypes);

  lines.push("// Copyright (c) Microsoft. All rights reserved.");
  lines.push(
    "// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.",
  );
  lines.push("");
  lines.push(
    `import { ${clientNames.join(", ")}, TypraFetchRequest } from "${clientImportPath}";`,
  );
  if (modelImports.length > 0) {
    lines.push(`import { ${modelImports.join(", ")} } from "${modelImportPath}";`);
  }
  lines.push("");
  lines.push('describe("transport fetch consumer conformance", () => {');
  for (const entry of vectors) {
    const testName = `${entry.contract.name}.${entry.operation.operation}:${entry.vector.name ?? "unnamed"}`;
    const clientName = `${entry.contract.name}Client`;
    const methodName = toCamelCase(entry.operation.operation);
    const input = vectorObject(entry.vector.input);
    const typedInput = typedInputExpression(
      entry.operation,
      input,
      modelTypes,
    );
    const expectedRequest = expectedRequestShape(entry.operation, input);
    lines.push(`  it(${JSON.stringify(testName)}, async () => {`);
    lines.push("    let captured: TypraFetchRequest | undefined;");
    lines.push(`    const client = new ${clientName}({`);
    lines.push('      baseUrl: "https://example.test",');
    lines.push("      transport: async (request) => {");
    lines.push("        captured = request;");
    lines.push("        return {");
    lines.push("          status: 200,");
    lines.push(`          body: ${JSON.stringify(entry.vector.expected ?? null)},`);
    lines.push("        };");
    lines.push("      },");
    lines.push("    });");
    lines.push(`    const result = await client.${methodName}(${typedInput});`);
    lines.push("    expect(captured).toEqual(");
    lines.push(indent(renderTypeScriptLiteral(expectedRequest, 6), 6));
    lines.push("    );");
    lines.push(
      "    const observed = typeof result === \"object\" && result !== null && \"save\" in result && typeof result.save === \"function\" ? result.save() : result;",
    );
    lines.push(`    expect(observed).toEqual(${JSON.stringify(entry.vector.expected ?? undefined)});`);
    lines.push("  });");
  }
  lines.push("});");
  lines.push("");

  return `${lines.join("\n")}\n`;
}

function collectTransportClientVectors(contracts: TransportContract[]): Array<{
  contract: TransportContract;
  operation: TransportOperation;
  vector: CallableVector;
}> {
  return contracts.flatMap((contract) =>
    contract.operations.flatMap((operation) =>
      (operation.callable.vectors ?? [])
        .filter((vector) => vector.stage === "transport")
        .map((vector) => ({ contract, operation, vector })),
    ),
  );
}

function collectConformanceTestModelImports(
  vectors: Array<{
    operation: TransportOperation;
  }>,
  modelTypes: Set<string>,
): string[] {
  const imports = new Set<string>();
  for (const { operation } of vectors) {
    for (const binding of operation.bindings) {
      if (binding.kind === "body" && modelTypes.has(binding.type)) {
        imports.add(binding.type);
      }
    }
  }
  return Array.from(imports).sort();
}

function typedInputExpression(
  operation: TransportOperation,
  input: Record<string, unknown>,
  modelTypes: Set<string>,
): string {
  const fields = operation.bindings.map((binding) => {
    const value = input[binding.name];
    if (binding.kind === "body" && modelTypes.has(binding.type)) {
      return `${binding.name}: ${binding.type}.load(${JSON.stringify(value)})`;
    }
    return `${binding.name}: ${JSON.stringify(value)}`;
  });
  return `{ ${fields.join(", ")} }`;
}

function expectedRequestShape(
  operation: TransportOperation,
  input: Record<string, unknown>,
): {
  method: string;
  url: string;
  headers: Record<string, string>;
  body?: unknown;
} {
  let path = routePathTemplate(operation);
  for (const binding of operation.bindings.filter((b) => b.kind === "path")) {
    path = path.replace(
      new RegExp(`\\{[+#./;?&]?${escapeRegExpForEmitter(binding.wireName)}(?:\\*|:\\d+)?\\}`, "g"),
      encodeURIComponent(String(input[binding.name] ?? "")),
    );
  }
  const query = new URLSearchParams();
  for (const binding of operation.bindings.filter((b) => b.kind === "query")) {
    const value = input[binding.name];
    if (value !== undefined && value !== null) {
      query.set(binding.wireName, String(value));
    }
  }
  const queryText = query.toString();
  if (queryText) path = `${path}?${queryText}`;

  const headers: Record<string, string> = {};
  for (const binding of operation.bindings.filter((b) => b.kind === "header")) {
    const value = input[binding.name];
    if (value !== undefined && value !== null) {
      headers[binding.wireName] = String(value);
    }
  }

  const request: {
    method: string;
    url: string;
    headers: Record<string, string>;
    body?: unknown;
  } = {
    method: operation.verb.toUpperCase(),
    url: `https://example.test${path}`,
    headers,
    body: undefined,
  };
  const body = operation.bindings.find((binding) => binding.kind === "body");
  if (body) {
    request.headers["Content-Type"] = "application/json";
    request.body = input[body.name];
  }
  return request;
}

function vectorObject(value: unknown): Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function escapeRegExpForEmitter(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function indent(value: string, spaces: number): string {
  return value
    .split("\n")
    .map((line) => `${" ".repeat(spaces)}${line}`)
    .join("\n");
}

function renderTypeScriptLiteral(value: unknown, indentSize = 0): string {
  if (value === undefined) return "undefined";
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) {
    return `[${value.map((item) => renderTypeScriptLiteral(item, indentSize)).join(", ")}]`;
  }
  const entries = Object.entries(value as Record<string, unknown>);
  if (entries.length === 0) return "{}";
  const current = " ".repeat(indentSize);
  const next = " ".repeat(indentSize + 2);
  return [
    "{",
    ...entries.map(
      ([key, entryValue]) =>
        `${next}${JSON.stringify(key)}: ${renderTypeScriptLiteral(entryValue, indentSize + 2)},`,
    ),
    `${current}}`,
  ].join("\n");
}
