/**
 * Go scaffolding emitter — generates the LoadContext / SaveContext file.
 *
 * Replaces `context.go.njk` Nunjucks template with a typed TypeScript
 * function that produces identical Go source output.
 */

// ============================================================================
// Context interface
// ============================================================================

interface GoContextContext {
  header: string;
  packageName: string;
}

// ============================================================================
// Main entry point
// ============================================================================

/**
 * Emit the Go context file containing LoadContext and SaveContext structs.
 *
 * @param ctx - header string and package name
 * @returns Complete Go source file as a string
 */
export function emitGoContext(ctx: GoContextContext): string {
  const lines: string[] = [];

  lines.push("// Code generated by Typra emitter; DO NOT EDIT.");
  lines.push(`// ${ctx.header}`);
  lines.push("");
  lines.push(`package ${ctx.packageName}`);
  lines.push("");
  lines.push("import (");
  lines.push('\t"fmt"');
  lines.push('\t"reflect"');
  lines.push('\t"sort"');
  lines.push('\t"strings"');
  lines.push("");
  lines.push('\t"gopkg.in/yaml.v3"');
  lines.push(")");
  lines.push("");
  lines.push("// LoadContext provides context for loading operations");
  lines.push("type LoadContext struct {");
  lines.push("\t// Add any context fields needed for loading");
  lines.push("\t// e.g., file paths, base directories, etc.");
  lines.push("}");
  lines.push("");
  lines.push("// NewLoadContext creates a new LoadContext");
  lines.push("func NewLoadContext() *LoadContext {");
  lines.push("\treturn &LoadContext{}");
  lines.push("}");
  lines.push("");
  lines.push("// SaveContext provides context for saving operations");
  lines.push("type SaveContext struct {");
  lines.push("\t// Add any context fields needed for saving");
  lines.push("\t// e.g., output directories, formatting options, etc.");
  lines.push("}");
  lines.push("");
  lines.push("// NewSaveContext creates a new SaveContext");
  lines.push("func NewSaveContext() *SaveContext {");
  lines.push("\treturn &SaveContext{}");
  lines.push("}");
  lines.push("");
  lines.push("// ptrOf returns a pointer to the given value. Used by factory functions");
  lines.push("// to set optional (pointer) fields in struct literals.");
  lines.push("func ptrOf[T any](v T) *T {");
  lines.push("\treturn &v");
  lines.push("}");
  lines.push("");
  lines.push("func marshalYAMLDocument(data interface{}) (string, error) {");
  lines.push("\tnode := toYAMLNode(data)");
  lines.push("\tbytes, err := yaml.Marshal(node)");
  lines.push("\tif err != nil {");
  lines.push('\t\treturn "", err');
  lines.push("\t}");
  lines.push("\treturn string(bytes), nil");
  lines.push("}");
  lines.push("");
  lines.push("func toYAMLNode(value interface{}) *yaml.Node {");
  lines.push("\tswitch v := value.(type) {");
  lines.push("\tcase nil:");
  lines.push('\t\treturn &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!null"}');
  lines.push("\tcase string:");
  lines.push('\t\tnode := &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: v}');
  lines.push('\t\tif strings.Contains(v, "\\n") {');
  lines.push("\t\t\tnode.Style = yaml.DoubleQuotedStyle");
  lines.push("\t\t}");
  lines.push("\t\treturn node");
  lines.push("\tcase map[string]interface{}:");
  lines.push("\t\treturn mapToYAMLNode(v)");
  lines.push("\tcase []interface{}:");
  lines.push("\t\tnode := &yaml.Node{Kind: yaml.SequenceNode, Tag: \"!!seq\"}");
  lines.push("\t\tfor _, item := range v {");
  lines.push("\t\t\tnode.Content = append(node.Content, toYAMLNode(item))");
  lines.push("\t\t}");
  lines.push("\t\treturn node");
  lines.push("\t}");
  lines.push("");
  lines.push("\trv := reflect.ValueOf(value)");
  lines.push("\tif rv.IsValid() {");
  lines.push("\t\tswitch rv.Kind() {");
  lines.push("\t\tcase reflect.Slice, reflect.Array:");
  lines.push("\t\t\tnode := &yaml.Node{Kind: yaml.SequenceNode, Tag: \"!!seq\"}");
  lines.push("\t\t\tfor i := 0; i < rv.Len(); i++ {");
  lines.push("\t\t\t\tnode.Content = append(node.Content, toYAMLNode(rv.Index(i).Interface()))");
  lines.push("\t\t\t}");
  lines.push("\t\t\treturn node");
  lines.push("\t\tcase reflect.Map:");
  lines.push("\t\t\tif rv.Type().Key().Kind() == reflect.String {");
  lines.push("\t\t\t\titems := make(map[string]interface{}, rv.Len())");
  lines.push("\t\t\t\tfor _, key := range rv.MapKeys() {");
  lines.push("\t\t\t\t\titems[key.String()] = rv.MapIndex(key).Interface()");
  lines.push("\t\t\t\t}");
  lines.push("\t\t\t\treturn mapToYAMLNode(items)");
  lines.push("\t\t\t}");
  lines.push("\t\t}");
  lines.push("\t}");
  lines.push("");
  lines.push("\tnode := &yaml.Node{}");
  lines.push("\tif err := node.Encode(value); err == nil {");
  lines.push('\t\tif node.Kind == yaml.ScalarNode && node.Tag == "!!str" && strings.Contains(node.Value, "\\n") {');
  lines.push("\t\t\tnode.Style = yaml.DoubleQuotedStyle");
  lines.push("\t\t}");
  lines.push("\t\treturn node");
  lines.push("\t}");
  lines.push('\treturn &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: fmt.Sprint(value)}');
  lines.push("}");
  lines.push("");
  lines.push("func mapToYAMLNode(items map[string]interface{}) *yaml.Node {");
  lines.push('\tnode := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}');
  lines.push("\tkeys := make([]string, 0, len(items))");
  lines.push("\tfor key := range items {");
  lines.push("\t\tkeys = append(keys, key)");
  lines.push("\t}");
  lines.push("\tsort.Strings(keys)");
  lines.push("\tfor _, key := range keys {");
  lines.push('\t\tnode.Content = append(node.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: key}, toYAMLNode(items[key]))');
  lines.push("\t}");
  lines.push("\treturn node");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
