import { EmitContext, Program, emitFile, resolvePath } from "@typespec/compiler";
import { dirname, relative, resolve } from "path";
import { TypraEmitterOptions } from "../lib.js";

interface GeneratedManifestEntry {
  path: string;
  marker: boolean;
}

interface GeneratedManifest {
  emitter: "typra-emitter";
  version: 1;
  generatedAt: string;
  files: GeneratedManifestEntry[];
}

const generatedFilesByProgram = new WeakMap<Program, Map<string, GeneratedManifestEntry>>();

export async function emitGeneratedFile(
  context: EmitContext<TypraEmitterOptions>,
  filePath: string,
  content: string,
  options: { marker?: boolean } = {},
): Promise<void> {
  const marker = options.marker ?? shouldMark(filePath);
  const finalContent = marker ? addMarker(filePath, content) : content;
  recordGeneratedFile(context.program, filePath, marker);

  await emitFile(context.program, {
    path: filePath,
    content: finalContent,
  });
}

export async function emitGeneratedManifest(context: EmitContext<TypraEmitterOptions>): Promise<void> {
  const entries = [...(generatedFilesByProgram.get(context.program)?.values() ?? [])]
    .sort((left, right) => left.path.localeCompare(right.path));
  const manifest: GeneratedManifest = {
    emitter: "typra-emitter",
    version: 1,
    generatedAt: new Date().toISOString(),
    files: entries,
  };

  await emitFile(context.program, {
    path: resolvePath(context.emitterOutputDir, ".typra-generated", "manifest.json"),
    content: JSON.stringify(manifest, null, 2),
  });
}

function recordGeneratedFile(program: Program, filePath: string, marker: boolean): void {
  let entries = generatedFilesByProgram.get(program);
  if (!entries) {
    entries = new Map<string, GeneratedManifestEntry>();
    generatedFilesByProgram.set(program, entries);
  }
  entries.set(normalizePath(filePath), {
    path: normalizePath(filePath),
    marker,
  });
}

function shouldMark(filePath: string): boolean {
  return !filePath.endsWith(".json");
}

function addMarker(filePath: string, content: string): string {
  const marker = markerFor(filePath);
  return content.startsWith(marker) ? content : `${marker}\n${content}`;
}

function markerFor(filePath: string): string {
  if (filePath.endsWith(".md")) {
    return "<!-- <auto-generated by typra-emitter> -->";
  }
  if (filePath.endsWith(".py") || filePath.endsWith(".yaml") || filePath.endsWith(".yml")) {
    return "# <auto-generated by typra-emitter>";
  }
  return "// <auto-generated by typra-emitter>";
}

function normalizePath(filePath: string): string {
  const absolute = resolve(filePath);
  const base = dirname(absolute);
  return relative(base, absolute).startsWith("..")
    ? absolute.replace(/\\/g, "/")
    : filePath.replace(/\\/g, "/");
}
