import { EmitContext, Program, emitFile, resolvePath } from "@typespec/compiler";
import { existsSync, readFileSync, unlinkSync } from "node:fs";
import { dirname, relative, resolve } from "path";
import { TypraEmitterOptions } from "../lib.js";

export interface GeneratedManifestEntry {
  outputRoot: string;
  path: string;
  marker: boolean;
}

export interface GeneratedManifest {
  emitter: "typra-emitter";
  version: 1;
  generatedAt: string;
  files: GeneratedManifestEntry[];
}

const generatedFilesByProgram = new WeakMap<Program, Map<string, GeneratedManifestEntry>>();
const DETERMINISTIC_GENERATED_AT = "1970-01-01T00:00:00.000Z";

export async function emitGeneratedFile(
  context: EmitContext<TypraEmitterOptions>,
  filePath: string,
  content: string,
  options: { marker?: boolean; outputRoot?: string; allowEmpty?: boolean } = {},
): Promise<void> {
  const marker = options.marker ?? shouldMark(filePath);
  const normalizedContent = normalizeGeneratedContent(content, { allowEmpty: options.allowEmpty });
  if (!normalizedContent && !options.allowEmpty) {
    removeSkippedGeneratedFile(filePath);
    return;
  }

  const finalContent = marker ? addMarker(filePath, normalizedContent) : normalizedContent;
  recordGeneratedFile(context.program, filePath, marker, options.outputRoot);

  await emitFile(context.program, {
    path: filePath,
    content: finalContent,
  });
}

export async function emitGeneratedManifest(context: EmitContext<TypraEmitterOptions>): Promise<void> {
  const entries = [...(generatedFilesByProgram.get(context.program)?.values() ?? [])]
    .sort((left, right) => left.path.localeCompare(right.path));
  const manifest: GeneratedManifest = {
    emitter: "typra-emitter",
    version: 1,
    generatedAt: context.options["deterministic-output"] ? DETERMINISTIC_GENERATED_AT : new Date().toISOString(),
    files: entries,
  };

  await emitFile(context.program, {
    path: resolvePath(context.emitterOutputDir, ".typra-generated", "manifest.json"),
    content: `${JSON.stringify(manifest, null, 2)}\n`,
  });
}

function recordGeneratedFile(program: Program, filePath: string, marker: boolean, outputRoot?: string): void {
  let entries = generatedFilesByProgram.get(program);
  if (!entries) {
    entries = new Map<string, GeneratedManifestEntry>();
    generatedFilesByProgram.set(program, entries);
  }
  entries.set(normalizePath(filePath), {
    outputRoot: normalizePath(outputRoot || dirname(filePath)),
    path: normalizePath(filePath),
    marker,
  });
}

function shouldMark(filePath: string): boolean {
  if (filePath.endsWith("py.typed")) {
    return false;
  }
  return !filePath.endsWith(".json");
}

function addMarker(filePath: string, content: string): string {
  const marker = markerFor(filePath);
  if (filePath.endsWith(".md") && content.startsWith("---\n")) {
    return addMarkdownMarkerAfterFrontmatter(content, marker);
  }
  return content.startsWith(marker) ? content : `${marker}\n${content}`;
}

function addMarkdownMarkerAfterFrontmatter(content: string, marker: string): string {
  const closingDelimiter = "\n---\n";
  const closingIndex = content.indexOf(closingDelimiter, 4);
  if (closingIndex < 0) {
    return content.startsWith(marker) ? content : `${marker}\n${content}`;
  }

  const markerIndex = closingIndex + closingDelimiter.length;
  const beforeMarker = content.slice(0, markerIndex);
  const afterMarker = content.slice(markerIndex);
  return afterMarker.startsWith(marker) ? content : `${beforeMarker}${marker}\n${afterMarker}`;
}

function markerFor(filePath: string): string {
  if (filePath.endsWith(".md")) {
    return "<!-- <auto-generated by typra-emitter> -->";
  }
  if (filePath.endsWith(".py") || filePath.endsWith(".yaml") || filePath.endsWith(".yml")) {
    return "# <auto-generated by typra-emitter>";
  }
  return "// <auto-generated by typra-emitter>";
}

function normalizePath(filePath: string): string {
  return relative(process.cwd(), resolve(filePath)).replace(/\\/g, "/");
}

function normalizeGeneratedContent(content: string, options: { allowEmpty?: boolean } = {}): string {
  const normalizedLines = content.replace(/\r\n?/g, "\n").split("\n").map(line => line.trimEnd());
  while (normalizedLines.length > 0 && normalizedLines[normalizedLines.length - 1] === "") {
    normalizedLines.pop();
  }

  if (normalizedLines.length === 0) {
    return options.allowEmpty ? "" : "";
  }

  return `${normalizedLines.join("\n")}\n`;
}

function removeSkippedGeneratedFile(filePath: string): void {
  const absolutePath = resolve(filePath);
  if (!existsSync(absolutePath)) {
    return;
  }

  const existingContent = readFileSync(absolutePath, "utf8");
  if (!existingContent.includes("<auto-generated by typra-emitter>")) {
    console.warn(`Warning: skipped empty generated output but preserved unmarked file: ${filePath}`);
    return;
  }

  unlinkSync(absolutePath);
}
