import { TypeNode } from "./ir/ast.js";
import { toKebabCase, toSnakeCase } from "./ir/utilities.js";
import { toPascalCase } from "./ir/visitor.js";
import { EmitTarget } from "./lib.js";

const SCALAR_TYPES = new Set([
  "any",
  "array",
  "boolean",
  "dictionary",
  "float",
  "float32",
  "float64",
  "int32",
  "int64",
  "integer",
  "number",
  "numeric",
  "object",
  "bytes",
  "plainDate",
  "plainTime",
  "string",
  "unknown",
  "url",
  "utcDateTime",
  "void",
]);

export function shouldEmitCompileOnlyProtocolScaffolds(target: EmitTarget): boolean {
  return target["protocol-scaffolds"] === "compile-only";
}

export function collectProtocolNodes(nodes: TypeNode[]): TypeNode[] {
  return nodes
    .filter(node => node.isProtocol)
    .sort((left, right) => {
      const byGroup = (left.group || "").localeCompare(right.group || "");
      if (byGroup !== 0) return byGroup;
      return left.typeName.name.localeCompare(right.typeName.name);
    });
}

export function emitTypeScriptProtocolScaffolds(protocols: TypeNode[], importPath: string): string {
  if (protocols.length === 0) return "";

  const importedNames = collectReferencedNames(protocols);
  const lines: string[] = [
    "// Copyright (c) Microsoft. All rights reserved.",
    "// WARNING: This is an auto-generated file. DO NOT EDIT THIS FILE DIRECTLY.",
    "",
    `import type { ${importedNames.join(", ")} } from "${importPath}";`,
    "",
  ];

  for (const protocol of protocols) {
    const protocolName = protocol.typeName.name;
    const className = `CompileOnly${protocolName}`;
    lines.push(`class ${className} implements ${protocolName} {`);
    for (const method of protocol.methods) {
      const params = Object.entries(method.params)
        .map(([name, typeName]) => `${name}: ${typescriptType(typeName)}`)
        .join(", ");
      const ret = typescriptType(method.returns);
      if (method.sync) {
        lines.push(`  ${method.name}(${params}): ${ret} {`);
        lines.push(`    throw new Error("${protocolName}.${method.name} is a compile-only protocol scaffold.");`);
        lines.push("  }");
      } else {
        lines.push(`  async ${method.name}(${params}): Promise<${ret}> {`);
        lines.push(`    throw new Error("${protocolName}.${method.name} is a compile-only protocol scaffold.");`);
        lines.push("  }");
      }
    }
    lines.push("}");
    lines.push("");
    lines.push(`const ${lowerFirst(protocolName)}Scaffold: ${protocolName} = new ${className}();`);
    lines.push(`void ${lowerFirst(protocolName)}Scaffold;`);
    lines.push("");
  }

  return lines.join("\n");
}

export function emitPythonProtocolScaffolds(protocols: TypeNode[], importPath: string): string {
  if (protocols.length === 0) return "";

  const importedNames = collectReferencedNames(protocols);
  const needsAny = protocols.some(protocol =>
    protocol.methods.some(method =>
      Object.values(method.params).some(usesPythonAny) || usesPythonAny(method.returns),
    ),
  );
  const lines: string[] = [
    "##########################################",
    "# WARNING: This is an auto-generated file.",
    "# DO NOT EDIT THIS FILE DIRECTLY",
    "# ANY EDITS WILL BE LOST",
    "##########################################",
    "",
  ];
  if (needsAny) {
    lines.push("from typing import Any");
    lines.push("");
  }
  lines.push(`from ${importPath} import ${importedNames.join(", ")}`);
  lines.push("");

  for (const protocol of protocols) {
    const protocolName = protocol.typeName.name;
    lines.push("");
    lines.push(`class CompileOnly${protocolName}:`);
    if (protocol.methods.length === 0) {
      lines.push("    pass");
    }
    for (const method of protocol.methods) {
      const params = Object.entries(method.params)
        .map(([name, typeName]) => `${toSnakeCase(name)}: ${pythonType(typeName)}`)
        .join(", ");
      const paramPrefix = params ? `, ${params}` : "";
      const ret = pythonType(method.returns);
      if (method.sync) {
        lines.push(`    def ${toSnakeCase(method.name)}(self${paramPrefix}) -> ${ret}:`);
      } else {
        lines.push(`    async def ${toSnakeCase(method.name)}(self${paramPrefix}) -> ${ret}:`);
      }
      lines.push(`        raise NotImplementedError("${protocolName}.${method.name} is a compile-only protocol scaffold.")`);
      lines.push("");
    }
    lines.push("");
    lines.push(`${toSnakeCase(protocolName)}_scaffold: ${protocolName} = CompileOnly${protocolName}()`);
  }

  return lines.join("\n");
}

export function emitGoProtocolScaffolds(protocols: TypeNode[], packageName: string, importPath: string): string {
  if (protocols.length === 0) return "";

  const importAlias = "typra";
  const needsErrors = protocols.some(protocol =>
    protocol.methods.some(method => !(method.sync && method.optional)),
  );
  const lines: string[] = [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    "",
    `package ${packageName}_test`,
    "",
    "import (",
    ...(needsErrors ? ["\t\"errors\"", ""] : []),
    `\t${importAlias} \"${importPath}\"`,
    ")",
    "",
  ];

  for (const protocol of protocols) {
    const protocolName = protocol.typeName.name;
    const structName = `compileOnly${protocolName}`;
    lines.push(`type ${structName} struct{}`);
    lines.push("");
    lines.push(`var _ ${importAlias}.${protocolName} = (*${structName})(nil)`);
    lines.push("");
    for (const method of protocol.methods) {
      const params = Object.entries(method.params)
        .map(([name, typeName]) => `${name} ${goType(typeName, importAlias)}`)
        .join(", ");
      lines.push(`func (*${structName}) ${toPascalCase(method.name)}(${params})${goReturn(method, importAlias)} {`);
      lines.push(...goUnsupportedBody(method, importAlias));
      lines.push("}");
      lines.push("");
    }
  }

  return lines.join("\n");
}

export function emitJavaProtocolScaffolds(protocols: TypeNode[], packageName: string): { className: string; source: string } | undefined {
  if (protocols.length === 0) return undefined;

  const className = "ProtocolScaffoldsGeneratedTest";
  const lines: string[] = [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    `package ${packageName};`,
    "",
    `final class ${className} {`,
    `  private ${className}() { }`,
    "",
    "  static void run() {",
  ];
  for (const protocol of protocols) {
    lines.push(`    ${protocol.typeName.name} ${lowerFirst(protocol.typeName.name)} = new CompileOnly${protocol.typeName.name}();`);
  }
  lines.push("  }");
  lines.push("");

  for (const protocol of protocols) {
    const protocolName = protocol.typeName.name;
    lines.push(`  private static final class CompileOnly${protocolName} implements ${protocolName} {`);
    for (const method of protocol.methods) {
      const params = Object.entries(method.params)
        .map(([name, typeName]) => `${javaType(typeName)} ${name}`)
        .join(", ");
      const ret = javaType(method.returns);
      lines.push("    @Override");
      lines.push(`    public ${ret} ${method.name}(${params}) {`);
      lines.push(`      throw new UnsupportedOperationException("${protocolName}.${method.name} is a compile-only protocol scaffold.");`);
      lines.push("    }");
      lines.push("");
    }
    lines.push("  }");
    lines.push("");
  }

  lines.push("}");
  lines.push("");
  return { className, source: lines.join("\n") };
}

export function emitRustProtocolScaffolds(protocols: TypeNode[], importPath: string): string {
  if (protocols.length === 0) return "";

  const lines: string[] = [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    "",
    "#![allow(unused_imports, dead_code, unused_variables, clippy::all)]",
    "",
    `use ${importPath}::*;`,
    "",
  ];

  for (const protocol of protocols) {
    const protocolName = protocol.typeName.name;
    const structName = `CompileOnly${protocolName}`;
    lines.push(`struct ${structName};`);
    lines.push("");
    lines.push("#[async_trait::async_trait]");
    lines.push(`impl ${protocolName} for ${structName} {`);
    for (const method of protocol.methods) {
      const params = Object.entries(method.params)
        .map(([name, typeName]) => `${toSnakeCase(name)}: &${rustType(typeName)}`)
        .join(", ");
      const paramPrefix = params ? `, ${params}` : "";
      const ret = rustType(method.returns);
      if (method.sync) {
        lines.push(`    fn ${toSnakeCase(method.name)}(&self${paramPrefix}) -> ${ret} {`);
        lines.push(`        panic!("${protocolName}.${method.name} is a compile-only protocol scaffold.")`);
        lines.push("    }");
      } else {
        lines.push(`    async fn ${toSnakeCase(method.name)}(&self${paramPrefix}) -> Result<${ret}, Box<dyn std::error::Error + Send + Sync>> {`);
        lines.push(`        Err("${protocolName}.${method.name} is a compile-only protocol scaffold.".into())`);
        lines.push("    }");
      }
    }
    lines.push("}");
    lines.push("");
    lines.push("#[test]");
    lines.push(`fn ${toSnakeCase(protocolName)}_compile_only_conformance() {`);
    lines.push(`    let _scaffold: Box<dyn ${protocolName}> = Box::new(${structName});`);
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

function collectReferencedNames(protocols: TypeNode[]): string[] {
  const names = new Set<string>();
  for (const protocol of protocols) {
    names.add(protocol.typeName.name);
    for (const method of protocol.methods) {
      for (const typeName of [method.returns, ...Object.values(method.params)]) {
        const reference = referencedTypeName(typeName);
        if (reference) {
          names.add(reference);
        }
      }
    }
  }
  return [...names].sort((left, right) => left.localeCompare(right));
}

function referencedTypeName(typeName: string): string | undefined {
  const normalized = typeName.replace(/\?$/, "").replace(/\[\]$/, "");
  if (normalized === "Record<unknown>") return undefined;
  return SCALAR_TYPES.has(normalized) ? undefined : normalized;
}

function typescriptType(typeName: string): string {
  if (typeName.endsWith("?")) return `${typescriptType(typeName.slice(0, -1))} | null`;
  if (typeName === "Record<unknown>" || typeName === "dictionary") return "Record<string, unknown>";
  if (typeName === "any") return "unknown";
  const map: Record<string, string> = {
    any: "unknown",
    boolean: "boolean",
    bytes: "Uint8Array",
    dictionary: "Record<string, unknown>",
    float: "number",
    float32: "number",
    float64: "number",
    int32: "number",
    int64: "number",
    integer: "number",
    number: "number",
    numeric: "number",
    plainDate: "Date",
    plainTime: "Date",
    string: "string",
    unknown: "unknown",
    url: "string",
    utcDateTime: "Date",
  };
  return map[typeName] || typeName;
}

function pythonType(typeName: string): string {
  if (typeName.endsWith("?")) return `${pythonType(typeName.slice(0, -1))} | None`;
  if (typeName.endsWith("[]")) return `list[${pythonType(typeName.slice(0, -2))}]`;
  if (typeName === "Record<unknown>" || typeName === "dictionary") return "dict[str, Any]";
  if (typeName === "unknown" || typeName === "any") return "Any";
  if (typeName === "void") return "None";
  const map: Record<string, string> = {
    boolean: "bool",
    float: "float",
    float32: "float",
    float64: "float",
    int32: "int",
    int64: "int",
    integer: "int",
    number: "float",
    numeric: "float",
    string: "str",
  };
  return map[typeName] || typeName;
}

function usesPythonAny(typeName: string): boolean {
  const normalized = typeName.replace(/\?$/, "").replace(/\[\]$/, "");
  return normalized === "unknown" || normalized === "any" || normalized === "Record<unknown>" || normalized === "dictionary";
}

function goType(typeName: string, importAlias: string): string {
  if (typeName.endsWith("?")) return `*${goType(typeName.slice(0, -1), importAlias)}`;
  if (typeName.endsWith("[]")) return `[]${goType(typeName.slice(0, -2), importAlias)}`;
  if (typeName === "Record<unknown>" || typeName === "dictionary") return "map[string]interface{}";
  if (typeName === "unknown" || typeName === "any") return "interface{}";
  if (typeName === "void") return "";
  const map: Record<string, string> = {
    boolean: "bool",
    float: "float64",
    float32: "float32",
    float64: "float64",
    int32: "int32",
    int64: "int64",
    integer: "int",
    number: "float64",
    numeric: "float64",
    string: "string",
  };
  return map[typeName] || `${importAlias}.${typeName}`;
}

function goReturn(method: TypeNode["methods"][number], importAlias: string): string {
  const ret = goType(method.returns, importAlias);
  if (method.sync && method.optional) {
    return ret ? ` ${ret}` : "";
  }
  if (method.sync) {
    return ret ? ` (${ret}, error)` : " error";
  }
  return ret ? ` (${ret}, error)` : " error";
}

function goUnsupportedBody(method: TypeNode["methods"][number], importAlias: string): string[] {
  const ret = goType(method.returns, importAlias);
  if (method.sync && method.optional) {
    return [`\tpanic("compile-only protocol scaffold")`];
  }
  if (!ret) {
    return [`\treturn errors.New("compile-only protocol scaffold")`];
  }
  return [`\treturn *new(${ret}), errors.New("compile-only protocol scaffold")`];
}

function javaType(typeName: string): string {
  if (typeName.endsWith("?")) return javaType(typeName.slice(0, -1));
  if (typeName.endsWith("[]")) return `java.util.List<${javaType(typeName.slice(0, -2))}>`;
  if (typeName === "Record<unknown>" || typeName === "dictionary") return "java.util.Map<String, Object>";
  if (typeName === "unknown" || typeName === "any") return "Object";
  if (typeName === "void") return "void";
  const map: Record<string, string> = {
    boolean: "Boolean",
    float: "Double",
    float32: "Float",
    float64: "Double",
    int32: "Integer",
    int64: "Long",
    integer: "Integer",
    number: "Double",
    numeric: "Double",
    string: "String",
  };
  return map[typeName] || typeName;
}

function rustType(typeName: string): string {
  if (typeName.endsWith("?")) return `Option<${rustType(typeName.slice(0, -1))}>`;
  if (typeName.endsWith("[]")) return `Vec<${rustType(typeName.slice(0, -2))}>`;
  if (typeName === "Record<unknown>" || typeName === "dictionary") return "serde_json::Value";
  if (typeName === "unknown" || typeName === "any") return "serde_json::Value";
  if (typeName === "void") return "()";
  if (typeName === "string") return "String";
  const map: Record<string, string> = {
    boolean: "bool",
    float: "f64",
    float32: "f32",
    float64: "f64",
    int32: "i32",
    int64: "i64",
    integer: "i64",
    number: "f64",
    numeric: "f64",
    object: "serde_json::Value",
    array: "Vec<serde_json::Value>",
  };
  return map[typeName] || typeName;
}

function lowerFirst(value: string): string {
  return `${value.charAt(0).toLowerCase()}${value.slice(1)}`;
}
