import {
  CoercionAssignment,
  CoercionDecl,
  EnumDef,
  FactoryDecl,
  FieldDecl,
  MethodStubDecl,
  PolymorphicDispatchDecl,
  PropertyCategory,
  TypeDecl,
  WireDecl,
} from "../../ir/declarations.js";
import { ExprVisitor, toPascalCase } from "../../ir/visitor.js";

const JAVA_TYPE_MAP: Record<string, string> = {
  string: "String",
  boolean: "Boolean",
  int32: "Integer",
  int64: "Long",
  integer: "Integer",
  number: "Double",
  float: "Double",
  numeric: "Double",
  float32: "Float",
  float64: "Double",
  any: "Object",
  unknown: "Object",
  dictionary: "Map<String, Object>",
};

export function emitJavaFileContent(
  types: TypeDecl[],
  packageName: string,
  visitor: ExprVisitor,
  polymorphicTypeNames: Set<string>,
  enums: EnumDef[] = [],
): string {
  const lines: string[] = [];
  lines.push("// Code generated by Typra emitter; DO NOT EDIT.");
  lines.push(`package ${packageName};`);
  lines.push("");
  lines.push("import java.util.ArrayList;");
  lines.push("import java.util.LinkedHashMap;");
  lines.push("import java.util.List;");
  lines.push("import java.util.Map;");
  lines.push("");

  for (const enumDef of enums) {
    emitEnum(enumDef, lines);
  }
  for (const type of types) {
    emitType(type, lines, visitor, polymorphicTypeNames);
  }

  return lines.join("\n");
}

function emitEnum(enumDef: EnumDef, lines: string[]): void {
  if (enumDef.isOpen) return;
  lines.push(`enum ${enumDef.name} {`);
  for (const value of enumDef.values) {
    lines.push(`  ${toEnumMember(value)}("${escapeJava(value)}"),`);
  }
  lines.push("  ;");
  lines.push("");
  lines.push("  public final String value;");
  lines.push(`  ${enumDef.name}(String value) { this.value = value; }`);
  lines.push(`  public static ${enumDef.name} fromValue(String value) {`);
  lines.push(`    for (${enumDef.name} item : values()) {`);
  lines.push("      if (item.value.equals(value)) return item;");
  lines.push("    }");
  lines.push("    return valueOf(value.toUpperCase().replace(\"-\", \"_\"));");
  lines.push("  }");
  lines.push("}");
  lines.push("");
}

function emitType(
  type: TypeDecl,
  lines: string[],
  visitor: ExprVisitor,
  polymorphicTypeNames: Set<string>,
): void {
  if (type.isProtocol) {
    emitProtocol(type, lines);
    return;
  }

  const typeName = type.typeName.name;
  const modifiers = type.isAbstract ? "public abstract" : "public";
  const extendsClause = type.base ? ` extends ${type.base.name}` : "";
  lines.push(`${modifiers} class ${typeName}${extendsClause} {`);
  lines.push(`  public static final String SHORTHAND_PROPERTY = ${type.coercionProperty ? `"${type.coercionProperty}"` : "null"};`);
  lines.push("");

  for (const field of type.fields) {
    lines.push(`  public ${javaFieldType(field, polymorphicTypeNames)} ${field.name}${javaDefault(field, polymorphicTypeNames)};`);
  }
  lines.push("");
  lines.push(`  public ${typeName}() { }`);
  lines.push("");

  emitLoad(type, lines, polymorphicTypeNames);
  emitSave(type, lines, polymorphicTypeNames);
  if (type.wire) {
    emitToWire(type.wire, lines);
  }
  emitJsonHelpers(typeName, lines);
  for (const factory of type.factories) {
    emitFactory(typeName, factory, visitor, lines);
  }
  for (const method of type.methods) {
    emitMethodStub(method, lines);
  }
  emitClassHelpers(lines);

  lines.push("}");
  lines.push("");
}

function emitProtocol(type: TypeDecl, lines: string[]): void {
  lines.push(`public interface ${type.typeName.name} {`);
  for (const method of type.methods) {
    const params = Object.entries(method.params).map(([name, typeName]) => `${javaScalarType(typeName)} ${name}`).join(", ");
    lines.push(`  ${javaScalarType(method.returns)} ${method.name}(${params});`);
  }
  lines.push("}");
  lines.push("");
}

function emitLoad(type: TypeDecl, lines: string[], polymorphicTypeNames: Set<string>): void {
  const typeName = type.typeName.name;
  lines.push(`  @SuppressWarnings("unchecked")`);
  lines.push(`  public static ${typeName} load(Object input, LoadContext context) {`);
  lines.push("    LoadContext ctx = context == null ? new LoadContext() : context;");
  lines.push("    Object data = ctx.processInput(input);");
  emitCoercions(typeName, type.load.coercions, lines);
  if (type.polymorphicDispatch) {
    emitPolymorphicDispatch(typeName, type.polymorphicDispatch, lines);
  }
  lines.push("    if (!(data instanceof Map<?, ?> map)) {");
  lines.push(`      return ctx.processOutput(new ${typeName}());`);
  lines.push("    }");
  lines.push(`    ${typeName} result = new ${typeName}();`);
  for (const assignment of type.load.assignments) {
    const field = type.fields.find(f => f.name === assignment.fieldName);
    if (!field) continue;
    emitLoadField(field, lines, polymorphicTypeNames);
  }
  lines.push("    return ctx.processOutput(result);");
  lines.push("  }");
  lines.push("");
}

function emitCoercions(typeName: string, coercions: CoercionDecl[], lines: string[]): void {
  for (const coercion of coercions) {
    const check = coercionCheck("data", coercion.scalarType);
    if (!check) continue;
    lines.push(`    if (${check}) {`);
    lines.push(`      ${typeName} result = new ${typeName}();`);
    for (const assignment of coercion.assignments) {
      lines.push(`      result.${assignment.fieldName} = ${coercionValue(assignment, coercion.scalarType)};`);
    }
    lines.push("      return ctx.processOutput(result);");
    lines.push("    }");
  }
}

function emitPolymorphicDispatch(typeName: string, dispatch: PolymorphicDispatchDecl, lines: string[]): void {
  lines.push("    if (data instanceof Map<?, ?> dispatchMap) {");
  lines.push(`      Object discriminator = dispatchMap.get("${dispatch.discriminatorField}");`);
  lines.push("      if (discriminator != null) {");
  lines.push("        switch (String.valueOf(discriminator)) {");
  for (const variant of dispatch.variants) {
    lines.push(`          case "${escapeJava(variant.value)}":`);
    lines.push(`            return ${variant.typeName.name}.load(data, ctx);`);
  }
  lines.push("          default:");
  lines.push("            break;");
  lines.push("        }");
  lines.push("      }");
  lines.push("    }");
  void typeName;
}

function emitLoadField(field: FieldDecl, lines: string[], polymorphicTypeNames: Set<string>): void {
  const name = field.name;
  lines.push(`    if (map.containsKey("${name}") && map.get("${name}") != null) {`);
  switch (field.category.kind) {
    case "scalar":
      lines.push(`      result.${name} = ${loadScalar(`map.get("${name}")`, field.category.scalarType, field.isOpenEnum ? null : field.enumName)};`);
      break;
    case "complex":
      lines.push(`      result.${name} = ${field.category.typeName}.load(map.get("${name}"), ctx);`);
      break;
    case "collection_scalar":
      lines.push(`      result.${name} = new ArrayList<>();`);
      lines.push(`      if (map.get("${name}") instanceof Iterable<?> values) {`);
      lines.push("        for (Object item : values) {");
      lines.push(`                result.${name}.add(${loadScalar("item", field.category.scalarType, field.isOpenEnum ? null : field.enumName)});`);
      lines.push("        }");
      lines.push("      }");
      break;
    case "collection_complex":
      lines.push(`      result.${name} = new ArrayList<>();`);
      lines.push(`      if (map.get("${name}") instanceof Iterable<?> values) {`);
      lines.push("        for (Object item : values) {");
      lines.push(`          result.${name}.add(${field.category.typeName}.load(item, ctx));`);
      lines.push("        }");
      lines.push("      }");
      break;
    case "dict":
      lines.push(`      if (map.get("${name}") instanceof Map<?, ?> dict) {`);
      lines.push(`        result.${name} = copyMap(dict);`);
      lines.push("      }");
      break;
  }
  lines.push("    }");
  void polymorphicTypeNames;
}

function emitSave(type: TypeDecl, lines: string[], polymorphicTypeNames: Set<string>): void {
  lines.push("  public Map<String, Object> save(SaveContext context) {");
  lines.push("    SaveContext ctx = context == null ? new SaveContext() : context;");
  lines.push(`    ${type.typeName.name} obj = ctx.processObject(this);`);
  if (type.base) {
    lines.push("    Map<String, Object> result = super.save(ctx);");
  } else {
    lines.push("    Map<String, Object> result = new LinkedHashMap<>();");
  }
  for (const field of type.save.assignments) {
    emitSaveField(field.fieldName, field.category, field.isOpenEnum ? null : field.enumName, lines, polymorphicTypeNames);
  }
  lines.push("    return ctx.processDict(result);");
  lines.push("  }");
  lines.push("");
}

function emitSaveField(name: string, category: PropertyCategory, enumName: string | null, lines: string[], polymorphicTypeNames: Set<string>): void {
  switch (category.kind) {
    case "scalar":
    case "dict":
      lines.push(`    if (obj.${name} != null) result.put("${name}", ${enumName ? `obj.${name}.value` : `serializeScalar(obj.${name})`});`);
      break;
    case "complex":
      lines.push(`    if (obj.${name} != null) result.put("${name}", obj.${name}.save(ctx));`);
      break;
    case "collection_scalar":
      lines.push(`    if (obj.${name} != null) result.put("${name}", new ArrayList<>(obj.${name}));`);
      break;
    case "collection_complex":
      lines.push(`    if (obj.${name} != null) {`);
      lines.push("      List<Object> items = new ArrayList<>();");
      lines.push(`      for (${category.typeName} item : obj.${name}) items.add(item.save(ctx));`);
      lines.push(`      result.put("${name}", items);`);
      lines.push("    }");
      break;
  }
  void polymorphicTypeNames;
}

function emitClassHelpers(lines: string[]): void {
  lines.push("  private static Map<String, Object> copyMap(Map<?, ?> source) {");
  lines.push("    Map<String, Object> result = new LinkedHashMap<>();");
  lines.push("    for (Map.Entry<?, ?> entry : source.entrySet()) {");
  lines.push("      result.put(String.valueOf(entry.getKey()), entry.getValue());");
  lines.push("    }");
  lines.push("    return result;");
  lines.push("  }");
  lines.push("");
  lines.push("  private static Object serializeScalar(Object value) {");
  lines.push("    if (value instanceof Enum<?> e) return e.name().toLowerCase().replace(\"_\", \"-\");");
  lines.push("    return value;");
  lines.push("  }");
  lines.push("");
}

function emitToWire(wire: WireDecl, lines: string[]): void {
  lines.push("  public Map<String, Object> toWire(String provider) {");
  lines.push("    Map<String, Object> result = new LinkedHashMap<>();");
  lines.push("    String target = provider == null ? \"\" : provider;");
  for (const field of wire.mappings) {
    lines.push("    {");
    lines.push(`      String wireName = "${field.fieldName}";`);
    lines.push(`      boolean include = ${Object.keys(field.wireNames).length === 0 ? "true" : "target.isEmpty()"};`);
    for (const [provider, name] of Object.entries(field.wireNames)) {
      lines.push(`      if (target.equals("${escapeJava(provider)}")) { wireName = "${escapeJava(name)}"; include = true; }`);
    }
    lines.push(`      if (include && this.${field.fieldName} != null) result.put(wireName, serializeScalar(this.${field.fieldName}));`);
    lines.push("    }");
  }
  lines.push("    return result;");
  lines.push("  }");
  lines.push("");
}

function emitJsonHelpers(typeName: string, lines: string[]): void {
  lines.push("  public String toJson() {");
  lines.push("    return TypraJson.stringify(save(new SaveContext()));");
  lines.push("  }");
  lines.push("");
  lines.push(`  public static ${typeName} fromJson(String json) {`);
  lines.push("    throw new UnsupportedOperationException(\"Java JSON parsing is not emitted yet; use load(Map, LoadContext).\");");
  lines.push("  }");
  lines.push("");
}

function emitFactory(typeName: string, factory: FactoryDecl, visitor: ExprVisitor, lines: string[]): void {
  const params = Object.entries(factory.params).map(([name, type]) => `${javaScalarType(type)} ${name}`).join(", ");
  lines.push(`  public static ${typeName} ${factory.name}(${params}) {`);
  lines.push(`    return ${visitor.visitExpr(factory.body)};`);
  lines.push("  }");
  lines.push("");
}

function emitMethodStub(method: MethodStubDecl, lines: string[]): void {
  const params = Object.entries(method.params).map(([name, type]) => `${javaScalarType(type)} ${name}`).join(", ");
  lines.push(`  public ${javaScalarType(method.returns)} ${method.name}(${params}) {`);
  if (method.returns === "void") {
    lines.push("    return;");
  } else {
    lines.push("    throw new UnsupportedOperationException(\"Implement this helper outside generated code.\");");
  }
  lines.push("  }");
  lines.push("");
}

function javaFieldType(field: FieldDecl, polymorphicTypeNames: Set<string>): string {
  switch (field.category.kind) {
    case "scalar":
      return field.enumName && !field.isOpenEnum ? field.enumName : javaScalarType(field.category.scalarType);
    case "complex":
      return field.category.typeName;
    case "collection_scalar":
      return `List<${field.enumName && !field.isOpenEnum ? field.enumName : javaScalarType(field.category.scalarType)}>`;
    case "collection_complex":
      return `List<${field.category.typeName}>`;
    case "dict":
      return "Map<String, Object>";
  }
  void polymorphicTypeNames;
}

function javaScalarType(typeName: string): string {
  if (typeName.endsWith("[]")) {
    return `List<${javaScalarType(typeName.slice(0, -2))}>`;
  }
  if (typeName.endsWith("?")) {
    return javaScalarType(typeName.slice(0, -1));
  }
  if (typeName === "void") return "void";
  if (typeName === "Record<unknown>") return "Map<String, Object>";
  return JAVA_TYPE_MAP[typeName] ?? typeName;
}

function javaDefault(field: FieldDecl, polymorphicTypeNames: Set<string>): string {
  if (field.defaultValue !== null) {
    return ` = ${javaLiteral(field.defaultValue, field.enumName)}`;
  }
  if (field.isOptional) {
    return " = null";
  }
  switch (field.category.kind) {
    case "scalar":
      if (field.enumName && !field.isOpenEnum) return " = null";
      if (field.category.scalarType === "string") return ' = ""';
      if (field.category.scalarType === "boolean") return " = false";
      return " = 0";
    case "collection_scalar":
    case "collection_complex":
      return " = new ArrayList<>()";
    case "dict":
      return " = new LinkedHashMap<>()";
    case "complex":
      return " = null";
  }
  void polymorphicTypeNames;
}

function loadScalar(valueExpr: string, scalarType: string, enumName: string | null): string {
  if (enumName) {
    return `${enumName}.fromValue(String.valueOf(${valueExpr}))`;
  }
  switch (scalarType) {
    case "string":
      return `String.valueOf(${valueExpr})`;
    case "boolean":
      return `(${valueExpr} instanceof Boolean b ? b : Boolean.parseBoolean(String.valueOf(${valueExpr})))`;
    case "int32":
    case "integer":
      return `(${valueExpr} instanceof Number n ? n.intValue() : Integer.parseInt(String.valueOf(${valueExpr})))`;
    case "int64":
      return `(${valueExpr} instanceof Number n ? n.longValue() : Long.parseLong(String.valueOf(${valueExpr})))`;
    case "float32":
      return `(${valueExpr} instanceof Number n ? n.floatValue() : Float.parseFloat(String.valueOf(${valueExpr})))`;
    case "number":
    case "float":
    case "numeric":
    case "float64":
      return `(${valueExpr} instanceof Number n ? n.doubleValue() : Double.parseDouble(String.valueOf(${valueExpr})))`;
    default:
      return valueExpr;
  }
}

function coercionCheck(valueExpr: string, scalarType: string): string | null {
  switch (scalarType) {
    case "string":
      return `${valueExpr} instanceof String`;
    case "boolean":
      return `${valueExpr} instanceof Boolean`;
    case "int32":
    case "int64":
    case "integer":
    case "number":
    case "float":
    case "numeric":
    case "float32":
    case "float64":
      return `${valueExpr} instanceof Number`;
    default:
      return null;
  }
}

function coercionValue(assignment: CoercionAssignment, scalarType: string): string {
  if (assignment.isInput) {
    return loadScalar("data", scalarType, null);
  }
  return javaLiteral(assignment.literalValue ?? "", null);
}

function javaLiteral(value: string | number | boolean, enumName: string | null): string {
  if (typeof value === "string") {
    if (enumName) return `${enumName}.${toEnumMember(value)}`;
    return `"${escapeJava(value)}"`;
  }
  return String(value);
}

function toEnumMember(value: string): string {
  return value.replace(/[^A-Za-z0-9]+/g, "_").replace(/^(\d)/, "_$1").toUpperCase();
}

function escapeJava(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, "\\\"").replace(/\r/g, "\\r").replace(/\n/g, "\\n");
}
