import {
  CollectionHelperDecl,
  CoercionAssignment,
  CoercionDecl,
  EnumDef,
  FactoryDecl,
  FieldDecl,
  MethodStubDecl,
  PolymorphicDispatchDecl,
  SaveAssignment,
  TypeDecl,
  WireDecl,
  isClosedPolymorphicDispatch,
} from "../../ir/declarations.js";
import { shouldGuardMissingRequiredField, shouldOmitAbsentOnSave } from "../../ir/field-emission-policy.js";
import {
  orderedEntryShorthandCases,
  entryShorthandTarget,
  isIntegralScalar,
  isFractionalScalar,
  isStringEncodedScalar,
  isBooleanScalar,
} from "../../ir/scalar-kinds.js";
import { ExprVisitor } from "../../ir/visitor.js";
import { EDITABLE_SEAM_MARKER, hasEditableSeamMarker } from "../../cleanup/generated-file.js";
import {
  javaEnumMemberName,
  javaEnumTypeName,
  javaMethodName,
  javaPropertyName,
  javaTypeName,
} from "./identifiers.js";

type JavaNativeSerialization = "none" | "jackson";

const JAVA_TYPE_MAP: Record<string, string> = {
  string: "String",
  boolean: "Boolean",
  int32: "Integer",
  int64: "Long",
  integer: "Integer",
  number: "Double",
  float: "Double",
  numeric: "Double",
  float32: "Float",
  float64: "Double",
  any: "Object",
  unknown: "Object",
  dictionary: "Map<String, Object>",
};

export function emitJavaFileContent(
  types: TypeDecl[],
  packageName: string,
  visitor: ExprVisitor,
  polymorphicTypeNames: Set<string>,
  enums: EnumDef[] = [],
  allTypes: TypeDecl[] = types,
  nativeSerialization: JavaNativeSerialization = "none",
): string {
  const lines: string[] = [];
  lines.push("// Code generated by Typra emitter; DO NOT EDIT.");
  lines.push(`package ${packageName};`);
  lines.push("");
  lines.push("import java.util.ArrayList;");
  lines.push("import java.util.LinkedHashMap;");
  lines.push("import java.util.List;");
  lines.push("import java.util.Map;");
  if (nativeSerialization === "jackson") {
    if (enums.length > 0) {
      lines.push("import com.fasterxml.jackson.annotation.JsonCreator;");
      lines.push("import com.fasterxml.jackson.annotation.JsonValue;");
    }
    lines.push("import com.fasterxml.jackson.annotation.JsonIgnore;");
    lines.push("import com.fasterxml.jackson.annotation.JsonInclude;");
    lines.push("import com.fasterxml.jackson.annotation.JsonProperty;");
    lines.push("import com.fasterxml.jackson.databind.annotation.JsonDeserialize;");
    lines.push("import com.fasterxml.jackson.databind.annotation.JsonSerialize;");
  }
  lines.push("");

  for (const enumDef of enums) emitEnum(enumDef, lines, false, nativeSerialization);
  for (const type of types) {
    emitType(type, lines, visitor, polymorphicTypeNames, allTypes, nativeSerialization);
  }

  return lines.join("\n");
}

export function emitJavaEnum(enumDef: EnumDef, packageName: string, nativeSerialization: JavaNativeSerialization = "none"): string {
  const lines = [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    `package ${packageName};`,
    "",
  ];
  if (nativeSerialization === "jackson") {
    lines.push("import com.fasterxml.jackson.annotation.JsonCreator;");
    lines.push("import com.fasterxml.jackson.annotation.JsonValue;");
    lines.push("");
  }
  emitEnum(enumDef, lines, true, nativeSerialization);
  return lines.join("\n");
}

function emitEnum(enumDef: EnumDef, lines: string[], isPublic: boolean, nativeSerialization: JavaNativeSerialization = "none"): void {
  if (enumDef.isOpen) return;
  const enumName = javaEnumTypeName(enumDef.name);
  lines.push(`${isPublic ? "public " : ""}enum ${enumName} {`);
  for (const value of enumDef.values) {
    lines.push(`  ${javaEnumMemberName(value)}("${escapeJava(value)}"),`);
  }
  lines.push("  ;");
  lines.push("");
  if (nativeSerialization === "jackson") lines.push("  @JsonValue");
  lines.push("  public final String value;");
  lines.push(`  ${enumName}(String value) { this.value = value; }`);
  if (nativeSerialization === "jackson") lines.push("  @JsonCreator");
  lines.push(`  public static ${enumName} fromValue(String value) {`);
  if (hasParseAliases(enumDef)) {
    lines.push("    switch (value) {");
    for (const [canonical, aliases] of Object.entries(enumDef.parseAliases)) {
      for (const alias of aliases) {
        lines.push(`      case "${escapeJava(alias)}":`);
      }
      lines.push(`        return ${javaEnumMemberName(canonical)};`);
    }
    lines.push("      default:");
    lines.push("        break;");
    lines.push("    }");
  }
  lines.push(`    for (${enumName} item : values()) {`);
  lines.push("      if (item.value.equals(value)) return item;");
  lines.push("    }");
  lines.push("    return valueOf(value.toUpperCase().replace(\"-\", \"_\"));");
  lines.push("  }");
  lines.push("}");
  lines.push("");
}

function hasParseAliases(value: { parseAliases: Record<string, string[]> }): boolean {
  return Object.values(value.parseAliases).some(aliases => aliases.length > 0);
}

function javaAliasParserName(enumName: string): string {
  return `parse${javaEnumTypeName(enumName)}`;
}

function emitOpenEnumAliasParsers(fields: FieldDecl[], lines: string[]): void {
  const emitted = new Set<string>();
  for (const field of fields) {
    if (!field.enumName || !field.isOpenEnum || !hasParseAliases(field)) continue;
    if (emitted.has(field.enumName)) continue;
    emitted.add(field.enumName);
    lines.push(`  private static String ${javaAliasParserName(field.enumName)}(String value) {`);
    lines.push("    switch (value) {");
    for (const [canonical, aliases] of Object.entries(field.parseAliases)) {
      for (const alias of aliases) {
        lines.push(`      case "${escapeJava(alias)}":`);
      }
      lines.push(`        return "${escapeJava(canonical)}";`);
    }
    lines.push("      default:");
    lines.push("        return value;");
    lines.push("    }");
    lines.push("  }");
    lines.push("");
  }
}

function emitType(
  type: TypeDecl,
  lines: string[],
  visitor: ExprVisitor,
  polymorphicTypeNames: Set<string>,
  allTypes: TypeDecl[],
  nativeSerialization: JavaNativeSerialization,
): void {
  if (type.isProtocol) {
    emitProtocol(type, lines);
    return;
  }

  const typeName = javaTypeName(type.typeName.name);
  const modifiers = type.isAbstract ? "public abstract" : "public";
  const extendsClause = type.base ? ` extends ${javaTypeName(type.base.name)}` : "";
  if (nativeSerialization === "jackson") {
    lines.push(`@JsonSerialize(using = ${typeName}.TypraJacksonSerializer.class)`);
    lines.push(`@JsonDeserialize(using = ${typeName}.TypraJacksonDeserializer.class)`);
    lines.push("@JsonInclude(JsonInclude.Include.NON_NULL)");
  }
  lines.push(`${modifiers} class ${typeName}${extendsClause} {`);
  lines.push(`  public static final String SHORTHAND_PROPERTY = ${type.coercionProperty ? `"${type.coercionProperty}"` : "null"};`);
  lines.push("");

  const inheritedFields = collectInheritedFields(type, allTypes);
  for (const field of type.fields.filter(field => !inheritedFields.has(field.name))) {
    if (nativeSerialization === "jackson") {
      lines.push(`  @JsonProperty("${escapeJava(field.name)}")`);
      lines.push("  @JsonInclude(JsonInclude.Include.NON_NULL)");
    }
    lines.push(`  public ${javaFieldType(field, polymorphicTypeNames)} ${javaPropertyName(field.name)}${javaDefault(field, polymorphicTypeNames)};`);
  }
  if (retainsRawPayload(type)) {
    if (nativeSerialization === "jackson") lines.push("  @JsonIgnore");
    lines.push("  protected Map<String, Object> rawPayload;");
  }
  lines.push("");
  const inheritedDefaults = type.fields.filter(field =>
    inheritedFields.has(field.name) &&
    !field.isOptional &&
    field.defaultValue !== null
  );
  if (inheritedDefaults.length === 0) {
    lines.push(`  public ${typeName}() { }`);
  } else {
    lines.push(`  public ${typeName}() {`);
    for (const field of inheritedDefaults) {
      lines.push(`    this.${javaPropertyName(field.name)} = ${javaLiteral(field.defaultValue!, field.enumName, scalarTypeOf(field))};`);
    }
    lines.push("  }");
  }
  lines.push("");

  emitOpenEnumAliasParsers(type.fields, lines);
  emitLoad(type, lines, polymorphicTypeNames, inheritedFields);
  emitSave(type, lines, polymorphicTypeNames, inheritedFields);
  if (type.wire) {
    emitToWire(type.wire, lines);
  }

  function collectInheritedFields(type: TypeDecl, allTypes: TypeDecl[]): Set<string> {
    const fields = new Set<string>();
    let base = type.base ? allTypes.find(candidate => candidate.typeName.name === type.base?.name) : undefined;
    while (base) {
      for (const field of base.fields) fields.add(field.name);
      base = base.base ? allTypes.find(candidate => candidate.typeName.name === base?.base?.name) : undefined;
    }
    return fields;
  }

  emitSerializationHelpers(typeName, lines);
  if (nativeSerialization === "jackson") {
    emitJacksonHelpers(typeName, lines);
  }
  for (const factory of type.factories) {
    emitFactory(typeName, factory, visitor, lines);
  }
  for (const method of type.methods) {
    emitMethodDelegation(typeName, method, lines);
  }
  emitClassHelpers(lines);
  if (retainsRawPayload(type)) {
    emitRawPayloadHelpers(lines);
  }

  lines.push("}");
  lines.push("");
}

/**
 * An abstract base over an open discriminator has no wildcard subtype to absorb unrecognized
 * values, and Java emits `abstract class` for it, so those values need a concrete subclass to
 * land in. Without one, Java rejects a document every other target accepts: it conflates
 * "not directly instantiable" with "closed to unrecognized values", which are different
 * properties. C#, TypeScript and Python already emit the same carrier.
 */
function needsUnknownCarrier(type: TypeDecl): boolean {
  const dispatch = type.polymorphicDispatch;
  if (!dispatch || !type.isAbstract) {
    return false;
  }
  return !dispatch.defaultVariant && !isClosedPolymorphicDispatch(dispatch);
}

/**
 * Whether the type keeps the verbatim payload it was loaded from.
 *
 * A non-abstract base absorbs unrecognized values into itself and needs the payload to round-trip
 * undeclared keys. An abstract base delegates that to its carrier subclass, which stores the
 * payload on the inherited field, so the base must still declare it.
 */
function retainsRawPayload(type: TypeDecl): boolean {
  return type.polymorphicDispatch?.defaultVariant?.isSelfReference === true || needsUnknownCarrier(type);
}

function javaUnknownCarrierName(parentName: string): string {
  return `Unknown${javaTypeName(parentName)}`;
}

/**
 * Emit the concrete carrier for an abstract base whose discriminator is open.
 *
 * The base stays `abstract`, honouring the schema's `@abstract`, and unrecognized discriminator
 * values load as this subclass rather than throwing. Java allows one public top-level class per
 * file, so unlike the C# carrier this is emitted as its own compilation unit.
 *
 * The carrier declares no fields of its own: it stores the verbatim payload on the base's
 * `rawPayload` and lets the base's inherited `save` seed its result from it, so the unrecognized
 * discriminator value and every undeclared key survive a load/save round-trip unchanged.
 */
export function emitJavaUnknownCarrier(
  type: TypeDecl,
  packageName: string,
  nativeSerialization: JavaNativeSerialization = "none",
): { filename: string; source: string } | undefined {
  if (!needsUnknownCarrier(type)) {
    return undefined;
  }
  const parent = javaTypeName(type.typeName.name);
  const carrier = javaUnknownCarrierName(type.typeName.name);
  const lines: string[] = [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    `package ${packageName};`,
    "",
    "import java.util.Map;",
    ...(nativeSerialization === "jackson" ? [
      "import com.fasterxml.jackson.databind.annotation.JsonDeserialize;",
      "import com.fasterxml.jackson.databind.annotation.JsonSerialize;",
      "",
    ] : [""]),
    "/**",
    ` * Carries a ${parent} whose discriminator value matches no known subtype.`,
    " * The unrecognized value stays on the discriminator field and every key the schema does not",
    ` * declare is preserved verbatim, so an unknown ${parent} survives a load/save round-trip`,
    " * unchanged.",
    " */",
    ...(nativeSerialization === "jackson" ? [
      `@JsonSerialize(using = ${carrier}.TypraJacksonSerializer.class)`,
      `@JsonDeserialize(using = ${carrier}.TypraJacksonDeserializer.class)`,
    ] : []),
    `public final class ${carrier} extends ${parent} {`,
    `  public ${carrier}() { }`,
    "",
    `  public static ${carrier} load(Object input, LoadContext context) {`,
    "    LoadContext ctx = context == null ? new LoadContext() : context;",
    "    Object data = ctx.processInput(input);",
    "    if (!(data instanceof Map<?, ?> map)) {",
    `      throw new IllegalArgumentException("Cannot load ${carrier} from a non-object value.");`,
    "    }",
    `    ${carrier} result = new ${carrier}();`,
    `    result.rawPayload = ${parent}.cloneRawMap(map);`,
  ];
  for (const assignment of type.load.assignments) {
    lines.push(`    result.rawPayload.remove("${escapeJava(assignment.sourceName)}");`);
  }
  lines.push(`    ${parent}.loadBaseInto(result, map, ctx);`);
  lines.push("    return ctx.processOutput(result);");
  lines.push("  }");
  if (nativeSerialization === "jackson") {
    lines.push("");
    emitJacksonHelpers(carrier, lines);
  }
  lines.push("}");
  lines.push("");
  return { filename: `${carrier}.java`, source: lines.join("\n") };
}

function emitJacksonHelpers(typeName: string, lines: string[]): void {
  lines.push(`  public static final class TypraJacksonSerializer extends com.fasterxml.jackson.databind.JsonSerializer<${typeName}> {`);
  lines.push("    @Override");
  lines.push(`    public void serialize(${typeName} value, com.fasterxml.jackson.core.JsonGenerator generator, com.fasterxml.jackson.databind.SerializerProvider serializers) throws java.io.IOException {`);
  lines.push("      generator.writeObject(value == null ? null : value.save(new SaveContext()));");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push(`  public static final class TypraJacksonDeserializer extends com.fasterxml.jackson.databind.JsonDeserializer<${typeName}> {`);
  lines.push("    @Override");
  lines.push(`    public ${typeName} deserialize(com.fasterxml.jackson.core.JsonParser parser, com.fasterxml.jackson.databind.DeserializationContext context) throws java.io.IOException {`);
  lines.push("      Object data = parser.getCodec().readValue(parser, Object.class);");
  lines.push(`      return ${typeName}.load(data, new LoadContext());`);
  lines.push("    }");
  lines.push("  }");
  lines.push("");
}

function emitProtocol(type: TypeDecl, lines: string[]): void {
  lines.push(`public interface ${javaTypeName(type.typeName.name)} {`);
  for (const method of type.methods) {
    const params = Object.entries(method.params).map(([name, typeName]) => `${javaScalarType(typeName)} ${javaPropertyName(name)}`).join(", ");
    lines.push(`  ${javaScalarType(method.returns)} ${javaMethodName(method.name)}(${params});`);
  }
  lines.push("}");
  lines.push("");
}

function emitLoad(
  type: TypeDecl,
  lines: string[],
  polymorphicTypeNames: Set<string>,
  inheritedFields: Set<string>,
): void {
  const typeName = javaTypeName(type.typeName.name);
  lines.push(`  @SuppressWarnings("unchecked")`);
  lines.push(`  public static ${typeName} load(Object input, LoadContext context) {`);
  lines.push("    LoadContext ctx = context == null ? new LoadContext() : context;");
  lines.push("    Object data = ctx.processInput(input);");
  emitCoercions(typeName, type.load.coercions, lines, type.fields, type.isAbstract);
  if (type.polymorphicDispatch) {
    emitPolymorphicDispatch(typeName, type.polymorphicDispatch, lines);
  }
  if (type.isAbstract) {
    const discriminator = type.polymorphicDispatch?.discriminatorField ?? "type";
    if (needsUnknownCarrier(type)) {
      lines.push("    if (data instanceof Map<?, ?>) {");
      lines.push(`      return ${javaUnknownCarrierName(type.typeName.name)}.load(data, ctx);`);
      lines.push("    }");
    }
    lines.push(`    throw new IllegalArgumentException("Cannot instantiate abstract ${typeName}; expected a matching '${escapeJava(discriminator)}' discriminator.");`);
    lines.push("  }");
    lines.push("");
    emitLoadBaseInto(type, lines, polymorphicTypeNames, inheritedFields);
    return;
  }
  lines.push("    if (!(data instanceof Map<?, ?> map)) {");
  lines.push(`      return ctx.processOutput(new ${typeName}());`);
  lines.push("    }");
  lines.push(`    ${typeName} result = new ${typeName}();`);
  if (type.polymorphicDispatch?.defaultVariant?.isSelfReference) {
    lines.push(`    if (map.get("${escapeJava(type.polymorphicDispatch.discriminatorField)}") instanceof String) {`);
    lines.push("      result.rawPayload = cloneRawMap(map);");
    for (const assignment of type.load.assignments) {
      lines.push(`      result.rawPayload.remove("${escapeJava(assignment.sourceName)}");`);
    }
    lines.push("    }");
  }
  lines.push(`    ${typeName}.loadBaseInto(result, map, ctx);`);
  lines.push("    return ctx.processOutput(result);");
  lines.push("  }");
  lines.push("");
  emitLoadBaseInto(type, lines, polymorphicTypeNames, inheritedFields);
}

function emitLoadBaseInto(
  type: TypeDecl,
  lines: string[],
  polymorphicTypeNames: Set<string>,
  inheritedFields: Set<string>,
): void {
  const typeName = javaTypeName(type.typeName.name);
  lines.push(`  static void loadBaseInto(${typeName} result, Map<?, ?> map, LoadContext ctx) {`);
  if (type.base) {
    lines.push(`    ${javaTypeName(type.base.name)}.loadBaseInto(result, map, ctx);`);
  }
  for (const assignment of type.load.assignments) {
    if (inheritedFields.has(assignment.fieldName)) continue;
    const field = type.fields.find(candidate => candidate.name === assignment.fieldName);
    const collectionHelper = type.collectionHelpers.find(helper =>
      helper.propertyName === assignment.fieldName && helper.hasNameProperty
    );
    if (shouldGuardMissingRequiredField(field)) {
      const wireName = escapeJava(assignment.sourceName);
      lines.push(`    if (!map.containsKey("${wireName}") || map.get("${wireName}") == null) {`);
      lines.push(`      throw new IllegalArgumentException(ctx.at("${wireName}").path + ": missing required field");`);
      lines.push("    }");
    }
    if (field) emitLoadField(field, collectionHelper, lines, polymorphicTypeNames);
  }
  lines.push("  }");
  lines.push("");
}

function emitCoercions(
  typeName: string,
  coercions: CoercionDecl[],
  lines: string[],
  fields: FieldDecl[] = [],
  isAbstract = false,
): void {
  assertDistinctNumericCoercionFamilies(typeName, coercions);
  let emittedBroadNumberGuard = false;
  const orderedCoercions = [...coercions].sort(
    (left, right) => numericCoercionRank(left.scalarType) - numericCoercionRank(right.scalarType),
  );
  for (const coercion of orderedCoercions) {
    if (isBroadNumberCoercion(coercion.scalarType)) {
      if (emittedBroadNumberGuard) continue;
      emittedBroadNumberGuard = true;
    }
    const check = coercionCheck("data", coercion.scalarType);
    if (!check) continue;
    lines.push(`    if (${check}) {`);
    if (isAbstract) {
      lines.push("      Map<String, Object> coerced = new LinkedHashMap<>();");
      for (const assignment of coercion.assignments) {
        const field = fields.find(candidate => candidate.name === assignment.fieldName);
        lines.push(`      coerced.put("${escapeJava(assignment.fieldName)}", ${coercionValue(assignment, coercion.scalarType, field)});`);
      }
      lines.push(`      return ${typeName}.load(coerced, ctx);`);
      lines.push("    }");
      continue;
    }
    lines.push(`      ${typeName} result = new ${typeName}();`);
    for (const assignment of coercion.assignments) {
      const field = fields.find(candidate => candidate.name === assignment.fieldName);
      lines.push(`      result.${javaPropertyName(assignment.fieldName)} = ${coercionValue(assignment, coercion.scalarType, field)};`);
    }
    lines.push("      return ctx.processOutput(result);");
    lines.push("    }");
  }
}

function assertDistinctNumericCoercionFamilies(typeName: string, coercions: CoercionDecl[]): void {
  for (const [family, matches] of [
    ["integral", coercions.filter(coercion => isIntegralCoercion(coercion.scalarType))],
    ["floating-point", coercions.filter(coercion => isBroadNumberCoercion(coercion.scalarType))],
  ] as const) {
    if (matches.length > 1) {
      throw new Error(
        `Java emitter cannot distinguish multiple ${family} coercions for ${typeName}: ${matches.map(match => match.scalarType).join(", ")}`,
      );
    }
  }
}

function numericCoercionRank(scalarType: string): number {
  if (isIntegralCoercion(scalarType)) return 1;
  if (isBroadNumberCoercion(scalarType)) return 2;
  return 0;
}

function isIntegralCoercion(scalarType: string): boolean {
  return scalarType === "int32" || scalarType === "int64" || scalarType === "integer";
}

function isBroadNumberCoercion(scalarType: string): boolean {
  return scalarType === "number"
    || scalarType === "float"
    || scalarType === "numeric"
    || scalarType === "float32"
    || scalarType === "float64";
}

function emitPolymorphicDispatch(typeName: string, dispatch: PolymorphicDispatchDecl, lines: string[]): void {
  const isClosed = isClosedPolymorphicDispatch(dispatch);
  lines.push("    if (data instanceof Map<?, ?> dispatchMap) {");
  lines.push(`      Object discriminator = dispatchMap.get("${escapeJava(dispatch.discriminatorField)}");`);
  lines.push("      if (!(discriminator instanceof String discriminatorString) || discriminatorString.isEmpty()) {");
  lines.push(`        throw new IllegalArgumentException("Invalid ${typeName} discriminator field '${escapeJava(dispatch.discriminatorField)}': expected non-blank string");`);
  lines.push("      }");
  lines.push("      switch (discriminatorString) {");
  for (const variant of dispatch.variants) {
    lines.push(`        case "${escapeJava(variant.value)}":`);
    lines.push(`          return ${javaTypeName(variant.typeName.name)}.load(data, ctx);`);
  }
  lines.push("        default:");
  if (dispatch.defaultVariant && !dispatch.defaultVariant.isSelfReference) {
    lines.push(`          return ${javaTypeName(dispatch.defaultVariant.typeName.name)}.load(data, ctx);`);
  } else if (isClosed) {
    lines.push(`          throw new IllegalArgumentException("Unknown ${typeName} discriminator field '${escapeJava(dispatch.discriminatorField)}' value: " + discriminatorString);`);
  } else {
    lines.push("          break;");
  }
  lines.push("      }");
  lines.push("    }");
  void typeName;
}

function emitLoadField(
  field: FieldDecl,
  collectionHelper: CollectionHelperDecl | undefined,
  lines: string[],
  polymorphicTypeNames: Set<string>,
): void {
  const wireName = escapeJava(field.name);
  const name = javaPropertyName(field.name);
  lines.push(`    if (map.containsKey("${wireName}") && map.get("${wireName}") != null) {`);
  switch (field.category.kind) {
    case "scalar":
      lines.push(`      result.${name} = ${loadScalar(`map.get("${wireName}")`, field.category.scalarType, field.isOpenEnum ? null : field.enumName, openEnumAliasParser(field))};`);
      break;
    case "complex":
      lines.push(`      result.${name} = ${javaTypeName(field.category.typeName)}.load(map.get("${wireName}"), ctx.at("${wireName}"));`);
      break;
    case "collection_scalar":
      lines.push(`      result.${name} = new ArrayList<>();`);
      lines.push(`      if (map.get("${wireName}") instanceof Iterable<?> values) {`);
      lines.push("        for (Object item : values) {");
      lines.push(`                      result.${name}.add(${loadScalar("item", field.category.scalarType, field.isOpenEnum ? null : field.enumName, openEnumAliasParser(field))});`);
      lines.push("        }");
      lines.push("      }");
      break;
    case "collection_complex":
      lines.push(`      result.${name} = new ArrayList<>();`);
      if (collectionHelper?.hasNameProperty) {
        lines.push(`      if (map.get("${wireName}") instanceof Map<?, ?> values) {`);
        lines.push("        for (Map.Entry<?, ?> entry : values.entrySet()) {");
        lines.push("          if (entry.getValue() instanceof Iterable<?>) {");
        lines.push(`            throw new IllegalArgumentException(ctx.at("${wireName}").at(String.valueOf(entry.getKey())).path + ": invalid named collection entry category array");`);
        lines.push("          }");
        lines.push("          Map<String, Object> itemData;");
        lines.push("          if (entry.getValue() instanceof Map<?, ?> itemMap) {");
        lines.push("            itemData = copyMap(itemMap);");
        lines.push("          } else {");
        lines.push("            itemData = new LinkedHashMap<>();");
        lines.push(...emitJavaEntryShorthandArms(collectionHelper, "            "));
        lines.push("          }");
        lines.push("          itemData.put(\"name\", String.valueOf(entry.getKey()));");
        lines.push(`          ${javaTypeName(field.category.typeName)} item = ${javaTypeName(field.category.typeName)}.load(itemData, ctx.at("${wireName}").at(String.valueOf(entry.getKey())));`);
        lines.push(`          result.${name}.add(item);`);
        lines.push("        }");
        lines.push(`      } else if (map.get("${wireName}") instanceof Iterable<?> values) {`);
      } else {
        lines.push(`      if (map.get("${wireName}") instanceof Iterable<?> values) {`);
      }
      lines.push(`        int ${name}Index = 0;`);
      lines.push("        for (Object item : values) {");
      lines.push(`          result.${name}.add(${javaTypeName(field.category.typeName)}.load(item, ctx.at("${wireName}").atIndex(${name}Index++)));`);
      lines.push("        }");
      lines.push("      }");
      break;
    case "dict":
      lines.push(`      if (map.get("${wireName}") instanceof Map<?, ?> dict) {`);
      if (!field.category.valueType || field.category.valueType === "unknown") {
        lines.push(`        result.${name} = copyMap(dict);`);
      } else {
        lines.push(`        result.${name} = new LinkedHashMap<>();`);
        lines.push("        for (Map.Entry<?, ?> entry : dict.entrySet()) {");
        lines.push(`          result.${name}.put(String.valueOf(entry.getKey()), ${javaDictValueLoad("entry.getValue()", field.category.valueType, `ctx.at("${wireName}").at(String.valueOf(entry.getKey()))`)});`);
        lines.push("        }");
      }
      lines.push("      }");
      break;
  }
  lines.push("    }");
  void polymorphicTypeNames;
}

// ============================================================================
// Named-collection entry shorthand
// ============================================================================

/**
 * Expand an immediate scalar entry of a name-keyed collection.
 *
 * Without a declaration this keeps the historical positional behaviour, which is
 * unsound for a discriminated element type because its first declared field is
 * the discriminator. With `@entryShorthand` the value lands in the declared
 * field and the constants come from the element's own `@coerce` table.
 */
function emitJavaEntryShorthandArms(helper: CollectionHelperDecl, indent: string): string[] {
  const target = entryShorthandTarget(helper, "kind");
  const shorthand = helper.entryShorthand;
  const cases = shorthand ? orderedEntryShorthandCases(shorthand.cases) : [];

  if (!shorthand || cases.length === 0) {
    return [`${indent}itemData.put("${target}", entry.getValue());`];
  }

  const lines: string[] = [`${indent}Object shorthandValue = entry.getValue();`];
  let first = true;
  for (const entryCase of cases) {
    const check = javaScalarValueCheck(entryCase.scalarType);
    if (!check) continue;
    lines.push(`${indent}${first ? "if" : "} else if"} (${check}) {`);
    first = false;
    for (const a of entryCase.assignments) {
      lines.push(`${indent}  itemData.put("${a.fieldName}", ${javaShorthandLiteral(a.literalValue)});`);
    }
  }
  if (!first) lines.push(`${indent}}`);
  lines.push(`${indent}itemData.put("${shorthand.valueField}", shorthandValue);`);
  return lines;
}

/** Java `instanceof` test recognising a decoded value of the given TypeSpec scalar. */
function javaScalarValueCheck(scalarType: string): string | null {
  if (isIntegralScalar(scalarType)) {
    return "shorthandValue instanceof Integer || shorthandValue instanceof Long"
      + " || shorthandValue instanceof Short || shorthandValue instanceof Byte";
  }
  if (isFractionalScalar(scalarType)) {
    return "shorthandValue instanceof Double || shorthandValue instanceof Float"
      + " || shorthandValue instanceof java.math.BigDecimal";
  }
  if (isStringEncodedScalar(scalarType)) return "shorthandValue instanceof String";
  if (isBooleanScalar(scalarType)) return "shorthandValue instanceof Boolean";
  return null;
}

/** Render a coercion constant as a Java literal, preserving its declared JSON type. */
function javaShorthandLiteral(value: string | number | boolean | null): string {
  if (value === null) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  return JSON.stringify(value);
}

function emitSave(
  type: TypeDecl,
  lines: string[],
  polymorphicTypeNames: Set<string>,
  inheritedFields: Set<string>,
): void {
  lines.push("  public Map<String, Object> save(SaveContext context) {");
  lines.push("    SaveContext ctx = context == null ? new SaveContext() : context;");
  lines.push(`    ${javaTypeName(type.typeName.name)} obj = ctx.processObject(this);`);
  if (retainsRawPayload(type)) {
    lines.push("    Map<String, Object> result = obj.rawPayload == null ? new LinkedHashMap<>() : cloneRawMap(obj.rawPayload);");
  } else {
    lines.push("    Map<String, Object> result = new LinkedHashMap<>();");
  }
  lines.push("    obj.saveFields(result, ctx);");
  lines.push("    return ctx.processDict(result);");
  lines.push("  }");
  lines.push("");
  lines.push("  protected void saveFields(Map<String, Object> result, SaveContext ctx) {");
  if (type.base) lines.push("    super.saveFields(result, ctx);");
  lines.push(`    ${javaTypeName(type.typeName.name)} obj = this;`);
  for (const field of type.save.assignments) {
    if (inheritedFields.has(field.fieldName)) continue;
    const collectionHelper = type.collectionHelpers.find(helper =>
      helper.propertyName === field.fieldName && helper.hasNameProperty
    );
    emitSaveField(
      field,
      collectionHelper,
      lines,
      polymorphicTypeNames,
    );
  }
  lines.push("  }");
  lines.push("");
}

function emitSaveField(
  field: SaveAssignment,
  collectionHelper: CollectionHelperDecl | undefined,
  lines: string[],
  polymorphicTypeNames: Set<string>,
): void {
  const name = field.fieldName;
  const category = field.category;
  const enumName = field.isOpenEnum ? null : field.enumName;
  const wireName = escapeJava(name);
  const propertyName = javaPropertyName(name);
  switch (category.kind) {
    case "scalar":
      if (shouldOmitAbsentOnSave(field, "always-check")) {
        lines.push(`    if (obj.${propertyName} != null) result.put("${wireName}", ${enumName ? `obj.${propertyName}.value` : `serializeScalar(obj.${propertyName})`});`);
      } else {
        lines.push(`    result.put("${wireName}", ${enumName ? `obj.${propertyName}.value` : `serializeScalar(obj.${propertyName})`});`);
      }
      break;
    case "dict":
      if (category.valueType && category.valueType !== "unknown" && !JAVA_TYPE_MAP[category.valueType]) {
        if (shouldOmitAbsentOnSave(field, "always-check")) lines.push(`    if (obj.${propertyName} != null) {`);
        lines.push("      Map<String, Object> items = new LinkedHashMap<>();");
        lines.push(`      for (Map.Entry<String, ${javaDictValueType(category.valueType)}> entry : obj.${propertyName}.entrySet()) items.put(entry.getKey(), entry.getValue().save(ctx));`);
        lines.push(`      result.put("${wireName}", items);`);
        if (shouldOmitAbsentOnSave(field, "always-check")) lines.push("    }");
      } else {
        if (shouldOmitAbsentOnSave(field, "always-check")) {
          lines.push(`    if (obj.${propertyName} != null) result.put("${wireName}", serializeScalar(obj.${propertyName}));`);
        } else {
          lines.push(`    result.put("${wireName}", serializeScalar(obj.${propertyName}));`);
        }
      }
      break;
    case "complex":
      if (shouldOmitAbsentOnSave(field, "always-check")) {
        lines.push(`    if (obj.${propertyName} != null) result.put("${wireName}", obj.${propertyName}.save(ctx));`);
      } else {
        lines.push(`    result.put("${wireName}", obj.${propertyName}.save(ctx));`);
      }
      break;
    case "collection_scalar":
      if (enumName) {
        if (shouldOmitAbsentOnSave(field, "always-check")) lines.push(`    if (obj.${propertyName} != null) {`);
        lines.push("      List<Object> items = new ArrayList<>();");
        lines.push(`      for (${javaEnumTypeName(enumName)} item : obj.${propertyName}) items.add(item.value);`);
        lines.push(`      result.put("${wireName}", items);`);
        if (shouldOmitAbsentOnSave(field, "always-check")) lines.push("    }");
      } else {
        if (shouldOmitAbsentOnSave(field, "always-check")) {
          lines.push(`    if (obj.${propertyName} != null) result.put("${wireName}", new ArrayList<>(obj.${propertyName}));`);
        } else {
          lines.push(`    result.put("${wireName}", new ArrayList<>(obj.${propertyName}));`);
        }
      }
      break;
    case "collection_complex":
      if (shouldOmitAbsentOnSave(field, "always-check")) lines.push(`    if (obj.${propertyName} != null) {`);
      if (collectionHelper?.hasNameProperty) {
        lines.push("      List<Object> serializedItems = new ArrayList<>();");
        lines.push("      List<String> itemNames = new ArrayList<>();");
        lines.push("      java.util.Set<String> names = new java.util.HashSet<>();");
        lines.push("      boolean canUseObject = true;");
        lines.push(`      for (${javaTypeName(category.typeName)} item : obj.${propertyName}) {`);
        lines.push("        String itemName = item.name;");
        lines.push("        itemNames.add(itemName);");
        lines.push("        if (itemName == null || itemName.isEmpty() || !names.add(itemName)) canUseObject = false;");
        lines.push("        Map<String, Object> itemData = new LinkedHashMap<>(item.save(ctx));");
        lines.push('        if ("".equals(itemData.get("name"))) itemData.remove("name");');
        lines.push("        serializedItems.add(itemData);");
        lines.push("      }");
        lines.push(`      if ("array".equals(ctx.collectionFormat) || !canUseObject) {`);
        lines.push(`        result.put("${wireName}", serializedItems);`);
        lines.push("      } else {");
        lines.push("        Map<String, Object> objectItems = new LinkedHashMap<>();");
        lines.push("        for (int index = 0; index < serializedItems.size(); index++) {");
        lines.push("          Map<String, Object> itemData = new LinkedHashMap<>((Map<String, Object>) serializedItems.get(index));");
        lines.push("          String itemName = itemNames.get(index);");
        lines.push('          itemData.remove("name");');
        lines.push(`          if (ctx.useShorthand && ${javaTypeName(category.typeName)}.SHORTHAND_PROPERTY != null && itemData.size() == 1 && itemData.containsKey(${javaTypeName(category.typeName)}.SHORTHAND_PROPERTY)) {`);
        lines.push(`            objectItems.put(itemName, itemData.get(${javaTypeName(category.typeName)}.SHORTHAND_PROPERTY));`);
        lines.push("          } else {");
        lines.push("            objectItems.put(itemName, itemData);");
        lines.push("          }");
        lines.push("        }");
        lines.push(`        result.put("${wireName}", objectItems);`);
        lines.push("      }");
      } else {
        lines.push("      List<Object> items = new ArrayList<>();");
        lines.push(`      for (${javaTypeName(category.typeName)} item : obj.${propertyName}) items.add(item.save(ctx));`);
        lines.push(`      result.put("${wireName}", items);`);
      }
      if (shouldOmitAbsentOnSave(field, "always-check")) lines.push("    }");
      break;
  }
  void polymorphicTypeNames;
}

function emitClassHelpers(lines: string[]): void {
  lines.push("  private static Map<String, Object> copyMap(Map<?, ?> source) {");
  lines.push("    Map<String, Object> result = new LinkedHashMap<>();");
  lines.push("    for (Map.Entry<?, ?> entry : source.entrySet()) {");
  lines.push("      result.put(String.valueOf(entry.getKey()), entry.getValue());");
  lines.push("    }");
  lines.push("    return result;");
  lines.push("  }");
  lines.push("");
  lines.push("  private static Object serializeScalar(Object value) {");
  lines.push("    if (value instanceof Enum<?> e) return e.name().toLowerCase().replace(\"_\", \"-\");");
  lines.push("    return value;");
  lines.push("  }");
  lines.push("");
}

/**
 * Visibility is uniform across every class that retains a raw payload. Java forbids hiding an
 * inherited static method with weaker access, so a `private static` helper on a subclass of a
 * base that exposes the same helper more widely would not compile. C# emits `protected static`
 * for the same reason.
 */
function emitRawPayloadHelpers(lines: string[]): void {
  lines.push("  protected static Map<String, Object> cloneRawMap(Map<?, ?> source) {");
  lines.push("    Map<String, Object> result = new LinkedHashMap<>();");
  lines.push("    for (Map.Entry<?, ?> entry : source.entrySet()) {");
  lines.push("      result.put(String.valueOf(entry.getKey()), cloneRawValue(entry.getValue()));");
  lines.push("    }");
  lines.push("    return result;");
  lines.push("  }");
  lines.push("");
  lines.push("  protected static Object cloneRawValue(Object value) {");
  lines.push("    if (value instanceof Map<?, ?> map) return cloneRawMap(map);");
  lines.push("    if (value instanceof Iterable<?> values) {");
  lines.push("      List<Object> result = new ArrayList<>();");
  lines.push("      for (Object item : values) result.add(cloneRawValue(item));");
  lines.push("      return result;");
  lines.push("    }");
  lines.push("    return value;");
  lines.push("  }");
  lines.push("");
}

/**
 * A wire field is emitted only when the requested provider actually maps it, matching every other
 * backend (Go: `if wireName, ok := mapping[provider]`). Defaulting to the schema field name leaks
 * fields into payloads for providers — or for an empty/null provider — that never declared them.
 */
function emitToWire(wire: WireDecl, lines: string[]): void {
  lines.push("  public Map<String, Object> toWire(String provider) {");
  lines.push("    Map<String, Object> result = new LinkedHashMap<>();");
  lines.push("    String target = provider == null ? \"\" : provider;");
  for (const field of wire.mappings) {
    lines.push("    {");
    lines.push(`      String wireName = null;`);
    for (const [provider, name] of Object.entries(field.wireNames)) {
      lines.push(`      if (target.equals("${escapeJava(provider)}")) { wireName = "${escapeJava(name)}"; }`);
    }
    lines.push(`      if (wireName != null && this.${javaPropertyName(field.fieldName)} != null) result.put(wireName, serializeScalar(this.${javaPropertyName(field.fieldName)}));`);
    lines.push("    }");
  }
  lines.push("    return result;");
  lines.push("  }");
  lines.push("");
}

function emitSerializationHelpers(typeName: string, lines: string[]): void {
  lines.push("  public String toYaml() {");
  lines.push("    return TypraYaml.stringify(save(new SaveContext()));");
  lines.push("  }");
  lines.push("");
  lines.push("  public String toJson() {");
  lines.push("    return TypraJson.stringify(save(new SaveContext()));");
  lines.push("  }");
  lines.push("");
  lines.push(`  public static ${typeName} fromYaml(String yaml) {`);
  lines.push("    return fromYaml(yaml, new LoadContext());");
  lines.push("  }");
  lines.push("");
  lines.push(`  public static ${typeName} fromYaml(String yaml, LoadContext context) {`);
  lines.push("    return load(TypraYaml.parse(yaml), context);");
  lines.push("  }");
  lines.push("");
  lines.push(`  public static ${typeName} fromJson(String json) {`);
  lines.push(`    return fromJson(json, new LoadContext());`);
  lines.push("  }");
  lines.push("");
  lines.push(`  public static ${typeName} fromJson(String json, LoadContext context) {`);
  lines.push(`    return load(TypraJson.parse(json), context);`);
  lines.push("  }");
  lines.push("");
}

function emitFactory(typeName: string, factory: FactoryDecl, visitor: ExprVisitor, lines: string[]): void {
  const params = Object.entries(factory.params).map(([name, type]) => `${javaScalarType(type)} ${javaPropertyName(name)}`).join(", ");
  lines.push(`  public static ${typeName} ${javaMethodName(factory.name)}(${params}) {`);
  lines.push(`    return ${visitor.visitExpr(factory.body)};`);
  lines.push("  }");
  lines.push("");
}

function emitMethodDelegation(typeName: string, method: MethodStubDecl, lines: string[]): void {
  const params = Object.entries(method.params).map(([name, type]) => `${javaScalarType(type)} ${javaPropertyName(name)}`).join(", ");
  lines.push(`  public ${javaScalarType(method.returns)} ${javaMethodName(method.name)}(${params}) {`);
  const args = ["this", ...Object.keys(method.params).map(javaPropertyName)].join(", ");
  if (method.returns === "void") {
    lines.push(`    ${typeName}Methods.${javaMethodName(method.name)}(${args});`);
  } else {
    lines.push(`    return ${typeName}Methods.${javaMethodName(method.name)}(${args});`);
  }
  lines.push("  }");
  lines.push("");
}

export const JAVA_EDITABLE_SEAM_MARKER = `// ${EDITABLE_SEAM_MARKER}`;
export const JAVA_EDITABLE_SEAM_NOTE = "// Typra editable seam. This file is created once and is safe to edit.";

/**
 * Adds the editable-seam marker to a pre-existing helper that predates the marker contract.
 * Returns null when the file already carries the marker and needs no migration.
 *
 * Seam files are create-once and consumer-owned, so migration only prepends the comment
 * header; hand-written bodies are never rewritten. A leading BOM stays at byte zero and the
 * file's dominant line ending is preserved so the result stays valid and diff-clean.
 */
export function ensureJavaEditableSeamMarker(existingSource: string): string | null {
  if (hasEditableSeamMarker(existingSource)) return null;

  const bom = existingSource.startsWith("\uFEFF") ? "\uFEFF" : "";
  const body = bom ? existingSource.slice(1) : existingSource;
  const eol = /\r\n/.test(body) ? "\r\n" : "\n";
  return `${bom}${JAVA_EDITABLE_SEAM_MARKER}${eol}${JAVA_EDITABLE_SEAM_NOTE}${eol}${body}`;
}

export function emitJavaMethodHelper(type: TypeDecl, packageName: string): { filename: string; source: string } | null {
  if (type.isProtocol || type.methods.length === 0) return null;
  const typeName = javaTypeName(type.typeName.name);
  const helperName = `${typeName}Methods`;
  const lines = [
    JAVA_EDITABLE_SEAM_MARKER,
    JAVA_EDITABLE_SEAM_NOTE,
    `package ${packageName};`,
    "",
    `public final class ${helperName} {`,
    `  private ${helperName}() { }`,
    "",
  ];
  for (const method of type.methods) {
    const params = [
      `${typeName} self`,
      ...Object.entries(method.params).map(([name, paramType]) =>
        `${javaScalarType(paramType)} ${javaPropertyName(name)}`
      ),
    ].join(", ");
    lines.push(`  public static ${javaScalarType(method.returns)} ${javaMethodName(method.name)}(${params}) {`);
    lines.push(`    throw new UnsupportedOperationException("Implement ${typeName}.${javaMethodName(method.name)} in ${helperName}.");`);
    lines.push("  }");
    lines.push("");
  }
  lines.push("}");
  lines.push("");
  return { filename: `${helperName}.java`, source: lines.join("\n") };
}

function javaFieldType(field: FieldDecl, polymorphicTypeNames: Set<string>): string {
  switch (field.category.kind) {
    case "scalar":
      return field.enumName && !field.isOpenEnum ? javaEnumTypeName(field.enumName) : javaScalarType(field.category.scalarType);
    case "complex":
      return javaTypeName(field.category.typeName);
    case "collection_scalar":
      return `List<${field.enumName && !field.isOpenEnum ? javaEnumTypeName(field.enumName) : javaScalarType(field.category.scalarType)}>`;
    case "collection_complex":
      return `List<${javaTypeName(field.category.typeName)}>`;
    case "dict":
      return `Map<String, ${javaDictValueType(field.category.valueType)}>`;
  }
  void polymorphicTypeNames;
}

function javaScalarType(typeName: string): string {
  if (typeName.endsWith("[]")) {
    return `List<${javaScalarType(typeName.slice(0, -2))}>`;
  }
  if (typeName.endsWith("?")) {
    return javaScalarType(typeName.slice(0, -1));
  }
  if (typeName === "void") return "void";
  if (typeName === "Record<unknown>") return "Map<String, Object>";
  return JAVA_TYPE_MAP[typeName] ?? javaTypeName(typeName);
}

function javaDefault(field: FieldDecl, polymorphicTypeNames: Set<string>): string {
  if (
    field.hasExplicitDefault &&
    (field.category.kind === "collection_scalar" || field.category.kind === "collection_complex")
  ) {
    return " = new ArrayList<>()";
  }
  if (field.isOptional) {
    return " = null";
  }
  if (field.defaultValue !== null) {
    return ` = ${javaLiteral(field.defaultValue, field.enumName, scalarTypeOf(field))}`;
  }
  if (
    field.category.kind === "scalar" &&
    field.enumName &&
    !field.isOpenEnum &&
    field.allowedValues.length > 0
  ) {
    return ` = ${javaEnumTypeName(field.enumName)}.fromValue("${escapeJava(field.allowedValues[0])}")`;
  }
  switch (field.category.kind) {
    case "scalar":
      if (field.category.scalarType === "string") return ' = ""';
      if (field.category.scalarType === "boolean") return " = false";
      return ` = ${javaNumericLiteral(0, field.category.scalarType)}`;
    case "collection_scalar":
    case "collection_complex":
      return " = new ArrayList<>()";
    case "dict":
      return " = new LinkedHashMap<>()";
    case "complex":
      return " = null";
  }
  void polymorphicTypeNames;
}

function openEnumAliasParser(field: FieldDecl): string | null {
  if (field.enumName && field.isOpenEnum && hasParseAliases(field)) {
    return javaAliasParserName(field.enumName);
  }
  return null;
}

function javaDictValueType(valueType: string | undefined): string {
  if (!valueType || valueType === "unknown") return "Object";
  return JAVA_TYPE_MAP[valueType] ?? javaTypeName(valueType);
}

function javaDictValueLoad(valueExpr: string, valueType: string, contextExpr: string): string {
  if (JAVA_TYPE_MAP[valueType]) {
    return loadScalar(valueExpr, valueType, null);
  }
  return `${javaTypeName(valueType)}.load(${valueExpr}, ${contextExpr})`;
}

function loadScalar(valueExpr: string, scalarType: string, enumName: string | null, parseAliasFunction: string | null = null): string {
  if (enumName) {
    return `${javaEnumTypeName(enumName)}.fromValue(String.valueOf(${valueExpr}))`;
  }
  if (parseAliasFunction) {
    return `${parseAliasFunction}(String.valueOf(${valueExpr}))`;
  }
  switch (scalarType) {
    case "string":
      return `String.valueOf(${valueExpr})`;
    case "boolean":
      return `(${valueExpr} instanceof Boolean b ? b : Boolean.parseBoolean(String.valueOf(${valueExpr})))`;
    case "int32":
    case "integer":
      return `(${valueExpr} instanceof Number n ? n.intValue() : Integer.parseInt(String.valueOf(${valueExpr})))`;
    case "int64":
      return `(${valueExpr} instanceof Number n ? n.longValue() : Long.parseLong(String.valueOf(${valueExpr})))`;
    case "float32":
      return `(${valueExpr} instanceof Number n ? n.floatValue() : Float.parseFloat(String.valueOf(${valueExpr})))`;
    case "number":
    case "float":
    case "numeric":
    case "float64":
      return `(${valueExpr} instanceof Number n ? n.doubleValue() : Double.parseDouble(String.valueOf(${valueExpr})))`;
    default:
      return valueExpr;
  }
}

function coercionCheck(valueExpr: string, scalarType: string): string | null {
  switch (scalarType) {
    case "string":
      return `${valueExpr} instanceof String`;
    case "boolean":
      return `${valueExpr} instanceof Boolean`;
    case "int32":
    case "int64":
    case "integer":
      return `(${valueExpr} instanceof Integer || ${valueExpr} instanceof Long || ${valueExpr} instanceof Short || ${valueExpr} instanceof Byte)`;
    case "number":
    case "float":
    case "numeric":
    case "float32":
    case "float64":
      return `${valueExpr} instanceof Number`;
    default:
      return null;
  }
}

function coercionValue(assignment: CoercionAssignment, scalarType: string, field?: FieldDecl): string {
  if (assignment.isInput) {
    return loadScalar(
      "data",
      scalarType,
      field?.isOpenEnum ? null : field?.enumName ?? null,
      field ? openEnumAliasParser(field) : null,
    );
  }
  return javaLiteral(assignment.literalValue ?? "", field?.enumName ?? null, field ? scalarTypeOf(field) : null);
}

function javaLiteral(
  value: string | number | boolean,
  enumName: string | null,
  scalarType: string | null = null,
): string {
  if (typeof value === "string") {
    if (enumName) return `${javaEnumTypeName(enumName)}.fromValue("${escapeJava(value)}")`;
    return `"${escapeJava(value)}"`;
  }
  if (typeof value === "number" && scalarType) return javaNumericLiteral(value, scalarType);
  return String(value);
}

function scalarTypeOf(field: FieldDecl): string | null {
  return field.category.kind === "scalar" ? field.category.scalarType : null;
}

function javaNumericLiteral(value: number, scalarType: string): string {
  switch (scalarType) {
    case "int64":
      return `${value}L`;
    case "float32":
      return `${Number.isInteger(value) ? `${value}.0` : value}f`;
    case "number":
    case "float":
    case "numeric":
    case "float64":
      return `${Number.isInteger(value) ? `${value}.0` : value}d`;
    default:
      return String(value);
  }
}

function escapeJava(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, "\\\"").replace(/\r/g, "\\r").replace(/\n/g, "\\n");
}
