import { BaseTestContext, CoercionTest, PropertyNode, PropertyValidation, TestExample, TypeNode } from "../../ir/ast.js";

function javaString(value: string): string {
  return JSON.stringify(value);
}

function javaTextBlock(name: string, lines: string[]): string[] {
  return [
    `    String ${name} = """`,
    ...lines.map(line => `      ${line.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"')}`),
    "      \"\"\";",
  ];
}

function className(typeName: string): string {
  return `${typeName}GeneratedTest`;
}

export function javaTestClassName(typeName: string): string {
  return className(typeName);
}

export function emitJavaTest(ctx: BaseTestContext): string {
  const typeName = ctx.node.typeName.name;
  const lines: string[] = [];
  lines.push("// Code generated by Typra emitter; DO NOT EDIT.");
  lines.push(`package ${ctx.package};`);
  lines.push("");
  lines.push(`final class ${className(typeName)} {`);
  lines.push("  private " + className(typeName) + "() { }");
  lines.push("");
  lines.push("  static void run() {");

  if (ctx.examples.length > 0) {
    ctx.examples.forEach((example, index) => {
      emitExampleTest(lines, typeName, ctx.node, example, index + 1);
    });
    emitInvalidJsonTest(lines, typeName);
  }

  ctx.coercions.forEach((coercion, index) => {
    emitCoercionTest(lines, typeName, coercion, index + 1);
  });

  if (ctx.node.properties.some(prop => prop.knownAs.length > 0) && ctx.examples.length > 0) {
    emitWireTest(lines, typeName, ctx.node, ctx.examples[0]);
  }

  lines.push("  }");
  emitAssertions(lines);
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export function emitJavaTestRunner(packageName: string, testClassNames: string[]): string {
  return [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    `package ${packageName};`,
    "",
    "public final class TypraGeneratedTests {",
    "  private TypraGeneratedTests() { }",
    "",
    "  public static void main(String[] args) {",
    ...testClassNames.map(name => `    ${name}.run();`),
    "  }",
    "}",
    "",
  ].join("\n");
}

function emitExampleTest(lines: string[], typeName: string, node: TypeNode, example: TestExample, index: number): void {
  lines.push("");
  lines.push(`    // ${typeName} example ${index}: fromJson, save, and reload`);
  const jsonData = `jsonData${index}`;
  lines.push(...javaTextBlock(jsonData, example.json));
  lines.push(`    ${typeName} instance${index} = ${typeName}.fromJson(${jsonData});`);
  emitExampleValidations(lines, `instance${index}`, node, example);
  lines.push(`    ${typeName} reloaded${index} = ${typeName}.load(instance${index}.save(new SaveContext()), new LoadContext());`);
  emitExampleValidations(lines, `reloaded${index}`, node, example);
}

function emitInvalidJsonTest(lines: string[], typeName: string): void {
  lines.push("");
  lines.push(`    assertThrows(() -> ${typeName}.fromJson("{"), "${typeName}.fromJson should reject malformed JSON");`);
}

function emitCoercionTest(lines: string[], typeName: string, coercion: CoercionTest, index: number): void {
  if (coercion.scalarType !== "string") return;
  lines.push("");
  const coerced = `coerced${index}`;
  lines.push(`    ${typeName} ${coerced} = ${typeName}.fromJson(${javaString(JSON.stringify(coercion.value))});`);
  for (const validation of coercion.validations) {
    emitValidation(lines, coerced, validation);
  }
}

function emitWireTest(lines: string[], typeName: string, node: TypeNode, example: TestExample): void {
  const mappings = node.properties.flatMap(prop => prop.knownAs.map(mapping => ({
    sourceName: prop.name,
    provider: mapping.provider,
    wireName: mapping.name,
  })));
  const providers = [...new Set(mappings.map(mapping => mapping.provider))];
  if (providers.length === 0) return;

  lines.push("");
  lines.push(`    ${typeName} wireInstance = ${typeName}.fromJson(${javaString(example.json.join("\n"))});`);
  for (const provider of providers) {
    lines.push(`    java.util.Map<String, Object> ${provider}Wire = wireInstance.toWire(${javaString(provider)});`);
    for (const mapping of mappings.filter(entry => entry.provider === provider)) {
      lines.push(`    assertTrue(${provider}Wire.containsKey(${javaString(mapping.wireName)}), "Expected ${provider} wire output to include ${mapping.wireName}");`);
      if (mapping.sourceName !== mapping.wireName) {
        lines.push(`    assertTrue(!${provider}Wire.containsKey(${javaString(mapping.sourceName)}), "Expected ${provider} wire output to omit ${mapping.sourceName}");`);
      }
    }
  }
}

function emitExampleValidations(lines: string[], varName: string, node: TypeNode, example: TestExample): void {
  for (const validation of example.validations) {
    emitValidation(lines, varName, validation);
  }
  emitStructuredValidations(lines, varName, node, example.sample);
}

function emitValidation(lines: string[], varName: string, validation: PropertyValidation): void {
  if (validation.delimiter === '"') {
    lines.push(`    assertEquals(${javaString(validation.value)}, ${varName}.${validation.key}, "Expected ${validation.key}");`);
    return;
  }

  const numeric = Number(validation.value);
  const expected = Number.isFinite(numeric) ? String(numeric) : validation.value;
  lines.push(`    assertEquals(${expected}, ${varName}.${validation.key}, "Expected ${validation.key}");`);
}

function emitStructuredValidations(lines: string[], varName: string, node: TypeNode, sample: Record<string, any>): void {
  for (const prop of node.properties) {
    if (!(prop.name in sample)) continue;
    const value = sample[prop.name];
    const expr = `${varName}.${prop.name}`;

    if (prop.isCollection && Array.isArray(value)) {
      lines.push(`    assertEquals(${value.length}, ${expr}.size(), "Expected ${prop.name} size");`);
      value.forEach((item, index) => {
        if (typeof item === "string") {
          lines.push(`    assertEquals(${javaString(item)}, ${expr}.get(${index}), "Expected ${prop.name}[${index}]");`);
        }
      });
      continue;
    }

    if (prop.isDict && value && typeof value === "object" && !Array.isArray(value)) {
      for (const [key, expected] of Object.entries(value)) {
        if (typeof expected === "string" || typeof expected === "number") {
          lines.push(`    assertEquals(${typeof expected === "number" ? expected : javaString(expected)}, ${expr}.get(${javaString(key)}), "Expected ${prop.name}.${key}");`);
        }
      }
      continue;
    }

    if (!prop.isScalar && prop.type && value && typeof value === "object" && !Array.isArray(value)) {
      const child = findSampleChildType(prop, value);
      if (child) {
        const local = `${varName}${capitalize(prop.name)}Value`;
        lines.push(`    assertTrue(${expr} instanceof ${child.typeName.name}, "Expected ${prop.name} to be ${child.typeName.name}");`);
        lines.push(`    ${child.typeName.name} ${local} = (${child.typeName.name}) ${expr};`);
        emitStructuredValidations(lines, local, child, value);
      } else {
        emitNestedValidations(lines, expr, prop.type, value);
      }
    }
  }
}

function emitNestedValidations(lines: string[], expr: string, node: TypeNode, sample: Record<string, any>): void {
  for (const prop of node.properties) {
    if (!(prop.name in sample)) continue;
    const expected = sample[prop.name];
    if (typeof expected === "string" || typeof expected === "number") {
      lines.push(`    assertEquals(${typeof expected === "number" ? expected : javaString(expected)}, ${expr}.${prop.name}, "Expected ${expr}.${prop.name}");`);
    }
  }
}

function findSampleChildType(prop: PropertyNode, sample: Record<string, any>): TypeNode | undefined {
  const discriminator = prop.type?.discriminator;
  if (!discriminator) return undefined;
  const discriminatorValue = sample[discriminator];
  return prop.type?.childTypes.find(child =>
    child.properties.some(childProp => childProp.name === discriminator && childProp.defaultValue === discriminatorValue)
  );
}

function emitAssertions(lines: string[]): void {
  lines.push("");
  lines.push("  private static void assertEquals(Object expected, Object actual, String message) {");
  lines.push("    if (expected instanceof Number expectedNumber && actual instanceof Number actualNumber) {");
  lines.push("      if (Math.abs(expectedNumber.doubleValue() - actualNumber.doubleValue()) < 0.000001d) return;");
  lines.push("    }");
  lines.push("    if (expected == null ? actual != null : !expected.equals(actual)) {");
  lines.push("      throw new AssertionError(message + \": expected \" + expected + \", got \" + actual);");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  private static void assertTrue(boolean condition, String message) {");
  lines.push("    if (!condition) throw new AssertionError(message);");
  lines.push("  }");
  lines.push("");
  lines.push("  private static void assertThrows(Runnable runnable, String message) {");
  lines.push("    try {");
  lines.push("      runnable.run();");
  lines.push("    } catch (RuntimeException expected) {");
  lines.push("      return;");
  lines.push("    }");
  lines.push("    throw new AssertionError(message);");
  lines.push("  }");
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
