import {
  BaseTestContext,
  CoercionTest,
  PropertyNode,
  PropertyValidation,
  TestExample,
  TypeNode,
} from "../../ir/ast.js";
import {
  javaEnumTypeName,
  javaPropertyName,
  javaTypeName,
} from "./identifiers.js";

function javaString(value: string): string {
  return JSON.stringify(value);
}

function javaTextBlock(name: string, lines: string[]): string[] {
  return [
    `    String ${name} = """`,
    ...lines.map(
      (line) =>
        `      ${line.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"')}`,
    ),
    '      """;',
  ];
}

function className(typeName: string): string {
  return `${javaTypeName(typeName)}GeneratedTest`;
}

export function javaTestClassName(typeName: string): string {
  return className(typeName);
}

type JavaNativeSerialization = "none" | "jackson";

export function emitJavaTest(
  ctx: BaseTestContext,
  nativeSerialization: JavaNativeSerialization = "none",
): string {
  const typeName = javaTypeName(ctx.node.typeName.name);
  const lines: string[] = [];
  lines.push("// Code generated by Typra emitter; DO NOT EDIT.");
  lines.push(`package ${ctx.package};`);
  lines.push("");
  lines.push(`final class ${className(typeName)} {`);
  lines.push("  private " + className(typeName) + "() { }");
  lines.push("");
  lines.push("  static void run() {");

  if (ctx.examples.length > 0) {
    ctx.examples.forEach((example, index) => {
      emitExampleTest(
        lines,
        typeName,
        ctx.node,
        example,
        index + 1,
        nativeSerialization,
      );
    });
    emitInvalidJsonTest(lines, typeName);
    emitInvalidYamlTest(lines, typeName);
    emitYamlEscapingTest(lines);
  }

  ctx.coercions.forEach((coercion, index) => {
    emitCoercionTest(
      lines,
      typeName,
      coercion,
      index + 1,
      ctx.node.coercions[index]?.expansion,
    );
  });

  if (
    ctx.node.properties.some((prop) => prop.knownAs.length > 0) &&
    ctx.examples.length > 0
  ) {
    emitWireTest(lines, typeName, ctx.node, ctx.examples[0]);
  }

  lines.push("  }");
  emitAssertions(lines, nativeSerialization);
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export function emitJavaTestRunner(
  packageName: string,
  testClassNames: string[],
): string {
  return [
    "// Code generated by Typra emitter; DO NOT EDIT.",
    `package ${packageName};`,
    "",
    "public final class TypraGeneratedTests {",
    "  private TypraGeneratedTests() { }",
    "",
    "  public static void main(String[] args) {",
    ...testClassNames.map((name) => `    ${name}.run();`),
    "  }",
    "}",
    "",
  ].join("\n");
}

function emitExampleTest(
  lines: string[],
  typeName: string,
  node: TypeNode,
  example: TestExample,
  index: number,
  nativeSerialization: JavaNativeSerialization,
): void {
  lines.push("");
  lines.push(
    `    // ${typeName} example ${index}: fromJson, fromYaml, save, and reload`,
  );
  const jsonData = `jsonData${index}`;
  lines.push(...javaTextBlock(jsonData, example.json));
  lines.push(
    `    ${typeName} instance${index} = ${typeName}.fromJson(${jsonData});`,
  );
  emitExampleValidations(lines, `instance${index}`, node, example);
  lines.push(`    String yamlRoundtrip${index} = instance${index}.toYaml();`);
  lines.push(
    `    ${typeName} fromYaml${index} = ${typeName}.fromYaml(yamlRoundtrip${index});`,
  );
  emitExampleValidations(lines, `fromYaml${index}`, node, example);
  lines.push(
    `    ${typeName} reloaded${index} = ${typeName}.load(instance${index}.save(new SaveContext()), new LoadContext());`,
  );
  emitExampleValidations(lines, `reloaded${index}`, node, example);
  if (nativeSerialization === "jackson") {
    lines.push(
      `    assertJacksonMatches(instance${index}, ${jsonData}, ${typeName}.class, "Expected Jackson to match Typra load/save for ${typeName} example ${index}");`,
    );
  }
}

function emitInvalidJsonTest(lines: string[], typeName: string): void {
  lines.push("");
  lines.push(
    `    assertThrows(() -> ${typeName}.fromJson("{"), "${typeName}.fromJson should reject malformed JSON");`,
  );
}

function emitInvalidYamlTest(lines: string[], typeName: string): void {
  lines.push("");
  lines.push(
    `    assertThrows(() -> ${typeName}.fromYaml(":\\n  broken"), "${typeName}.fromYaml should reject malformed YAML");`,
  );
}

function emitYamlEscapingTest(lines: string[]): void {
  lines.push("");
  lines.push(
    "    java.util.Map<String, Object> yamlControl = new java.util.LinkedHashMap<>();",
  );
  lines.push(
    "    String yamlControlValue = new String(new int[] { 0x0001, 0x0008, 0x000c, 0x1f642 }, 0, 4);",
  );
  lines.push('    yamlControl.put("value", yamlControlValue);');
  lines.push("    String yamlControlText = TypraYaml.stringify(yamlControl);");
  lines.push(
    `    assertTrue(yamlControlText.contains(${javaString("\\u0001")}), "YAML should unicode-escape C0 controls");`,
  );
  lines.push(
    `    assertTrue(yamlControlText.contains(${javaString("\\b")}), "YAML should escape backspace");`,
  );
  lines.push(
    `    assertTrue(yamlControlText.contains(${javaString("\\f")}), "YAML should escape form feed");`,
  );
  lines.push(
    `    Object yamlParsed = TypraYaml.parse(${javaString('value: "\\b\\f\\u0001\\uD83D\\uDE42"')});`,
  );
  lines.push(
    '    Object yamlValue = ((java.util.Map<?, ?>) yamlParsed).get("value");',
  );
  lines.push(
    "    String yamlParsedExpected = new String(new int[] { 0x0008, 0x000c, 0x0001, 0x1f642 }, 0, 4);",
  );
  lines.push(
    '    assertEquals(yamlParsedExpected, yamlValue, "YAML should decode named and unicode escapes");',
  );
  lines.push(
    `    assertThrows(() -> TypraYaml.parse(${javaString('value: "\\x"')}), "YAML should reject unknown escapes");`,
  );
}

function emitCoercionTest(
  lines: string[],
  typeName: string,
  coercion: CoercionTest,
  index: number,
  expansion: Record<string, unknown> | undefined,
): void {
  lines.push("");
  const directCases = javaDirectCoercionCases(coercion);
  directCases.forEach((testCase, caseIndex) => {
    const coerced = `coerced${index}_${caseIndex + 1}`;
    lines.push(
      `    ${typeName} ${coerced} = ${typeName}.load(${testCase.literal}, new LoadContext());`,
    );
    for (const validation of coercion.validations) {
      emitValidation(
        lines,
        coerced,
        expansion?.[validation.sourceKey ?? validation.key] === "{value}"
          ? { ...validation, value: testCase.expected, delimiter: "" }
          : validation,
      );
    }
  });
  if (coercion.scalarType.toLowerCase() !== "string") {
    return;
  }
  const stringValue = JSON.parse(coercion.value) as string;
  const coerced = `coercedJson${index}`;
  lines.push(
    `    ${typeName} ${coerced} = ${typeName}.fromJson(${javaString(JSON.stringify(stringValue))});`,
  );
  for (const validation of coercion.validations)
    emitValidation(lines, coerced, validation);
  const coercedYaml = `coercedYaml${index}`;
  lines.push(
    `    ${typeName} ${coercedYaml} = ${typeName}.fromYaml(${javaString(JSON.stringify(stringValue))});`,
  );
  for (const validation of coercion.validations)
    emitValidation(lines, coercedYaml, validation);
}

function javaDirectCoercionCases(
  coercion: CoercionTest,
): Array<{ literal: string; expected: string | number | boolean }> {
  switch (coercion.scalarType.toLowerCase()) {
    case "int32":
    case "int64":
    case "integer":
    case "long":
      return [
        { literal: "42", expected: 42 },
        { literal: "42L", expected: 42 },
      ];
    case "float":
    case "float32":
    case "float64":
    case "double":
    case "number":
    case "numeric":
      return [
        { literal: "3.14", expected: 3.14 },
        { literal: "3.14f", expected: 3.14 },
      ];
    default:
      return [{ literal: String(coercion.value), expected: coercion.value }];
  }
}

function emitWireTest(
  lines: string[],
  typeName: string,
  node: TypeNode,
  example: TestExample,
): void {
  const mappings = node.properties.flatMap((prop) =>
    prop.knownAs.map((mapping) => ({
      sourceName: prop.name,
      provider: mapping.provider,
      wireName: mapping.name,
    })),
  );
  const providers = [...new Set(mappings.map((mapping) => mapping.provider))];
  if (providers.length === 0) return;

  lines.push("");
  lines.push(
    `    ${typeName} wireInstance = ${typeName}.fromJson(${javaString(example.json.join("\n"))});`,
  );
  for (const provider of providers) {
    lines.push(
      `    java.util.Map<String, Object> ${provider}Wire = wireInstance.toWire(${javaString(provider)});`,
    );
    for (const mapping of mappings.filter(
      (entry) => entry.provider === provider,
    )) {
      lines.push(
        `    assertTrue(${provider}Wire.containsKey(${javaString(mapping.wireName)}), "Expected ${provider} wire output to include ${mapping.wireName}");`,
      );
      if (mapping.sourceName !== mapping.wireName) {
        lines.push(
          `    assertTrue(!${provider}Wire.containsKey(${javaString(mapping.sourceName)}), "Expected ${provider} wire output to omit ${mapping.sourceName}");`,
        );
      }
    }
  }
}

function emitExampleValidations(
  lines: string[],
  varName: string,
  node: TypeNode,
  example: TestExample,
): void {
  for (const validation of example.validations) {
    emitValidation(lines, varName, validation);
  }
  emitStructuredValidations(lines, varName, node, example.sample);
}

function emitValidation(
  lines: string[],
  varName: string,
  validation: PropertyValidation,
): void {
  if (validation.delimiter === '"') {
    lines.push(
      `    assertEquals(${javaString(validation.value)}, ${varName}.${javaPropertyName(validation.key)}, "Expected ${validation.key}");`,
    );
    return;
  }

  const numeric = Number(validation.value);
  const expected = Number.isFinite(numeric)
    ? String(numeric)
    : validation.value;
  lines.push(
    `    assertEquals(${expected}, ${varName}.${javaPropertyName(validation.key)}, "Expected ${validation.key}");`,
  );
}

function emitStructuredValidations(
  lines: string[],
  varName: string,
  node: TypeNode,
  sample: Record<string, any>,
  includeScalars = false,
  inheritedNode?: TypeNode,
): void {
  for (const prop of node.properties) {
    if (!(prop.name in sample)) continue;
    const value = sample[prop.name];
    const expr = `${varName}.${javaPropertyName(prop.name)}`;

    if (includeScalars && prop.isScalar && !prop.isCollection && !prop.isDict) {
      const emittedProp =
        inheritedNode?.discriminator === prop.name ||
        node.discriminator === prop.name
          ? undefined
          : (inheritedNode?.properties.find(
              (candidate) => candidate.name === prop.name,
            ) ?? prop);
      emitScalarSampleValidation(lines, expr, prop.name, value, emittedProp);
      continue;
    }

    if (!prop.isScalar && prop.type && typeof value === "string") {
      emitShorthandObjectValidation(lines, expr, prop.name, value, prop.type);
      continue;
    }

    if (
      prop.isCollection &&
      prop.isNamedCollection &&
      value &&
      typeof value === "object" &&
      !Array.isArray(value)
    ) {
      emitNamedCollectionMapValidation(
        lines,
        expr,
        prop.name,
        value,
        prop,
        node,
      );
      continue;
    }

    if (prop.isCollection && Array.isArray(value)) {
      emitCollectionValidation(lines, expr, prop.name, value, prop, node);
      continue;
    }

    if (
      prop.isDict &&
      value &&
      typeof value === "object" &&
      !Array.isArray(value)
    ) {
      for (const [key, expected] of Object.entries(value)) {
        if (typeof expected === "string" || typeof expected === "number") {
          lines.push(
            `    assertEquals(${typeof expected === "number" ? expected : javaString(expected)}, ${expr}.get(${javaString(key)}), "Expected ${prop.name}.${key}");`,
          );
        }
      }
      continue;
    }

    if (
      isPolymorphicProperty(prop) &&
      value &&
      typeof value === "object" &&
      !Array.isArray(value)
    ) {
      emitPolymorphicValidation(lines, expr, prop.name, value, prop, varName);
      continue;
    }

    if (
      !prop.isScalar &&
      prop.type &&
      value &&
      typeof value === "object" &&
      !Array.isArray(value)
    ) {
      emitNestedValidations(lines, expr, prop.type, value);
    }
  }
}

function emitNestedValidations(
  lines: string[],
  expr: string,
  node: TypeNode,
  sample: Record<string, any>,
): void {
  for (const prop of node.properties) {
    if (!(prop.name in sample)) continue;
    const expected = sample[prop.name];
    if (
      !prop.isScalar &&
      prop.type &&
      (typeof expected === "string" ||
        typeof expected === "number" ||
        typeof expected === "boolean")
    ) {
      emitShorthandObjectValidation(
        lines,
        `${expr}.${javaPropertyName(prop.name)}`,
        prop.name,
        expected,
        prop.type,
      );
      continue;
    }
    if (typeof expected === "string" || typeof expected === "number") {
      const emittedProp = node.discriminator === prop.name ? undefined : prop;
      lines.push(
        `    assertEquals(${javaExpectedLiteral(expected, emittedProp)}, ${expr}.${javaPropertyName(prop.name)}, "Expected ${expr}.${prop.name}");`,
      );
    }
  }
}

function emitCollectionValidation(
  lines: string[],
  expr: string,
  propName: string,
  values: any[],
  prop: PropertyNode,
  node: TypeNode,
): void {
  lines.push(
    `    assertEquals(${values.length}, ${expr}.size(), "Expected ${propName} size");`,
  );

  if (prop.isScalar) {
    values.forEach((item, index) => {
      emitScalarSampleValidation(
        lines,
        `${expr}.get(${index})`,
        `${propName}[${index}]`,
        item,
        prop,
      );
    });
    return;
  }

  const itemType = resolvePropertyType(node, prop);
  if (!itemType) return;

  values.forEach((item, index) => {
    const itemExpr = `${expr}.get(${index})`;
    if (
      typeof item === "string" ||
      typeof item === "number" ||
      typeof item === "boolean"
    ) {
      emitShorthandObjectValidation(
        lines,
        itemExpr,
        `${propName}[${index}]`,
        item,
        itemType,
      );
      return;
    }
    if (!item || typeof item !== "object" || Array.isArray(item)) return;
    const child = findSampleChildType(prop, item, itemType);
    if (child) {
      const local = `${localIdentifier(expr)}${index}Value`;
      lines.push(
        `    assertTrue(${itemExpr} instanceof ${child.typeName.name}, "Expected ${propName}[${index}] to be ${child.typeName.name}");`,
      );
      lines.push(
        `    ${child.typeName.name} ${local} = (${child.typeName.name}) ${itemExpr};`,
      );
      emitStructuredValidations(lines, local, child, item, true, itemType);
      return;
    }

    emitNestedValidations(lines, itemExpr, itemType, item);
  });
}

function emitNamedCollectionMapValidation(
  lines: string[],
  expr: string,
  propName: string,
  values: Record<string, any>,
  prop: PropertyNode,
  node: TypeNode,
): void {
  const entries = Object.entries(values);
  lines.push(
    `    assertEquals(${entries.length}, ${expr}.size(), "Expected ${propName} size");`,
  );
  const itemType = resolvePropertyType(node, prop);
  if (!itemType) return;

  entries.forEach(([key, item], index) => {
    const nameProperty = itemType.properties.find(
      (itemProp) => itemProp.name === "name",
    );
    const itemExpr = nameProperty
      ? `${localIdentifier(expr)}${index}Entry`
      : `${expr}.get(${index})`;
    if (nameProperty) {
      lines.push(
        `    ${javaTypeName(itemType.typeName.name)} ${itemExpr} = ${expr}.stream().filter(item -> ${javaString(key)}.equals(item.${javaPropertyName(nameProperty.name)})).findFirst().orElseThrow(() -> new AssertionError("Expected ${propName}.${key} entry"));`,
      );
      lines.push(
        `    assertEquals(${javaString(key)}, ${itemExpr}.${javaPropertyName(nameProperty.name)}, "Expected ${propName}.${key} name");`,
      );
    }
    if (
      typeof item === "string" ||
      typeof item === "number" ||
      typeof item === "boolean"
    ) {
      emitShorthandObjectValidation(
        lines,
        itemExpr,
        `${propName}.${key}`,
        item,
        itemType,
      );
      return;
    }
    if (!item || typeof item !== "object" || Array.isArray(item)) return;
    const child = findSampleChildType(prop, item, itemType);
    if (child) {
      const local = `${localIdentifier(expr)}${index}Value`;
      lines.push(
        `    assertTrue(${itemExpr} instanceof ${child.typeName.name}, "Expected ${propName}.${key} to be ${child.typeName.name}");`,
      );
      lines.push(
        `    ${child.typeName.name} ${local} = (${child.typeName.name}) ${itemExpr};`,
      );
      emitStructuredValidations(lines, local, child, item, true, itemType);
      return;
    }
    emitNestedValidations(lines, itemExpr, itemType, item);
  });
}

function emitPolymorphicValidation(
  lines: string[],
  expr: string,
  propName: string,
  value: Record<string, any>,
  prop: PropertyNode,
  varName: string,
): void {
  const child = findSampleChildType(prop, value);
  if (!child) return;

  const local = `${localIdentifier(varName)}${capitalize(localIdentifier(propName))}Value`;
  lines.push(
    `    assertTrue(${expr} instanceof ${child.typeName.name}, "Expected ${propName} to be ${child.typeName.name}");`,
  );
  lines.push(
    `    ${child.typeName.name} ${local} = (${child.typeName.name}) ${expr};`,
  );
  emitStructuredValidations(lines, local, child, value, true, prop.type);
}

function emitShorthandObjectValidation(
  lines: string[],
  expr: string,
  propName: string,
  expected: string | number | boolean,
  node: TypeNode,
): void {
  if (node.childTypes.length > 0) return;

  const shorthandField = findScalarCoercionField(node, typeof expected);
  if (!shorthandField) return;

  const shorthandProp = node.properties.find(
    (prop) => prop.name === shorthandField,
  );
  const emittedProp =
    node.discriminator === shorthandField ? undefined : shorthandProp;
  lines.push(
    `    assertEquals(${javaExpectedLiteral(expected, emittedProp)}, ${expr}.${javaPropertyName(shorthandField)}, "Expected ${propName}.${shorthandField}");`,
  );
}

function emitScalarSampleValidation(
  lines: string[],
  expr: string,
  displayName: string,
  expected: any,
  prop?: PropertyNode,
): void {
  if (
    typeof expected === "string" ||
    typeof expected === "number" ||
    typeof expected === "boolean"
  ) {
    lines.push(
      `    assertEquals(${javaExpectedLiteral(expected, prop)}, ${expr}, "Expected ${displayName}");`,
    );
  }
}

function findSampleChildType(
  prop: PropertyNode,
  sample: Record<string, any>,
  type = prop.type,
): TypeNode | undefined {
  const discriminator = type?.discriminator;
  const discriminatorValue = discriminator ? sample[discriminator] : undefined;
  if (discriminator && discriminatorValue !== undefined) {
    return type?.childTypes.find((child) =>
      child.properties.some(
        (childProp) =>
          childProp.name === discriminator &&
          childProp.defaultValue === discriminatorValue,
      ),
    );
  }

  return type?.childTypes.find((child) =>
    child.properties.some(
      (childProp) =>
        childProp.defaultValue !== null &&
        sample[childProp.name] === childProp.defaultValue,
    ),
  );
}

function resolvePropertyType(
  node: TypeNode,
  prop: PropertyNode,
): TypeNode | undefined {
  if (prop.type && prop.type.childTypes.length > 0) return prop.type;
  return findTypeByName(node, prop.typeName.name) ?? prop.type;
}

function findTypeByName(
  node: TypeNode,
  typeName: string,
  visited = new Set<TypeNode>(),
): TypeNode | undefined {
  if (visited.has(node)) return undefined;
  visited.add(node);
  if (node.typeName.name === typeName) return node;

  for (const child of node.childTypes) {
    const match = findTypeByName(child, typeName, visited);
    if (match) return match;
  }

  for (const prop of node.properties) {
    if (!prop.type) continue;
    const match = findTypeByName(prop.type, typeName, visited);
    if (match) return match;
  }

  return undefined;
}

function findScalarCoercionField(
  node: TypeNode,
  scalarType: string,
): string | undefined {
  const coercion = node.coercions.find((entry) =>
    scalarType === "number"
      ? [
          "int32",
          "int64",
          "integer",
          "number",
          "float",
          "numeric",
          "float32",
          "float64",
        ].includes(entry.scalar)
      : entry.scalar === scalarType,
  );
  if (!coercion) return undefined;

  for (const [key, value] of Object.entries(coercion.expansion)) {
    if (value === "{value}") return key;
  }

  return undefined;
}

function isPolymorphicProperty(prop: PropertyNode): boolean {
  return (
    !prop.isScalar &&
    !prop.isCollection &&
    !prop.isDict &&
    (prop.type?.childTypes.length ?? 0) > 0
  );
}

function javaLiteral(value: string | number | boolean): string {
  if (typeof value === "string") return javaString(value);
  return String(value);
}

function javaExpectedLiteral(
  value: string | number | boolean,
  prop?: PropertyNode,
): string {
  if (
    typeof value === "string" &&
    prop?.enumName &&
    !prop.isOpenEnum &&
    prop.allowedValues.length > 0
  ) {
    return `${javaEnumTypeName(prop.enumName)}.fromValue(${javaString(value)})`;
  }
  return javaLiteral(value);
}

function localIdentifier(expr: string): string {
  return expr
    .replace(/[^A-Za-z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part, index) => (index === 0 ? part : capitalize(part)))
    .join("");
}

function emitAssertions(
  lines: string[],
  nativeSerialization: JavaNativeSerialization,
): void {
  lines.push("");
  lines.push(
    "  private static void assertEquals(Object expected, Object actual, String message) {",
  );
  lines.push(
    "    if (expected instanceof Number expectedNumber && actual instanceof Number actualNumber) {",
  );
  lines.push(
    "      if (Math.abs(expectedNumber.doubleValue() - actualNumber.doubleValue()) < 0.000001d) return;",
  );
  lines.push("    }");
  lines.push(
    "    if (expected == null ? actual != null : !expected.equals(actual)) {",
  );
  lines.push(
    '      throw new AssertionError(message + ": expected " + expected + ", got " + actual);',
  );
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push(
    "  private static void assertTrue(boolean condition, String message) {",
  );
  lines.push("    if (!condition) throw new AssertionError(message);");
  lines.push("  }");
  lines.push("");
  lines.push(
    "  private static void assertThrows(Runnable runnable, String message) {",
  );
  lines.push("    try {");
  lines.push("      runnable.run();");
  lines.push("    } catch (RuntimeException expected) {");
  lines.push("      return;");
  lines.push("    }");
  lines.push("    throw new AssertionError(message);");
  lines.push("  }");
  if (nativeSerialization === "jackson") {
    lines.push("");
    lines.push(
      "  private static <T> void assertJacksonMatches(T instance, String sourceJson, Class<T> type, String message) {",
    );
    lines.push("    try {");
    lines.push(
      "      com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();",
    );
    lines.push(
      '      String typraJson = (String) type.getMethod("toJson").invoke(instance);',
    );
    lines.push(
      "      String jacksonJson = mapper.writeValueAsString(instance);",
    );
    lines.push(
      '      assertEquals(mapper.readValue(typraJson, Object.class), mapper.readValue(jacksonJson, Object.class), message + " serialization");',
    );
    lines.push("      T jacksonLoaded = mapper.readValue(sourceJson, type);");
    lines.push(
      '      String jacksonLoadedJson = (String) type.getMethod("toJson").invoke(jacksonLoaded);',
    );
    lines.push(
      '      assertEquals(mapper.readValue(typraJson, Object.class), mapper.readValue(jacksonLoadedJson, Object.class), message + " deserialization");',
    );
    lines.push(
      "    } catch (ReflectiveOperationException | java.io.IOException error) {",
    );
    lines.push("      throw new AssertionError(message, error);");
    lines.push("    }");
    lines.push("  }");
  }
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
