/**
 * Python code emitter — Declaration IR → Python source code.
 *
 * Replaces `file.py.njk` + `_macros.njk` (~619 lines of Nunjucks templates)
 * with a typed TypeScript function that walks the FileDecl tree.
 *
 * The emitter produces correctly-formatted Python 3.11+ code using modern
 * `X | None` union syntax. Output should be byte-identical to the template
 * output after ruff+black formatting.
 *
 * Structural blocks emitted (in order):
 *   1. Header comment (auto-generated warning)
 *   2. Imports (abc, dataclasses/pydantic, typing, context, local types)
 *   3. For each type in the file:
 *      a. @dataclass or BaseModel class definition with docstring
 *      b. _shorthand_property ClassVar
 *      c. Field declarations with type annotations + defaults
 *      d. load() static method
 *      e. Collection helpers (load_X / save_X)
 *      f. Polymorphic dispatch (load_<discriminator>)
 *      g. save() instance method
 *      h. to_yaml() and to_json() methods
 *      i. Factory classmethods
 *      j. Method stubs (as comments)
 */

import {
  FileDecl,
  TypeDecl,
  FieldDecl,
  LoadAssignment,
  SaveAssignment,
  CollectionHelperDecl,
  PolymorphicDispatchDecl,
  FactoryDecl,
  CoercionDecl,
  PropertyCategory,
  WireFieldMapping,
  isClosedPolymorphicDispatch,
} from "../../ir/declarations.js";
import {
  orderedEntryShorthandCases,
  entryShorthandTarget,
  isIntegralScalar,
  isFractionalScalar,
  isStringEncodedScalar,
  isBooleanScalar,
} from "../../ir/scalar-kinds.js";
import { ExprVisitor } from "../../ir/visitor.js";
import { toSnakeCase } from "../../ir/utilities.js";

/**
 * Type mapping from TypeSpec scalar types to Python types.
 */
const TYPE_MAP: Record<string, string> = {
  "string": "str",
  "number": "float",
  "array": "list",
  "object": "dict",
  "boolean": "bool",
  "int64": "int",
  "int32": "int",
  "float64": "float",
  "float32": "float",
  "integer": "int",
  "float": "float",
  "numeric": "float",
  "any": "Any",
  "dictionary": "dict[str, Any]",
};

function paramType(typeStr: string): string {
  if (typeStr === "string") return "str";
  if (typeStr === "boolean") return "bool";
  if (typeStr === "integer" || typeStr === "int32" || typeStr === "int64") return "int";
  if (typeStr === "float" || typeStr === "float64" || typeStr === "float32") return "float";
  return "Any";
}

function returnType(typeStr: string): string {
  if (typeStr === "string") return "str";
  if (typeStr === "boolean") return "bool";
  if (typeStr === "integer" || typeStr === "int32" || typeStr === "int64") return "int";
  if (typeStr === "float" || typeStr === "float64" || typeStr === "float32") return "float";
  return typeStr;
}

// ============================================================================
// Main entry point
// ============================================================================

/**
 * Emit a complete Python file from a FileDecl.
 */
export interface PythonEmitterOptions {
  cancellationTokenPath?: string;
  nativeSerialization?: "none" | "pydantic";
}

export function emitPythonFile(
  decl: FileDecl,
  visitor: ExprVisitor,
  group: string = "",
  options: PythonEmitterOptions = {},
): string {
  const lines: string[] = [];

  // 1. Header
  lines.push("##########################################");
  lines.push("# WARNING: This is an auto-generated file.");
  lines.push("# DO NOT EDIT THIS FILE DIRECTLY");
  lines.push("# ANY EDITS WILL BE LOST");
  lines.push("##########################################");
  lines.push("");

  // 2. Imports — sorted alphabetically as ruff/isort would
  // Collect all import lines, then sort them
  const stdlibImports: string[] = [];
  const localImports: string[] = [];
  const hasProtocol = decl.types.some(t => t.isProtocol);
  const hasNonProtocol = decl.types.some(t => !t.isProtocol);
  const hasMethodHelpers = decl.types.some(t => !t.isProtocol && t.methods.length > 0);
  const hasRuntimeCancellation = decl.types.some(type =>
    type.methods.some(method => method.runtimeCancellable),
  );
  const preservesRawPayload = decl.types.some(type =>
    absorbsUnknownValues(type.polymorphicDispatch),
  );
  const usePydantic = options.nativeSerialization === "pydantic";

  if (preservesRawPayload) {
    stdlibImports.push("import copy");
  }
  if (decl.containsAbstract) {
    stdlibImports.push("from abc import ABC");
  }
  if (hasNonProtocol && !usePydantic) {
    stdlibImports.push("from dataclasses import dataclass, field");
  }
  const pydanticImports = ["BaseModel", "ConfigDict", "Field"];
  if (preservesRawPayload) {
    pydanticImports.push("PrivateAttr");
  }
  if (hasNonProtocol && usePydantic) {
    localImports.push(`from pydantic import ${pydanticImports.sort().join(", ")}`);
  }
  const typingImports = ["Any"];
  if (hasNonProtocol) typingImports.push("ClassVar");
  if (decl.enums.length > 0) typingImports.push("Literal");
  if (hasProtocol || hasMethodHelpers) typingImports.push("Protocol", "runtime_checkable");
  typingImports.sort();
  stdlibImports.push(`from typing import ${typingImports.join(", ")}`);
  if (hasRuntimeCancellation) {
    localImports.push(
      pythonCancellationTokenImport(
        options.cancellationTokenPath ?? "prompty.core.cancellation.CancellationToken",
      ),
    );
  }

  function pythonCancellationTokenImport(path: string): string {
    const separator = path.lastIndexOf(".");
    if (separator < 1 || separator === path.length - 1) {
      throw new Error(`Invalid Python cancellation-token-path: ${path}`);
    }
    const moduleName = path.slice(0, separator);
    const symbolName = path.slice(separator + 1);
    const alias = symbolName === "CancellationToken" ? "" : " as CancellationToken";
    return `from ${moduleName} import ${symbolName}${alias}`;
  }

  // Context import — go up one level when inside a group subfolder
  if (hasNonProtocol) {
    const ctxPrefix = group ? ".." : ".";
    localImports.push(`from ${ctxPrefix}_context import LoadContext, SaveContext`);
  }

  // Cross-group and same-group type imports
  for (const imp of decl.imports) {
    if (imp.group === group) {
      // Same group (or both root): relative sibling import
      localImports.push(`from ._${imp.module} import ${imp.names.join(", ")}`);
    } else if (imp.group) {
      // Different non-empty group: go up to model root, then into the group subfolder
      localImports.push(`from ..${imp.group}._${imp.module} import ${imp.names.join(", ")}`);
    } else {
      // Imported module is at model root (no group): go up one level
      localImports.push(`from .._${imp.module} import ${imp.names.join(", ")}`);
    }
  }
  localImports.sort();

  for (const line of stdlibImports) {
    lines.push(line);
  }
  lines.push("");
  for (const line of localImports) {
    lines.push(line);
  }

  // 2.5. Enum type aliases
  if (decl.enums.length > 0) {
    lines.push("");
    for (const enumDef of decl.enums) {
      const values = enumDef.values.map(v => `"${v}"`).join(", ");
      if (enumDef.isOpen) {
        // Open enum — Literal values or any str
        lines.push(`${enumDef.name} = Literal[${values}] | str`);
      } else {
        lines.push(`${enumDef.name} = Literal[${values}]`);
      }
    }
    for (const enumDef of decl.enums) {
      emitEnumParser(enumDef, lines);
    }
  }

  // 3. Emit each type
  for (const type of decl.types) {
    lines.push("");
    lines.push("");
    emitType(type, lines, visitor, options);
  }

  return pruneUnusedTypingImports(emitCleanPythonLines(lines, "\n"));
}

function hasParseAliases(enumDef: { parseAliases: Record<string, string[]> }): boolean {
  return Object.values(enumDef.parseAliases).some(aliases => aliases.length > 0);
}

function enumParserName(enumName: string): string {
  return `_parse_${toSnakeCase(enumName)}`;
}

function emitEnumParser(enumDef: { name: string; values: string[]; parseAliases: Record<string, string[]>; isOpen: boolean }, lines: string[]): void {
  if (!hasParseAliases(enumDef)) return;
  lines.push("");
  lines.push(`def ${enumParserName(enumDef.name)}(value: Any) -> ${enumDef.name}:`);
  lines.push("    text = str(value)");
  lines.push("    aliases = {");
  for (const value of enumDef.values) {
    lines.push(`        ${JSON.stringify(value)}: ${JSON.stringify(value)},`);
  }
  for (const [canonical, aliases] of Object.entries(enumDef.parseAliases)) {
    for (const alias of aliases) {
      lines.push(`        ${JSON.stringify(alias)}: ${JSON.stringify(canonical)},`);
    }
  }
  lines.push("    }");
  if (enumDef.isOpen) {
    lines.push("    return aliases.get(text, text)");
  } else {
    lines.push("    if text in aliases:");
    lines.push("        return aliases[text]");
    lines.push(`    raise ValueError(f"Invalid ${enumDef.name} value: {text}")`);
  }
}

function emitCleanPythonLines(lines: string[], suffix = ""): string {
  return lines.map(line => line.trimEnd()).join("\n") + suffix;
}

function pruneUnusedTypingImports(source: string): string {
  const match = /^from typing import (?<names>[A-Za-z_, ]+)$/m.exec(source);
  if (!match?.groups) {
    return source;
  }

  const names = match.groups.names.split(",").map(name => name.trim()).filter(Boolean);
  const body = `${source.slice(0, match.index)}${source.slice(match.index + match[0].length)}`;
  const usedNames = names.filter(name => new RegExp(`\\b${escapeRegExp(name)}\\b`).test(body));

  if (usedNames.length === names.length) {
    return source;
  }

  return `${source.slice(0, match.index)}${usedNames.length > 0 ? `from typing import ${usedNames.join(", ")}` : ""}${source.slice(match.index + match[0].length)}`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[|\\{}()[\]^$+?.]/g, "\\$&");
}

// ============================================================================
// Type emission
// ============================================================================

const PYDANTIC_RESERVED_FIELD_NAMES = new Set([
  "model_config",
  "model_dump",
  "model_dump_json",
  "model_validate",
]);

function assertNoPydanticReservedFieldNames(type: TypeDecl): void {
  for (const field of type.fields) {
    const attributeName = toSnakeCase(field.name);
    if (PYDANTIC_RESERVED_FIELD_NAMES.has(attributeName)) {
      throw new Error(
        `Python native-serialization 'pydantic' cannot emit ${type.typeName.name}.${field.name}: `
        + `the Python attribute '${attributeName}' is reserved by Pydantic/Typra interop. `
        + "Rename the TypeSpec property or use native-serialization: 'none'.",
      );
    }
  }
}

function emitType(type: TypeDecl, lines: string[], visitor: ExprVisitor, options: PythonEmitterOptions): void {
  const name = type.typeName.name;
  const usePydantic = options.nativeSerialization === "pydantic";

  // Protocol types → emit as Protocol class with method signatures
  if (type.isProtocol) {
    emitProtocolClass(type, lines);
    return;
  }
  if (usePydantic) {
    assertNoPydanticReservedFieldNames(type);
  }

  // Class definition
  const bases: string[] = [];
  if (type.base) bases.push(type.base.name);
  if (usePydantic && !type.base) bases.push("BaseModel");
  if (type.isAbstract) bases.push("ABC");
  const baseSuffix = bases.length > 0 ? `(${bases.join(", ")})` : "";
  if (!usePydantic) {
    lines.push("@dataclass");
  }
  lines.push(`class ${name}${baseSuffix}:`);

  // Docstring
  emitDocstring(type, lines);

  // _shorthand_property ClassVar
  lines.push("");
  const shorthand = type.coercionProperty ? `"${type.coercionProperty}"` : "None";
  lines.push(`    _shorthand_property: ClassVar[str | None] = ${shorthand}`);
  if (usePydantic) {
    lines.push("    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)");
  }

  // Field declarations (blank line between _shorthand and first field)
  lines.push("");
  const saveTargets = new Map(type.save.assignments.map(a => [a.fieldName, a.targetName]));
  for (const field of type.fields) {
    const wireName = saveTargets.get(field.name) ?? field.name;
    lines.push(`    ${toSnakeCase(field.name)}: ${pythonTypeAnnotation(field)}${pythonDefaultValue(field, options, wireName)}`);
  }
  if (absorbsUnknownValues(type.polymorphicDispatch)) {
    lines.push(usePydantic
      ? "    _raw: dict[str, Any] = PrivateAttr(default_factory=dict)"
      : "    _raw: dict[str, Any] = field(default_factory=dict, init=False, repr=False)");
  }

  // load() method
  lines.push("");
  emitLoadMethod(type, lines);

  // Collection helpers (between load and polymorphic dispatch)
  for (const helper of type.collectionHelpers) {
    emitCollectionLoadHelper(name, helper, lines);
    lines.push("");
    emitCollectionSaveHelper(name, helper, lines);
  }

  // Polymorphic dispatch
  if (type.polymorphicDispatch) {
    lines.push("");
    lines.push("");
    emitPolymorphicDispatch(
      name,
      type.polymorphicDispatch,
      type.isAbstract,
      lines,
      needsUnknownCarrier(type) ? unknownCarrierName(name) : undefined,
    );
  }

  // save() method
  lines.push("");
  emitSaveMethod(type, lines);

  // to_wire() method (only when wire mappings exist)
  if (type.wire) {
    emitToWireMethod(type, lines);
  }

  // to_yaml() method
  emitToYaml(name, lines);

  // to_json() method
  emitToJson(name, lines);

  if (usePydantic) {
    emitPydanticInteropMethods(name, lines);
  }

  // Factory methods
  if (type.factories.length > 0) {
    const fieldNames = new Set(type.fields.map(f => f.name));
    lines.push("");
    for (const factory of type.factories) {
      emitFactory(name, factory, visitor, fieldNames, lines);
      lines.push("");
    }
  }

  lines.push("");

  if (needsUnknownCarrier(type)) {
    emitUnknownCarrier(type, lines, options);
  }

  // Method stubs — emit as a sibling Protocol class outside the dataclass
  if (type.methods.length > 0) {
    emitMethodHelpersProtocol(type, lines);
  }
}

/**
 * Emit the concrete carrier for an abstract base whose discriminator is open.
 *
 * Rust models polymorphism as an enum and adds an `Unknown { kind_name, raw }` variant.
 * Python models it as class inheritance over an `ABC`, so the equivalent is a concrete
 * subclass: the base keeps its `ABC` marker, honouring the schema's `@abstract`, and
 * unrecognized discriminator values land here rather than raising.
 *
 * The carrier declares no discriminator field of its own. `<T>.load` calls `load_<disc>`
 * first and then applies the base's own assignments to whatever instance came back, so the
 * exact unrecognized value is already preserved by the time this instance is returned.
 * It needs no `save` either: the base's `save` seeds its result from `_raw`.
 */
function emitUnknownCarrier(type: TypeDecl, lines: string[], options: PythonEmitterOptions): void {
  const parentName = type.typeName.name;
  const carrier = unknownCarrierName(parentName);

  if (options.nativeSerialization !== "pydantic") {
    lines.push("@dataclass");
  }
  lines.push(`class ${carrier}(${parentName}):`);
  lines.push(`    """Carries a ${parentName} whose discriminator matches no known subtype.`);
  lines.push("");
  lines.push(`    The unrecognized value stays on \`${toSnakeCase(type.polymorphicDispatch!.discriminatorField)}\` and every key the`);
  lines.push(`    schema does not declare is preserved verbatim, so an unknown ${parentName}`);
  lines.push("    survives a load/save round-trip unchanged.");
  lines.push("");
  lines.push('    """');
  lines.push("");
  lines.push("    @staticmethod");
  lines.push(`    def load(data: Any, context: LoadContext | None = None) -> "${carrier}":`);
  lines.push(`        instance = ${carrier}()`);
  lines.push("        instance._raw = copy.deepcopy(data)");
  for (const a of type.load.assignments) {
    lines.push(`        instance._raw.pop("${a.sourceName}", None)`);
  }
  lines.push("        return instance");
  lines.push("");
  lines.push("");
}

/**
 * Emit a typing.Protocol class named `<TypeName>Helpers` that declares the
 * `@method` contract for a concrete type. The generated dataclass does NOT
 * satisfy this Protocol on its own — runtime code must provide an
 * implementation (either by attaching methods to the class or by providing
 * a wrapper type). Using `@runtime_checkable` allows isinstance() checks.
 */
function emitMethodHelpersProtocol(type: TypeDecl, lines: string[]): void {
  const name = type.typeName.name;
  lines.push("");
  lines.push("");
  lines.push("@runtime_checkable");
  lines.push(`class ${name}Helpers(Protocol):`);
  lines.push(`    """Helper contract for ${name}.`);
  lines.push("");
  lines.push(`    Runtime implementations must provide these methods on every ${name}`);
  lines.push("    instance (either by attaching them to the generated class or by wrapping it).");
  lines.push("    The type checker can verify conformance by annotating against this Protocol");
  lines.push(`    or by calling isinstance(instance, ${name}Helpers) at runtime.`);
  lines.push(`    """`);
  for (const m of type.methods) {
    const params = Object.entries(m.params)
      .map(([pName, pType]) => `${toSnakeCase(pName)}: ${protocolType(pType)}`)
    if (m.runtimeCancellable) {
      params.push("cancellation: CancellationToken | None = None");
    }
    const paramList = params.length > 0 ? `, ${params.join(", ")}` : "";
    const ret = protocolType(m.returns);
    const snakeName = toSnakeCase(m.name);
    // Zero-param, non-verb methods are emitted as @property — idiomatic Python
    // for accessor-style helpers (matches the C# emitter's heuristic).
    const isProperty = Object.keys(m.params).length === 0 && !m.runtimeCancellable && !isMethodStyle(m.name);
    lines.push("");
    if (isProperty) {
      lines.push("    @property");
    }
    lines.push(`    def ${snakeName}(self${paramList}) -> ${ret}:`);
    if (m.description) {
      lines.push(`        """${m.description}"""`);
    }
    emitRequiredProtocolMethodBody(lines);
  }
}

/**
 * Verbs that indicate an action — zero-param @methods whose name starts with
 * one of these are emitted as regular Python methods. Everything else becomes
 * a ``@property``. Mirrors the C# emitter's heuristic so both runtimes expose
 * ``message.text`` as a property and ``message.to_text_content()`` as a method.
 */
const PY_METHOD_VERB_PREFIXES = [
  "to", "get", "set", "fetch", "compute", "make", "build", "create",
  "load", "save", "convert", "parse", "format", "render", "serialize",
  "deserialize", "find", "calculate", "invoke", "execute", "run",
];

function isMethodStyle(name: string): boolean {
  const lower = name.toLowerCase();
  for (const prefix of PY_METHOD_VERB_PREFIXES) {
    if (lower === prefix) return true;
    if (lower.startsWith(prefix) && name.length > prefix.length) {
      const next = name[prefix.length];
      if (next === next.toUpperCase() && next !== next.toLowerCase()) {
        return true;
      }
    }
  }
  return false;
}

// ============================================================================
// Protocol class emission
// ============================================================================

/** Map a protocol type string to a Python type annotation. */
function protocolType(typeStr: string): string {
  // Handle nullable types
  if (typeStr.endsWith("?")) {
    const inner = typeStr.slice(0, -1);
    return `${protocolType(inner)} | None`;
  }
  // Handle array types
  if (typeStr.endsWith("[]")) {
    const inner = typeStr.slice(0, -2);
    return `list[${protocolType(inner)}]`;
  }
  // Handle Record/dict types
  if (typeStr === "Record<unknown>" || typeStr === "dictionary") return "dict[str, Any]";
  if (typeStr === "unknown" || typeStr === "any") return "Any";
  if (typeStr === "void") return "None";
  // Scalar types
  const mapped = TYPE_MAP[typeStr];
  if (mapped) return mapped;
  return typeStr;
}

/**
 * Emit a Python Protocol class for a protocol type.
 * Uses typing.Protocol for structural subtyping.
 */
function emitProtocolClass(type: TypeDecl, lines: string[]): void {
  const name = type.typeName.name;

  lines.push("@runtime_checkable");
  lines.push(`class ${name}(Protocol):`);

  // Docstring
  if (type.description) {
    const descLines = type.description.split("\n");
    lines.push(`    """${descLines[0]}`);
    for (let i = 1; i < descLines.length; i++) {
      lines.push(`    ${descLines[i]}`);
    }
    lines.push(`    """`);
  }

  if (type.methods.length === 0) {
    lines.push("    pass");
    return;
  }

  for (const method of type.methods) {
    const params = Object.entries(method.params)
      .map(([pName, pType]) => `${toSnakeCase(pName)}: ${protocolType(pType)}`)
    if (method.runtimeCancellable) {
      params.push("cancellation: CancellationToken | None = None");
    }
    const paramList = params.length > 0 ? `, ${params.join(", ")}` : "";
    const ret = protocolType(method.returns);

    // Sync method
    lines.push("");
    if (method.description) {
      lines.push(`    def ${toSnakeCase(method.name)}(self${paramList}) -> ${ret}:`);
      lines.push(`        """${method.description}"""`);
      if (method.optional) {
        lines.push("        return None");
      } else {
        emitRequiredProtocolMethodBody(lines);
      }
    } else {
      if (method.optional) {
        lines.push(`    def ${toSnakeCase(method.name)}(self${paramList}) -> ${ret}:`);
        lines.push("        return None");
      } else {
        lines.push(`    def ${toSnakeCase(method.name)}(self${paramList}) -> ${ret}:`);
        emitRequiredProtocolMethodBody(lines);
      }
    }

    // Async variant (skip for sync-only methods)
    if (!method.sync) {
      lines.push("");
      if (method.description) {
        lines.push(`    async def ${toSnakeCase(method.name)}_async(self${paramList}) -> ${ret}:`);
        lines.push(`        """${method.description} (async variant)"""`);
        if (method.optional) {
          lines.push("        return None");
        } else {
          emitRequiredProtocolMethodBody(lines);
        }
      } else {
        if (method.optional) {
          lines.push(`    async def ${toSnakeCase(method.name)}_async(self${paramList}) -> ${ret}:`);
          lines.push("        return None");
        } else {
          lines.push(`    async def ${toSnakeCase(method.name)}_async(self${paramList}) -> ${ret}:`);
          emitRequiredProtocolMethodBody(lines);
        }
      }
    }
  }

  lines.push("");
}

function emitRequiredProtocolMethodBody(lines: string[]): void {
  lines.push("        raise NotImplementedError");
}

// ============================================================================
// Docstring
// ============================================================================

function emitDocstring(type: TypeDecl, lines: string[]): void {
  const descLines = type.description.split("\n");
  lines.push(`    """${descLines[0]}`);
  for (let i = 1; i < descLines.length; i++) {
    lines.push(`    ${descLines[i]}`);
  }

  if (type.fields.length > 0) {
    lines.push("    ");
    lines.push("    Attributes");
    lines.push("    ----------");
    for (const f of type.fields) {
      lines.push(`    ${toSnakeCase(f.name)} : ${pythonDocstringType(f)}`);
      lines.push(`        ${f.description}`);
    }
  }
  lines.push(`    """`);
}

// ============================================================================
// Type annotations — uses modern X | None syntax
// ============================================================================

function pythonTypeAnnotation(f: FieldDecl): string {
  // Named enum field — use the enum type alias
  if (f.enumName && f.allowedValues.length > 0) {
    return f.isOptional ? `${f.enumName} | None` : f.enumName;
  }
  const cat = f.category;
  switch (cat.kind) {
    case "dict":
      return f.isOptional
        ? `dict[str, ${pythonRecordValueType(cat.valueType)}] | None`
        : `dict[str, ${pythonRecordValueType(cat.valueType)}]`;
    case "collection_scalar": {
      const pyType = `list[${TYPE_MAP[cat.scalarType] || "Any"}]`;
      return f.isOptional ? `${pyType} | None` : pyType;
    }
    case "collection_complex": {
      const pyType = `list[${cat.typeName}]`;
      return f.isOptional ? `${pyType} | None` : pyType;
    }
    case "scalar": {
      const pyType = TYPE_MAP[cat.scalarType] || "Any";
      return f.isOptional ? `${pyType} | None` : pyType;
    }
    case "complex":
      return f.isOptional ? `${cat.typeName} | None` : cat.typeName;
  }
}

function pythonRecordValueType(valueType: string | undefined): string {
  if (!valueType || valueType === "unknown") return "Any";
  return TYPE_MAP[valueType] || valueType;
}

function pythonDocstringType(f: FieldDecl): string {
  const cat = f.category;
  let baseType: string;
  switch (cat.kind) {
    case "dict":
      baseType = `dict[str, ${pythonRecordValueType(cat.valueType)}]`;
      break;
    case "collection_scalar":
      baseType = `list[${TYPE_MAP[cat.scalarType] || "Any"}]`;
      break;
    case "collection_complex":
      baseType = `list[${cat.typeName}]`;
      break;
    case "scalar":
      baseType = TYPE_MAP[cat.scalarType] || "Any";
      break;
    case "complex":
      baseType = cat.typeName;
      break;
  }
  if (f.isOptional) return `Optional[${baseType}]`;
  return baseType;
}

// ============================================================================
// Default values
// ============================================================================

function pythonDefaultValue(f: FieldDecl, options: PythonEmitterOptions = {}, wireName?: string): string {
  if (options.nativeSerialization === "pydantic") {
    return pydanticDefaultValue(f, wireName ?? f.name);
  }

  const cat = f.category;

  if (cat.kind === "collection_scalar" || cat.kind === "collection_complex") {
    return f.isOptional && !f.hasExplicitDefault ? " = None" : " = field(default_factory=list)";
  }

  if (f.isOptional) {
    return " = None";
  }

  function pydanticDefaultValue(f: FieldDecl, wireName: string): string {
    const cat = f.category;
    const args: string[] = [];

    if (cat.kind === "collection_scalar" || cat.kind === "collection_complex") {
      if (f.isOptional && !f.hasExplicitDefault) {
        args.push("default=None");
      } else {
        args.push("default_factory=list");
      }
    } else if (f.isOptional) {
      args.push("default=None");
    } else if (f.enumName && f.allowedValues.length > 0) {
      const dv = typeof f.defaultValue === "string" && f.allowedValues.includes(f.defaultValue)
        ? f.defaultValue
        : f.allowedValues[0];
      args.push(`default=${JSON.stringify(dv)}`);
    } else if (cat.kind === "scalar") {
      const t = cat.scalarType;
      if (t === "boolean") {
        args.push(`default=${f.defaultValue ? "True" : "False"}`);
      } else if (t === "string") {
        args.push(`default=${JSON.stringify(f.defaultValue ?? "")}`);
      } else if (t === "number" || t === "numeric" || t === "float64" || t === "float32" || t === "float") {
        args.push(`default=${f.defaultValue ?? "0.0"}`);
      } else if (t === "int64" || t === "int32" || t === "integer") {
        args.push(`default=${f.defaultValue ?? "0"}`);
      } else if (t === "dictionary") {
        args.push("default_factory=dict");
      } else {
        args.push(`default=${f.defaultValue ?? "None"}`);
      }
    } else if (cat.kind === "dict") {
      args.push("default_factory=dict");
    } else if (cat.kind === "complex") {
      args.push(`default_factory=${f.typeName.name}`);
    } else {
      args.push("default=None");
    }

    args.push(`alias=${JSON.stringify(wireName)}`);
    return ` = Field(${args.join(", ")})`;
  }

  // Enum fields — use the field's default value or the first allowed value
  if (f.enumName && f.allowedValues.length > 0) {
    const dv = typeof f.defaultValue === "string" && f.allowedValues.includes(f.defaultValue)
      ? f.defaultValue
      : f.allowedValues[0];
    return ` = field(default="${dv}")`;
  }

  if (cat.kind === "scalar") {
    const t = cat.scalarType;
    if (t === "boolean") {
      return ` = field(default=${f.defaultValue ? "True" : "False"})`;
    }
    if (t === "string") {
      return ` = field(default="${f.defaultValue ?? ""}")`;
    }
    if (t === "number" || t === "numeric" || t === "float64" || t === "float32" || t === "float") {
      return ` = field(default=${f.defaultValue ?? "0.0"})`;
    }
    if (t === "int64" || t === "int32" || t === "integer") {
      return ` = field(default=${f.defaultValue ?? "0"})`;
    }
    if (t === "dictionary") {
      return " = field(default_factory=dict)";
    }
    return ` = field(default=${f.defaultValue ?? "None"})`;
  }

  if (cat.kind === "dict") {
    return " = field(default_factory=dict)";
  }

  if (cat.kind === "complex") {
    return ` = field(default_factory=${f.typeName.name})`;
  }

  return " = None";
}

// ============================================================================
// load() method
// ============================================================================

function emitLoadMethod(type: TypeDecl, lines: string[]): void {
  const name = type.typeName.name;

  lines.push("    @staticmethod");
  lines.push(`    def load(data: Any, context: LoadContext | None = None) -> "${name}":`);
  lines.push(`        """Load a ${name} instance.`);
  lines.push("        Args:");
  lines.push("            data (Any): The data to load the instance from.");
  lines.push("            context (Optional[LoadContext]): Optional context with pre/post processing callbacks.");
  lines.push("        Returns:");
  lines.push(`            ${name}: The loaded ${name} instance.`);
  lines.push("");
  lines.push(`        """`);
  lines.push("");
  lines.push("        if context is None:");
  lines.push("            context = LoadContext()");
  lines.push("        data = context.process_input(data)");

  // Coercion checks — direct property setting instead of dict construction
  if (type.load.coercions.length > 0) {
    lines.push("        ");
    lines.push("        # handle alternate representations");
    for (const c of type.load.coercions) {
      emitCoercionBranch(name, c, type, lines);
    }
  }

  lines.push("        ");
  lines.push(`        if not isinstance(data, dict):`);
  lines.push(`            raise ValueError(f"Invalid data for ${name}: {data}")`);

  for (const a of type.load.assignments) {
    const field = type.fields.find(candidate => candidate.name === a.fieldName);
    if (field?.category.kind !== "complex" || field.isOptional || field.hasExplicitDefault) continue;
    lines.push(`        if "${a.sourceName}" not in data or data["${a.sourceName}"] is None:`);
    lines.push(`            raise ValueError(f"{context.at('${a.sourceName}').path}: missing required field")`);
  }

  // Create instance (polymorphic dispatch or direct)
  if (type.load.hasPolymorphicDispatch && type.polymorphicDispatch) {
    const discSnake = toSnakeCase(type.polymorphicDispatch.discriminatorField);
    lines.push("");
    lines.push(`        # load polymorphic ${name} instance`);
    lines.push(`        instance = ${name}.load_${discSnake}(data, context)`);
  } else {
    lines.push("");
    lines.push(`        # create new instance`);
    lines.push(`        instance = ${name}()`);
  }

  // Blank line(s) after instance creation
  lines.push("");
  if (type.load.hasPolymorphicDispatch) {
    lines.push("");
  }

  // Per-property assignments
  for (const a of type.load.assignments) {
    lines.push(`        if data is not None and "${a.sourceName}" in data:`);
    lines.push(`            ${emitLoadAssignment(a)}`);
  }
  if (type.polymorphicDispatch?.defaultVariant?.isSelfReference) {
    lines.push("");
    lines.push(`        if type(instance) is ${name}:`);
    lines.push("            instance._raw = copy.deepcopy(data)");
  }

  // Context post-processing
  lines.push("        if context is not None:");
  lines.push("            instance = context.process_output(instance)");
  lines.push("        return instance");
  lines.push("");
  lines.push("");
}

function emitLoadAssignment(a: LoadAssignment): string {
  const snake = toSnakeCase(a.fieldName);
  const cat = a.category;
  if (a.enumName && a.allowedValues.length > 0 && Object.keys(a.parseAliases).length > 0) {
    return `instance.${snake} = ${enumParserName(a.enumName)}(data["${a.sourceName}"])`;
  }
  switch (cat.kind) {
    case "scalar":
    case "collection_scalar":
      return `instance.${snake} = data["${a.sourceName}"]`;
    case "dict":
      return dictLoadAssignment(snake, a.sourceName, cat.valueType);
    case "collection_complex":
      return `instance.${snake} = ${a.parentTypeName}.load_${snake}(data["${a.sourceName}"], context.at("${a.sourceName}"))`;
    case "complex":
      return `instance.${snake} = ${cat.typeName}.load(data["${a.sourceName}"], context.at("${a.sourceName}"))`;
  }

  function dictLoadAssignment(fieldName: string, sourceName: string, valueType: string | undefined): string {
    if (!valueType || valueType === "unknown") {
      return `instance.${fieldName} = data["${sourceName}"]`;
    }
    const valueExpr = dictValueLoadExpr("value", valueType, `context.at("${sourceName}").at(key)`);
    return `instance.${fieldName} = {key: ${valueExpr} for key, value in data["${sourceName}"].items()}`;
  }

  function dictValueLoadExpr(valueExpr: string, valueType: string, contextExpr: string): string {
    switch (TYPE_MAP[valueType]) {
      case "str":
        return `str(${valueExpr})`;
      case "int":
        return `int(${valueExpr})`;
      case "float":
        return `float(${valueExpr})`;
      case "bool":
        return `bool(${valueExpr})`;
      case "Any":
        return valueExpr;
      default:
        return `${valueType}.load(${valueExpr}, ${contextExpr})`;
    }
  }
}

/**
 * Emit a single coercion branch — direct property setting with early return.
 *
 * For types where the coercion involves a dynamic discriminator with child
 * variants, falls back to calling the dispatch method.
 */
function emitCoercionBranch(
  typeName: string,
  c: CoercionDecl,
  type: TypeDecl,
  lines: string[],
): void {
  const pyScalar = TYPE_MAP[c.scalarType] || c.scalarType;
  lines.push(`        if isinstance(data, ${pyScalar}):`);

  if (c.needsDispatch && type.polymorphicDispatch) {
    // Dynamic discriminator — must go through dispatch
    const discSnake = toSnakeCase(type.polymorphicDispatch.discriminatorField);
    // Build a minimal dict for the dispatch method
    const dictFields = c.assignments.map(a => {
      const val = a.isInput ? "data" : `"${a.literalValue}"`;
      return `"${a.fieldName}": ${val}`;
    });
    lines.push(`            return ${typeName}.load_${discSnake}({${dictFields.join(", ")}}, context)`);
  } else {
    // Direct property setting — no intermediate dict
    lines.push(`            instance = ${typeName}()`);
    for (const a of c.assignments) {
      const snake = toSnakeCase(a.fieldName);
      if (a.isInput) {
        lines.push(`            instance.${snake} = data`);
      } else {
        lines.push(`            instance.${snake} = "${a.literalValue}"`);
      }
    }
    lines.push("            if context is not None:");
    lines.push("                instance = context.process_output(instance)");
    lines.push("            return instance");
  }
}

// ============================================================================
// Collection helpers (load_X / save_X)
// ============================================================================

function emitCollectionLoadHelper(parentName: string, helper: CollectionHelperDecl, lines: string[]): void {
  const snake = toSnakeCase(helper.propertyName);
  const elemName = helper.elementTypeName.name;
  const shorthandField = entryShorthandTarget(helper, "kind");

  lines.push("");
  lines.push("    @staticmethod");
  lines.push(`    def load_${snake}(data: dict | list, context: LoadContext | None) -> list[${elemName}]:`);
  lines.push("        if context is None:");
  lines.push(`            context = LoadContext(path="${helper.propertyName}")`);
  lines.push("        if isinstance(data, dict):");
  lines.push(`            # convert simple named ${helper.propertyName} to list of ${elemName}`);
  lines.push("            result = []");
  lines.push("            for k, v in data.items():");
  lines.push("                if isinstance(v, list):");
  lines.push('                    raise TypeError(f"{context.at(k).path}: invalid named collection entry category array")');
  lines.push("                if isinstance(v, dict):");
  lines.push("                    # value is an object, spread its properties");
  lines.push(`                    result.append(${elemName}.load({"name": k, **v}, context.at(k)))`);
  lines.push("                else:");
  emitPyEntryShorthandArms(helper, shorthandField, elemName, lines);
  lines.push("            return result");
  lines.push(`        return [${elemName}.load(item, context.at_index(index)) for index, item in enumerate(data)]`);
}

/**
 * Emit the immediate-scalar branch of a name-keyed collection entry.
 *
 * With `@entryShorthand` declared, each `@coerce` scalar type contributes an arm
 * that applies that coercion's constant assignments (typically the discriminator)
 * and routes the raw scalar to the declared value field. Without it, this falls
 * back to the historical single-field assignment so existing schemas are unchanged.
 */
function emitPyEntryShorthandArms(
  helper: CollectionHelperDecl,
  shorthandField: string,
  elemName: string,
  lines: string[],
): void {
  const shorthand = helper.entryShorthand;
  const indent = "                    ";

  if (!shorthand || shorthand.cases.length === 0) {
    lines.push(`${indent}# value is a scalar, use it as the primary property`);
    lines.push(
      `${indent}result.append(${elemName}.load({"name": k, "${shorthandField}": v}, context.at(k)))`,
    );
    return;
  }

  lines.push(`${indent}# value is a scalar, infer the entry shape from its type`);
  let first = true;
  for (const entryCase of orderedEntryShorthandCases(shorthand.cases)) {
    const check = pyScalarValueCheck(entryCase.scalarType);
    if (!check) continue;
    const fields = entryCase.assignments
      .map(a => `"${a.fieldName}": ${pythonLiteral(a.literalValue)}`)
      .concat(`"${shorthand.valueField}": v`)
      .join(", ");
    lines.push(`${indent}${first ? "if" : "elif"} ${check}:`);
    lines.push(`${indent}    shorthand = {${fields}}`);
    first = false;
  }
  lines.push(`${indent}else:`);
  lines.push(`${indent}    shorthand = {"${shorthand.valueField}": v}`);
  lines.push(
    `${indent}result.append(${elemName}.load({"name": k, **shorthand}, context.at(k)))`,
  );
}

/**
 * Runtime predicate recognising a decoded value of the given TypeSpec scalar.
 *
 * The integral check explicitly excludes `bool` because Python's `bool` is a
 * subclass of `int`, so a bare `isinstance(v, int)` claims every boolean. That
 * exclusion makes the arms order-independent rather than relying on emission order.
 */
function pyScalarValueCheck(scalarType: string): string | null {
  if (isIntegralScalar(scalarType)) return "isinstance(v, int) and not isinstance(v, bool)";
  if (isFractionalScalar(scalarType)) return "isinstance(v, float)";
  if (isStringEncodedScalar(scalarType)) return "isinstance(v, str)";
  if (isBooleanScalar(scalarType)) return "isinstance(v, bool)";
  return null;
}

/**
 * Render a coercion constant as a Python literal, preserving its declared JSON type.
 *
 * Python spells booleans and null differently from JSON, and stringifying every
 * constant would retype a schema that expands into a boolean or numeric value.
 */
function pythonLiteral(value: string | number | boolean | null): string {
  if (value === null) return "None";
  if (typeof value === "boolean") return value ? "True" : "False";
  if (typeof value === "number") return String(value);
  return JSON.stringify(value);
}

function emitCollectionSaveHelper(parentName: string, helper: CollectionHelperDecl, lines: string[]): void {
  const snake = toSnakeCase(helper.propertyName);
  const elemName = helper.elementTypeName.name;

  lines.push("    @staticmethod");
  lines.push(`    def save_${snake}(items: list[${elemName}], context: SaveContext | None) -> dict[str, Any] | list[dict[str, Any]]:`);
  lines.push("        if context is None:");
  lines.push("            context = SaveContext()");

  if (helper.hasNameProperty) {
    lines.push("");
    lines.push("        serialized = [dict(item.save(context)) for item in items]");
    lines.push("        for item_data in serialized:");
    lines.push('            if item_data.get("name") == "":');
    lines.push('                item_data.pop("name")');
    lines.push("");
    lines.push('        if context.collection_format == "array":');
    lines.push("            return serialized");
    lines.push("");
    lines.push("        names: set[str] = set()");
    lines.push("        for item_data in serialized:");
    lines.push('            name = item_data.get("name")');
    lines.push("            if not isinstance(name, str) or not name or name in names:");
    lines.push("                return serialized");
    lines.push("            names.add(name)");
    lines.push("");
    lines.push("        # Object format: use name as key");
    lines.push("        result: dict[str, Any] = {}");
    lines.push("        for item, item_data in zip(items, serialized):");
    lines.push('            name = item_data.pop("name")');
    lines.push("            # Check if we can use shorthand (only primary property set)");
    lines.push("            if context.use_shorthand and hasattr(item, '_shorthand_property'):");
    lines.push("                shorthand_prop = item._shorthand_property");
    lines.push("                if shorthand_prop and len(item_data) == 1 and shorthand_prop in item_data:");
    lines.push("                    result[name] = item_data[shorthand_prop]");
    lines.push("                    continue");
    lines.push("            result[name] = item_data");
    lines.push("        return result");
  } else {
    lines.push("");
    lines.push("        # The schema declares an ordered collection, so preserve array format");
    lines.push("        return [item.save(context) for item in items]");
  }
}

/**
 * Does this dispatch absorb unrecognized discriminator values into a carrier rather than
 * rejecting them? Mirrors `absorbsUnknownIntoBase` in the Go emitter and
 * `absorbsUnknownValues` in the TypeScript emitter; the predicate is deliberately identical
 * across backends so they agree on which schemas are open.
 */
function absorbsUnknownValues(dispatch: PolymorphicDispatchDecl | null | undefined): boolean {
  if (!dispatch) {
    return false;
  }
  if (dispatch.defaultVariant) {
    return dispatch.defaultVariant.isSelfReference;
  }
  return !isClosedPolymorphicDispatch(dispatch);
}

/**
 * An abstract base with an open discriminator has no wildcard self-variant, so unrecognized
 * values need a concrete subclass to land in.
 */
function needsUnknownCarrier(type: TypeDecl): boolean {
  const dispatch = type.polymorphicDispatch;
  if (!dispatch || !type.isAbstract) {
    return false;
  }
  return !dispatch.defaultVariant && !isClosedPolymorphicDispatch(dispatch);
}

function unknownCarrierName(parentName: string): string {
  return `Unknown${parentName}`;
}

// ============================================================================
// Polymorphic dispatch
// ============================================================================

function emitPolymorphicDispatch(
  parentName: string,
  dispatch: PolymorphicDispatchDecl,
  isAbstract: boolean,
  lines: string[],
  carrier?: string,
): void {
  const discSnake = toSnakeCase(dispatch.discriminatorField);
  const isClosed = isClosedPolymorphicDispatch(dispatch);
  lines.push("    @staticmethod");
  lines.push(`    def load_${discSnake}(data: dict, context: LoadContext | None) -> "${parentName}":`);
  lines.push(`        # load polymorphic ${parentName} instance`);
  lines.push(`        if data is not None and data.get("${dispatch.discriminatorField}") is not None and str(data["${dispatch.discriminatorField}"]) != "":`);
  lines.push(`            discriminator_value = str(data["${dispatch.discriminatorField}"])`);

  for (let i = 0; i < dispatch.variants.length; i++) {
    const v = dispatch.variants[i];
    const keyword = i === 0 ? "if" : "elif";
    lines.push(`            ${keyword} discriminator_value == "${v.value}":`);
    lines.push(`                return ${v.typeName.name}.load(data, context)`);
  }

  // Default handling — matches template whitespace exactly
  if (dispatch.defaultVariant) {
    lines.push("");
    lines.push("            else:");
    if (dispatch.defaultVariant.isSelfReference) {
      lines.push(`                # create new instance (stop recursion)`);
      lines.push(`                return ${parentName}()`);
    } else {
      lines.push("");
      lines.push(`                # load default instance`);
      lines.push(`                return ${dispatch.defaultVariant.typeName.name}.load(data, context)`);
    }
  } else if (carrier) {
    lines.push("");
    lines.push("            else:");
    lines.push(`                # absorb unrecognized discriminator`);
    lines.push(`                return ${carrier}.load(data, context)`);
  } else {
    lines.push("");
    lines.push("            else:");
    lines.push(`                raise ValueError(f"Unknown ${parentName} discriminator field '${dispatch.discriminatorField}' value: {discriminator_value}")`);
  }

  lines.push("        else:");
  if (carrier) {
    // Matches the Go and TypeScript backends, which absorb a missing discriminator into the
    // same carrier they use for an unrecognized one. No vector covers this case; the choice
    // is made for cross-backend consistency, not from a stated requirement.
    lines.push(`            # absorb missing discriminator`);
    lines.push(`            return ${carrier}.load(data, context)`);
  } else if (isClosed || isAbstract) {
    lines.push("");
    lines.push(`            raise ValueError("Missing ${parentName} discriminator property: '${dispatch.discriminatorField}'")`);
  } else {
    lines.push(`            # create new instance`);
    lines.push(`            return ${parentName}()`);
  }
  lines.push("");
}

// ============================================================================
// save() method
// ============================================================================

function emitSaveMethod(type: TypeDecl, lines: string[]): void {
  const name = type.typeName.name;

  lines.push(`    def save(self, context: SaveContext | None = None) -> dict[str, Any]:`);
  lines.push(`        """Save the ${name} instance to a dictionary.`);
  lines.push("        Args:");
  lines.push("            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.");
  lines.push("        Returns:");
  lines.push("            dict[str, Any]: The dictionary representation of this instance.");
  lines.push("");
  lines.push(`        """`);
  lines.push("        obj = self");
  lines.push("        if context is not None:");
  lines.push("            obj = context.process_object(obj)");
  lines.push("");

  if (type.save.hasBase) {
    lines.push("");
    lines.push("        # Start with parent class properties");
    lines.push("        result = super().save(context)");
    lines.push("");
  } else if (absorbsUnknownValues(type.polymorphicDispatch)) {
    lines.push("");
    lines.push("        result: dict[str, Any] = copy.deepcopy(obj._raw)");
  } else {
    lines.push("");
    lines.push("        result: dict[str, Any] = {}");
  }

  // Per-property save assignments
  lines.push("");
  for (const a of type.save.assignments) {
    const snake = toSnakeCase(a.fieldName);
    lines.push(`        if obj.${snake} is not None:`);
    lines.push(`            ${emitSaveAssignment(a)}`);
  }

  // Context post-processing (only for root types without base)
  if (!type.save.hasBase) {
    lines.push("");
    lines.push("        if context is not None:");
    lines.push("            result = context.process_dict(result)");
  }
  lines.push("        return result");
  lines.push("");
}

function emitSaveAssignment(a: SaveAssignment): string {
  const snake = toSnakeCase(a.fieldName);
  const cat = a.category;
  switch (cat.kind) {
    case "scalar":
    case "collection_scalar":
      return `result["${a.targetName}"] = obj.${snake}`;
    case "dict":
      if (cat.valueType && cat.valueType !== "unknown" && !TYPE_MAP[cat.valueType]) {
        return `result["${a.targetName}"] = {key: value.save(context) for key, value in obj.${snake}.items()}`;
      }
      return `result["${a.targetName}"] = obj.${snake}`;
    case "collection_complex":
      return `result["${a.targetName}"] = ${a.parentTypeName}.save_${snake}(obj.${snake}, context)`;
    case "complex":
      return `result["${a.targetName}"] = obj.${snake}.save(context)`;
  }
}

// ============================================================================
// to_wire() method
// ============================================================================

function emitToWireMethod(type: TypeDecl, lines: string[]): void {
  const name = type.typeName.name;
  const wire = type.wire!;

  lines.push(`    def to_wire(self, provider: str) -> dict[str, Any]:`);
  lines.push(`        """Convert to provider-specific wire format.`);
  lines.push("        Args:");
  lines.push("            provider (str): The provider to convert to (e.g., \"openai\", \"anthropic\").");
  lines.push("        Returns:");
  lines.push("            dict[str, Any]: The wire-format dictionary with provider-specific field names.");
  lines.push("");
  lines.push(`        """`);
  lines.push("        data = self.save()");
  lines.push("        result: dict[str, Any] = {}");

  // Build the wire_map literal from the IR mappings
  lines.push("        wire_map: dict[str, dict[str, str]] = {");
  for (const mapping of wire.mappings) {
    const entries = Object.entries(mapping.wireNames)
      .map(([provider, wireName]) => `"${provider}": "${wireName}"`)
      .join(", ");
    lines.push(`            "${mapping.fieldName}": {${entries}},`);
  }
  lines.push("        }");

  lines.push("        for key, value in data.items():");
  lines.push("            mapping = wire_map.get(key)");
  lines.push("            if mapping is not None and provider in mapping:");
  lines.push("                result[mapping[provider]] = value");
  lines.push("        return result");
  lines.push("");
}

// ============================================================================
// to_yaml() / to_json() methods
// ============================================================================

function emitToYaml(name: string, lines: string[]): void {
  lines.push(`    def to_yaml(self, context: SaveContext | None = None) -> str:`);
  lines.push(`        """Convert the ${name} instance to a YAML string.`);
  lines.push("        Args:");
  lines.push("            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.");
  lines.push("        Returns:");
  lines.push("            str: The YAML string representation of this instance.");
  lines.push("");
  lines.push(`        """`);
  lines.push("        if context is None:");
  lines.push("            context = SaveContext()");
  lines.push("        return context.to_yaml(self.save(context))");
  lines.push("");
}

function emitToJson(name: string, lines: string[]): void {
  lines.push(`    def to_json(self, context: SaveContext | None = None, indent: int = 2) -> str:`);
  lines.push(`        """Convert the ${name} instance to a JSON string.`);
  lines.push("        Args:");
  lines.push("            context (Optional[SaveContext]): Optional context with pre/post processing callbacks.");
  lines.push("            indent (int): Number of spaces for indentation. Defaults to 2.");
  lines.push("        Returns:");
  lines.push("            str: The JSON string representation of this instance.");
  lines.push("");
  lines.push(`        """`);
  lines.push("        if context is None:");
  lines.push("            context = SaveContext()");
  lines.push("        return context.to_json(self.save(context), indent)");
  lines.push("");
}

function emitPydanticInteropMethods(name: string, lines: string[]): void {
  lines.push("");
  lines.push("    @classmethod");
  lines.push(`    def model_validate(cls, obj: Any, *args: Any, **kwargs: Any) -> "${name}":`);
  lines.push("        \"\"\"Validate through Typra's authoritative load contract.\"\"\"");
  lines.push("        if args or kwargs:");
  lines.push("            raise TypeError(\"Typra Pydantic mode delegates validation to load(); model_validate arguments are unsupported.\")");
  lines.push("        if isinstance(obj, cls):");
  lines.push("            return obj");
  lines.push("        return cls.load(obj)");
  lines.push("");
  lines.push("    def model_dump(self, *args: Any, **kwargs: Any) -> dict[str, Any]:");
  lines.push("        \"\"\"Serialize through Typra's authoritative save contract.\"\"\"");
  lines.push("        if args or kwargs:");
  lines.push("            raise TypeError(\"Typra Pydantic mode delegates serialization to save(); model_dump arguments are unsupported.\")");
  lines.push("        return self.save()");
  lines.push("");
  lines.push("    def model_dump_json(self, *args: Any, **kwargs: Any) -> str:");
  lines.push("        \"\"\"Serialize JSON through Typra's authoritative to_json contract.\"\"\"");
  lines.push("        indent = kwargs.pop(\"indent\", 2)");
  lines.push("        if args or kwargs:");
  lines.push("            raise TypeError(\"Typra Pydantic mode delegates JSON serialization to to_json(); unsupported model_dump_json arguments were provided.\")");
  lines.push("        return self.to_json(indent=indent)");
  lines.push("");
}

// ============================================================================
// Factory methods
// ============================================================================

function emitFactory(parentName: string, factory: FactoryDecl, visitor: ExprVisitor, fieldNames: Set<string>, lines: string[]): void {
  const params = Object.entries(factory.params)
    .map(([pName, pType]) => `${toSnakeCase(pName)}: ${paramType(pType)}`)
    .join(", ");
  const paramStr = params ? `, ${params}` : "";

  // In Python, a @classmethod with the same name as a dataclass field shadows
  // the field's default. Prefix with create_ to avoid the collision.
  const methodName = fieldNames.has(factory.name) ? `create_${factory.name}` : factory.name;

  lines.push("    @classmethod");
  lines.push(`    def ${methodName}(cls${paramStr}) -> "${parentName}":`);
  lines.push(`        """Create a ${parentName} with preset field values."""`);
  lines.push(`        return ${visitor.visitExpr(factory.body)}`);
}
